// <auto-generated />

namespace Samples.Partials
{
    public static class Module
    {
    }

    public static partial class Hooks
    {
        public static string label()
        {
            return "hook";
        }
    }

    public sealed partial class Customer
    {
        public Customer(string Name)
        {
            this.Name = Name;
        }

        public string Name { get; }

        public override bool Equals(object obj)
        {
            var other = obj as Customer;
            return other != null && object.Equals(Name, other.Name);
        }

        public override int GetHashCode()
        {
            unchecked
            {
                var hash = 17;
                hash = (hash * 397) ^ (object.Equals(Name, null) ? 0 : Name.GetHashCode());
                return hash;
            }
        }
    }

    public partial class Greeter
    {
        public string Echo(string value)
        {
            return value;
        }
    }

    public partial interface IGreeter
    {
        string Echo(string value);
    }
}
