// <auto-generated />

namespace Samples.Delegates
{
    public static class Module
    {
    }

    public delegate string Transformer(string value);

    public delegate string Project<T>(T value)
        where T : class;
}
