// <auto-generated />

using System;

namespace Samples.Delegates
{
    public static class Module
    {
    }

    [ObsoleteAttribute("Use NewTransformer.")]
    public delegate string Transformer(string value);

    [ObsoleteAttribute("Use NewProject.")]
    public delegate string Project<T>(T value)
        where T : class;

    public delegate string Joiner(string separator, params string[] values);
}
