// <auto-generated />

namespace Samples.Lock
{
    public static class Module
    {
        public static string pulse(object gate)
        {
            lock (gate)
            {
                gate.ToString();
            }
            return "done";
        }
    }
}
