// <auto-generated />

using TypeSharp.Runtime;

namespace Samples.TypeLevelUnion
{
    public static class Module
    {
        internal static string normalizeInternal(object id)
        {
            return new System.Func<string>(delegate()
            {
                var __match0 = id;
                if (__match0 is string text)
                {
                    if (text != "")
                    {
                        return text;
                    }
                }

                if (__match0 is int number)
                {
                    if (number > 0)
                    {
                        return number.ToString();
                    }
                }

                {
                    return "";
                }

                throw TypeSharpPattern.NoMatch(__match0);
            })();
        }

        public static string normalizeText(string text)
        {
            return normalizeInternal(text);
        }

        public static string normalizeNumber(int number)
        {
            return normalizeInternal(number);
        }
    }
}
