// <auto-generated />

namespace Samples.Properties
{
    public static class Module
    {
    }

    public class BuildInfo
    {
        public string Name { get; } = "build";

        public static string Version { get; } = "1.0";

        public string Echo(string value)
        {
            return value;
        }
    }
}
