// <auto-generated />

namespace Samples.InterfaceEvents
{
    public static class Module
    {
    }

    public interface INotifier
    {
        event ChangedHandler Changed;

        string Echo(string value);
    }

    public delegate void ChangedHandler(string value);
}
