// <auto-generated />

namespace Samples.InterfaceProperties
{
    public static class Module
    {
    }

    public interface IBuildInfo
    {
        string Name { get; set; }

        int Version { get; set; }
    }
}
