// <auto-generated />

using System;

namespace Samples.TypeAttributes
{
    public static class Module
    {
    }

    [ObsoleteAttribute("Use NewGreeter.")]
    public class Greeter
    {
        public string Echo(string value)
        {
            return value;
        }
    }

    [ObsoleteAttribute("Use INewGreeter.")]
    public interface IGreeter
    {
        string Echo(string value);
    }
}
