// <auto-generated />

namespace Samples.MultiplicativeCompoundAssignment
{
    public static class Module
    {
        public static int adjust(int value, short factor)
        {
            var result = value;
            result *= factor;
            result /= 2;
            result %= 5;
            return result;
        }

        public static long adjustLong(long value, int divisor)
        {
            var result = value;
            result *= 3;
            result /= divisor;
            result %= 7;
            return result;
        }

        public static float scaleFloat(float value, int factor)
        {
            var result = value;
            result *= factor;
            result /= factor;
            result %= 2;
            return result;
        }

        public static double scaleDouble(double value, float factor)
        {
            var result = value;
            result *= factor;
            result /= 2;
            result %= factor;
            return result;
        }

        public static decimal scaleDecimal(decimal value, int factor)
        {
            var result = value;
            result *= factor;
            result /= 2m;
            result %= factor;
            return result;
        }
    }
}
