// <auto-generated />

namespace Samples.GenericConstraints
{
    public static class Module
    {
        public static T keep<T>(T value)
            where T : class, IEntity
        {
            return value;
        }
    }

    public class Repository<T>
        where T : class, IEntity, new()
    {
        public T Keep(T value)
        {
            return value;
        }
    }

    public interface IEntity
    {
        string Id();
    }

    public interface IFactory
    {
        T Create<T>()
            where T : class, new();
    }
}
