// <auto-generated />

namespace Samples.Extensions
{
    public static class Module
    {
    }

    public static class StringExtensions
    {
        public static bool HasPrefix(this string text, string prefix)
        {
            return text.StartsWith(prefix);
        }
    }
}
