// <auto-generated />

using System.Collections.Generic;

namespace Samples.Collections
{
    public static class Module
    {
        public static string[] names()
        {
            return new string[] { "Ada", "Grace" };
        }

        public static string[] emptyNames()
        {
            return new string[] { };
        }

        public static int[] numbers()
        {
            var values = new int[] { 1, 2, 3 };
            return values;
        }

        public static List<string> nameList()
        {
            return new List<string> { "Ada", "Grace" };
        }

        public static List<string> emptyNameList()
        {
            return new List<string> { };
        }

        public static List<int> numberList()
        {
            var values = new List<int> { 1, 2, 3 };
            return values;
        }
    }
}
