// <auto-generated />

namespace Samples.Collections
{
    public static class Module
    {
        public static string[] names()
        {
            return new string[] { "Ada", "Grace" };
        }

        public static string[] emptyNames()
        {
            return new string[] { };
        }

        public static int[] numbers()
        {
            var values = new int[] { 1, 2, 3 };
            return values;
        }
    }
}
