// <auto-generated />

namespace Samples.BooleanBitwise
{
    public static class Module
    {
        public static bool both(bool left, bool right)
        {
            return left & right;
        }

        public static bool either(bool left, bool right)
        {
            return left | right;
        }

        public static bool toggled(bool left, bool right)
        {
            return left ^ right;
        }

        public static bool combined(bool left, bool right)
        {
            return (left & right) | (left ^ right);
        }
    }
}
