// <auto-generated />

namespace Samples.GenericOptionalDefaultParameterLowering
{
    public static class Module
    {
        internal static T choose<T>(T value, string fallback = "fallback")
        {
            return value;
        }

        internal static bool flag<T>(T value, bool enabled = true)
        {
            return enabled;
        }

        internal static int amount<T>(T value, int count = 3)
        {
            return count;
        }

        internal static string maybe<T>(T value, string label = null)
        {
            return label;
        }

        internal static string decorate<T>(T value, string prefix = "item")
        {
            return prefix;
        }

        public static string main()
        {
            var direct = choose("value");
            var explicitValue = choose<int>(42);
            var full = choose("value", "manual");
            var namedDefault = choose("named");
            var piped = choose("pipe");
            var pipedExplicit = choose<int>(7);
            var flagText = flag("value").ToString();
            var amountText = amount("value").ToString();
            var maybeValue = maybe("value");
            var decorated = decorate("value");
            return direct + explicitValue.ToString() + full + namedDefault + piped + pipedExplicit.ToString() + flagText + amountText + (maybeValue ?? "") + decorated;
        }
    }
}
