// <auto-generated />

namespace Samples.Properties
{
    public static class Module
    {
    }

    public class RuntimeOptions
    {
        public string Mode { get; set; } = "debug";

        public static string Channel { get; set; } = "local";

        public string Echo(string value)
        {
            return value;
        }
    }
}
