// <auto-generated />

namespace Samples.GenericNamedArgumentLowering
{
    public static class Module
    {
        internal static T choose<T>(T left, T right)
        {
            return left;
        }

        internal static T pairLeft<T, U>(T left, U right)
        {
            return left;
        }

        internal static T keepWithPrefix<T>(T value, string prefix)
        {
            return value;
        }

        public static string main()
        {
            var direct = choose("a", "b");
            var explicitValue = choose<string>("c", "d");
            var mixed = choose<string>("e", "f");
            var mixedTypes = pairLeft("g", 1);
            var piped = choose("h", "i");
            var pipedExplicit = choose<int>(1, 2);
            var pipedMixed = keepWithPrefix(3, "n=");
            return direct + explicitValue + mixed + mixedTypes + piped + pipedExplicit.ToString() + pipedMixed.ToString();
        }
    }
}
