// <auto-generated />

using System.Collections.Generic;

namespace Samples.Yield
{
    public static class Module
    {
        public static IEnumerable<string> names()
        {
            yield return "Ada";
            yield return "Grace";
        }
    }
}
