// <auto-generated />

namespace Samples.LogicalUnsignedShift
{
    public static class Module
    {
        public static int signed(int value, byte count)
        {
            return unchecked((int)(unchecked((uint)(value)) >> count));
        }

        public static long signedLong(long value, short count)
        {
            return unchecked((long)(unchecked((ulong)(value)) >> count));
        }

        public static int small(sbyte value, int count)
        {
            return unchecked((int)(unchecked((uint)(value)) >> count));
        }

        public static uint unsigned(uint value, int count)
        {
            return value >> count;
        }

        public static ulong unsignedLong(ulong value, int count)
        {
            return value >> count;
        }

        public static int combined(int value)
        {
            return unchecked((int)(unchecked((uint)(unchecked((int)(unchecked((uint)(value)) >> 2)))) >> 1));
        }
    }
}
