// <auto-generated />

namespace Samples.IndexedAccess
{
    public static class Module
    {
        internal static string name()
        {
            return "Ada";
        }

        internal static int age()
        {
            return 42;
        }

        internal static string shapeName()
        {
            return "Grace";
        }

        internal static bool isAda(string name)
        {
            return name == "Ada";
        }
    }

    internal sealed class Customer
    {
        public Customer(string Name, int Age)
        {
            this.Name = Name;
            this.Age = Age;
        }

        public string Name { get; }
        public int Age { get; }

        public override bool Equals(object obj)
        {
            var other = obj as Customer;
            return other != null && object.Equals(Name, other.Name) && object.Equals(Age, other.Age);
        }

        public override int GetHashCode()
        {
            unchecked
            {
                var hash = 17;
                hash = (hash * 397) ^ (object.Equals(Name, null) ? 0 : Name.GetHashCode());
                hash = (hash * 397) ^ (object.Equals(Age, null) ? 0 : Age.GetHashCode());
                return hash;
            }
        }
    }
}
