using System.Text;
using TypeSharp.Compiler.Parsing;

namespace TypeSharp.Compiler.Backend;

public static class CSharpSourceBackend
{
    public static string Emit(SyntaxNode root)
    {
        var emitter = new Emitter();
        return emitter.Emit(root);
    }

    private sealed class Emitter
    {
        private readonly StringBuilder _builder = new();
        private readonly HashSet<string> _constructorCandidateNames = new(StringComparer.Ordinal);
        private readonly Dictionary<string, RecordShape> _records = new(StringComparer.Ordinal);
        private readonly Dictionary<string, TypeLevelUnionShape> _typeLevelUnions = new(StringComparer.Ordinal);
        private readonly Dictionary<string, UnionShape> _unions = new(StringComparer.Ordinal);
        private readonly Dictionary<string, string> _unionCaseFactories = new(StringComparer.Ordinal);
        private readonly Dictionary<string, string> _unionCaseValues = new(StringComparer.Ordinal);
        private Dictionary<string, string> _valueTypes = new(StringComparer.Ordinal);
        private int _temporaryIndex;

        public string Emit(SyntaxNode root)
        {
            var namespaceName = root.Children.FirstOrDefault(child => child.Kind == SyntaxKind.NamespaceDeclaration) is { } namespaceDeclaration
                ? GetQualifiedName(namespaceDeclaration)
                : "TypeSharp.Generated";

            var imports = CollectImports(root);
            var literals = root.Children
                .Where(child => child.Kind == SyntaxKind.LiteralDeclaration)
                .ToArray();

            var functions = root.Children
                .Where(child => child.Kind == SyntaxKind.FunctionDeclaration)
                .ToArray();

            var typeAliases = root.Children
                .Where(child => child.Kind == SyntaxKind.TypeAliasDeclaration)
                .ToArray();

            var modules = root.Children
                .Where(child => child.Kind == SyntaxKind.ModuleDeclaration)
                .ToArray();

            var records = root.Children
                .Where(child => child.Kind == SyntaxKind.RecordDeclaration)
                .ToArray();

            var unions = root.Children
                .Where(child => child.Kind == SyntaxKind.UnionDeclaration)
                .ToArray();

            var classes = root.Children
                .Where(child => child.Kind == SyntaxKind.ClassDeclaration)
                .ToArray();

            var interfaces = root.Children
                .Where(child => child.Kind == SyntaxKind.InterfaceDeclaration)
                .ToArray();

            foreach (var importedName in imports.ImportedNames)
            {
                _constructorCandidateNames.Add(importedName);
            }

            foreach (var typeAlias in typeAliases)
            {
                RegisterTypeAlias(typeAlias);
            }

            foreach (var record in records)
            {
                RegisterRecord(record);
            }

            foreach (var union in unions)
            {
                RegisterUnion(union);
            }

            _builder.AppendLine("// <auto-generated />");
            _builder.AppendLine();
            foreach (var import in imports.Usings)
            {
                _builder.AppendLine($"using {import};");
            }

            var needsRuntime = unions.Length > 0 || ContainsNode(root, SyntaxKind.MatchExpression);
            if (needsRuntime && !imports.Usings.Contains("TypeSharp.Runtime", StringComparer.Ordinal))
            {
                _builder.AppendLine("using TypeSharp.Runtime;");
            }

            foreach (var import in imports.StaticUsings)
            {
                _builder.AppendLine($"using static {import};");
            }

            if (imports.Usings.Count > 0 || imports.StaticUsings.Count > 0 || needsRuntime)
            {
                _builder.AppendLine();
            }

            _builder.AppendLine($"namespace {namespaceName}");
            _builder.AppendLine("{");
            _builder.AppendLine("    public static class Module");
            _builder.AppendLine("    {");

            foreach (var literal in literals)
            {
                EmitLiteralDeclaration(literal);
            }

            if (literals.Length > 0 && functions.Length > 0)
            {
                _builder.AppendLine();
            }

            for (var index = 0; index < functions.Length; index++)
            {
                if (index > 0)
                {
                    _builder.AppendLine();
                }

                EmitFunction(functions[index], isStatic: true);
            }

            _builder.AppendLine("    }");

            foreach (var module in modules)
            {
                _builder.AppendLine();
                EmitModuleDeclaration(module);
            }

            foreach (var recordDeclaration in records)
            {
                _builder.AppendLine();
                EmitRecordDeclaration(recordDeclaration);
            }

            foreach (var unionDeclaration in unions)
            {
                _builder.AppendLine();
                EmitUnionDeclaration(unionDeclaration);
            }

            foreach (var classDeclaration in classes)
            {
                _builder.AppendLine();
                EmitClassDeclaration(classDeclaration);
            }

            foreach (var interfaceDeclaration in interfaces)
            {
                _builder.AppendLine();
                EmitInterfaceDeclaration(interfaceDeclaration);
            }

            _builder.AppendLine("}");
            return _builder.ToString().Replace("\r\n", "\n", StringComparison.Ordinal);
        }

        private void RegisterRecord(SyntaxNode node)
        {
            var name = GetRecordDeclarationName(node);
            if (name.Length == 0)
            {
                return;
            }

            var parameters = GetParameters(node);
            _records[name] = new RecordShape(name, parameters);
            _constructorCandidateNames.Add(name);
        }

        private void RegisterTypeAlias(SyntaxNode node)
        {
            var name = GetTypeAliasDeclarationName(node);
            var target = node.Children.LastOrDefault(child => !child.IsToken);
            if (name.Length == 0 || target?.Kind != SyntaxKind.UnionType)
            {
                return;
            }

            var members = new List<TypeLevelUnionMemberShape>();
            var seen = new HashSet<string>(StringComparer.Ordinal);
            foreach (var member in target.Children.Where(child => !child.IsToken))
            {
                var sourceType = GetSourceTypeName(member);
                if (sourceType.Length == 0 || !seen.Add(sourceType))
                {
                    continue;
                }

                members.Add(new TypeLevelUnionMemberShape(sourceType, MapType(member)));
            }

            if (members.Count >= 2)
            {
                _typeLevelUnions[name] = new TypeLevelUnionShape(name, members);
            }
        }

        private void RegisterUnion(SyntaxNode node)
        {
            var unionName = GetUnionDeclarationName(node);
            if (unionName.Length == 0 || GetTypeParameterList(node).Length > 0)
            {
                return;
            }

            var cases = GetUnionCases(node);
            _unions[unionName] = new UnionShape(unionName, cases);
            foreach (var unionCase in cases)
            {
                if (unionCase.Parameters.Count == 0)
                {
                    _unionCaseValues[unionCase.Name] = $"{unionName}.{unionCase.Name}";
                }
                else
                {
                    _unionCaseFactories[unionCase.Name] = $"{unionName}.{unionCase.Name}";
                }
            }
        }

        private static CSharpImports CollectImports(SyntaxNode root)
        {
            var usings = new List<string>();
            var staticUsings = new List<string>();
            var importedNames = new List<string>();
            var seenUsings = new HashSet<string>(StringComparer.Ordinal);
            var seenStaticUsings = new HashSet<string>(StringComparer.Ordinal);
            var seenImportedNames = new HashSet<string>(StringComparer.Ordinal);

            foreach (var child in root.Children)
            {
                if (child.Kind is SyntaxKind.ImportNamedDeclaration or SyntaxKind.ImportTypeDeclaration)
                {
                    foreach (var importedName in GetNamedImportIdentifiers(child))
                    {
                        if (seenImportedNames.Add(importedName))
                        {
                            importedNames.Add(importedName);
                        }
                    }

                    var moduleSpecifier = child.Children.FirstOrDefault(grandchild => grandchild.IsToken && grandchild.Kind == SyntaxKind.StringLiteralToken);
                    if (TryUnquoteStringLiteral(moduleSpecifier?.Text, out var namespaceName) && seenUsings.Add(namespaceName))
                    {
                        usings.Add(namespaceName);
                    }

                    continue;
                }

                if (child.Kind == SyntaxKind.ImportStaticDeclaration)
                {
                    var typeName = child.Children.FirstOrDefault(grandchild => grandchild.Kind == SyntaxKind.TypeName);
                    var qualifiedName = GetQualifiedName(typeName);
                    if (qualifiedName.Length > 0 && seenStaticUsings.Add(qualifiedName))
                    {
                        staticUsings.Add(qualifiedName);
                    }
                }
            }

            return new CSharpImports(usings, staticUsings, importedNames);
        }

        private void EmitModuleDeclaration(SyntaxNode node)
        {
            var visibility = GetVisibility(node);
            var name = GetModuleDeclarationName(node);

            _builder.AppendLine($"    {visibility} static class {name}");
            _builder.AppendLine("    {");

            var literals = node.Children
                .Where(child => child.Kind == SyntaxKind.LiteralDeclaration)
                .ToArray();

            var functions = node.Children
                .Where(child => child.Kind == SyntaxKind.FunctionDeclaration)
                .ToArray();

            foreach (var literal in literals)
            {
                EmitLiteralDeclaration(literal);
            }

            if (literals.Length > 0 && functions.Length > 0)
            {
                _builder.AppendLine();
            }

            for (var index = 0; index < functions.Length; index++)
            {
                if (index > 0)
                {
                    _builder.AppendLine();
                }

                EmitFunction(functions[index], isStatic: true);
            }

            _builder.AppendLine("    }");
        }

        private void EmitRecordDeclaration(SyntaxNode node)
        {
            var visibility = GetVisibility(node);
            var name = GetRecordDeclarationName(node);
            var typeParameters = GetTypeParameterList(node);
            var parameters = GetParameters(node);

            _builder.AppendLine($"    {visibility} sealed class {name}{typeParameters}");
            _builder.AppendLine("    {");

            if (parameters.Count > 0)
            {
                _builder.AppendLine($"        public {name}({FormatParameters(parameters)})");
                _builder.AppendLine("        {");
                foreach (var parameter in parameters)
                {
                    _builder.AppendLine($"            this.{parameter.Name} = {parameter.Name};");
                }

                _builder.AppendLine("        }");
                _builder.AppendLine();
            }

            foreach (var parameter in parameters)
            {
                _builder.AppendLine($"        public {parameter.Type} {parameter.Name} {{ get; }}");
            }

            if (parameters.Count > 0)
            {
                _builder.AppendLine();
            }

            EmitRecordEquals(name, parameters);
            _builder.AppendLine();
            EmitRecordGetHashCode(parameters);

            _builder.AppendLine("    }");
        }

        private void EmitUnionDeclaration(SyntaxNode node)
        {
            var visibility = GetVisibility(node);
            var name = GetUnionDeclarationName(node);
            var typeParameters = GetTypeParameterList(node);
            var cases = GetUnionCases(node);
            var baseType = $"{name}{typeParameters}";

            _builder.AppendLine($"    {visibility} abstract class {baseType}");
            _builder.AppendLine("    {");
            _builder.AppendLine($"        private {name}()");
            _builder.AppendLine("        {");
            _builder.AppendLine("        }");

            foreach (var unionCase in cases)
            {
                _builder.AppendLine();
                EmitUnionCaseFactory(baseType, unionCase);
            }

            foreach (var unionCase in cases)
            {
                _builder.AppendLine();
                EmitUnionCaseClass(baseType, unionCase);
            }

            _builder.AppendLine("    }");
        }

        private void EmitUnionCaseFactory(string baseType, UnionCaseShape unionCase)
        {
            if (unionCase.Parameters.Count == 0)
            {
                _builder.AppendLine($"        public static {baseType} {unionCase.Name}");
                _builder.AppendLine("        {");
                _builder.AppendLine("            get");
                _builder.AppendLine("            {");
                _builder.AppendLine($"                return {unionCase.ClassName}.Instance;");
                _builder.AppendLine("            }");
                _builder.AppendLine("        }");
                return;
            }

            _builder.AppendLine($"        public static {baseType} {unionCase.Name}({FormatParameters(unionCase.Parameters)})");
            _builder.AppendLine("        {");
            _builder.AppendLine($"            return new {unionCase.ClassName}({FormatArgumentNames(unionCase.Parameters)});");
            _builder.AppendLine("        }");
        }

        private void EmitUnionCaseClass(string baseType, UnionCaseShape unionCase)
        {
            _builder.AppendLine($"        public sealed class {unionCase.ClassName} : {baseType}, ITypeSharpUnionCase");
            _builder.AppendLine("        {");
            if (unionCase.Parameters.Count == 0)
            {
                EmitPayloadlessUnionCaseBody(unionCase);
            }
            else
            {
                EmitPayloadUnionCaseBody(unionCase);
            }

            _builder.AppendLine("        }");
        }

        private void EmitPayloadlessUnionCaseBody(UnionCaseShape unionCase)
        {
            _builder.AppendLine($"            public static readonly {unionCase.ClassName} Instance = new {unionCase.ClassName}();");
            _builder.AppendLine();
            _builder.AppendLine($"            private {unionCase.ClassName}()");
            _builder.AppendLine("            {");
            _builder.AppendLine("            }");
            _builder.AppendLine();
            EmitUnionMetadataProperties(unionCase, hasPayload: false);
            _builder.AppendLine();
            _builder.AppendLine("            public object Payload");
            _builder.AppendLine("            {");
            _builder.AppendLine("                get");
            _builder.AppendLine("                {");
            _builder.AppendLine("                    throw new System.InvalidOperationException(\"Union case has no payload.\");");
            _builder.AppendLine("                }");
            _builder.AppendLine("            }");
            _builder.AppendLine();
            _builder.AppendLine("            public override bool Equals(object obj)");
            _builder.AppendLine("            {");
            _builder.AppendLine($"                return obj is {unionCase.ClassName};");
            _builder.AppendLine("            }");
            _builder.AppendLine();
            _builder.AppendLine("            public override int GetHashCode()");
            _builder.AppendLine("            {");
            _builder.AppendLine("                return TypeSharpUnion.CombineHash(Tag, null);");
            _builder.AppendLine("            }");
        }

        private void EmitPayloadUnionCaseBody(UnionCaseShape unionCase)
        {
            _builder.AppendLine($"            public {unionCase.ClassName}({FormatParameters(unionCase.Parameters)})");
            _builder.AppendLine("            {");
            foreach (var parameter in unionCase.Parameters)
            {
                _builder.AppendLine($"                this.{parameter.Name} = {parameter.Name};");
            }

            _builder.AppendLine("            }");
            _builder.AppendLine();
            foreach (var parameter in unionCase.Parameters)
            {
                _builder.AppendLine($"            public {parameter.Type} {parameter.Name} {{ get; }}");
            }

            _builder.AppendLine();
            EmitUnionMetadataProperties(unionCase, hasPayload: true);
            _builder.AppendLine();
            _builder.AppendLine("            public object Payload");
            _builder.AppendLine("            {");
            _builder.AppendLine("                get");
            _builder.AppendLine("                {");
            _builder.AppendLine($"                    return {FormatPayloadExpression(unionCase.Parameters)};");
            _builder.AppendLine("                }");
            _builder.AppendLine("            }");
            _builder.AppendLine();
            EmitUnionCaseEquals(unionCase);
            _builder.AppendLine();
            EmitUnionCaseGetHashCode(unionCase);
        }

        private void EmitUnionMetadataProperties(UnionCaseShape unionCase, bool hasPayload)
        {
            _builder.AppendLine("            public int Tag");
            _builder.AppendLine("            {");
            _builder.AppendLine("                get");
            _builder.AppendLine("                {");
            _builder.AppendLine($"                    return {unionCase.Tag};");
            _builder.AppendLine("                }");
            _builder.AppendLine("            }");
            _builder.AppendLine();
            _builder.AppendLine("            public string CaseName");
            _builder.AppendLine("            {");
            _builder.AppendLine("                get");
            _builder.AppendLine("                {");
            _builder.AppendLine($"                    return \"{unionCase.Name}\";");
            _builder.AppendLine("                }");
            _builder.AppendLine("            }");
            _builder.AppendLine();
            _builder.AppendLine("            public bool HasPayload");
            _builder.AppendLine("            {");
            _builder.AppendLine("                get");
            _builder.AppendLine("                {");
            _builder.AppendLine($"                    return {hasPayload.ToString().ToLowerInvariant()};");
            _builder.AppendLine("                }");
            _builder.AppendLine("            }");
        }

        private void EmitUnionCaseEquals(UnionCaseShape unionCase)
        {
            _builder.AppendLine("            public override bool Equals(object obj)");
            _builder.AppendLine("            {");
            _builder.AppendLine($"                var other = obj as {unionCase.ClassName};");
            var comparisons = string.Join(" && ", unionCase.Parameters.Select(parameter => $"object.Equals({parameter.Name}, other.{parameter.Name})"));
            _builder.AppendLine($"                return other != null && {comparisons};");
            _builder.AppendLine("            }");
        }

        private void EmitUnionCaseGetHashCode(UnionCaseShape unionCase)
        {
            _builder.AppendLine("            public override int GetHashCode()");
            _builder.AppendLine("            {");
            if (unionCase.Parameters.Count == 1)
            {
                _builder.AppendLine($"                return TypeSharpUnion.CombineHash(Tag, {unionCase.Parameters[0].Name});");
            }
            else
            {
                _builder.AppendLine($"                return TypeSharpEquality.CombineHash(Tag, {FormatArgumentNames(unionCase.Parameters)});");
            }

            _builder.AppendLine("            }");
        }

        private void EmitClassDeclaration(SyntaxNode node)
        {
            var visibility = GetVisibility(node);
            var name = GetClassDeclarationName(node);
            var typeParameters = GetTypeParameterList(node);

            _builder.AppendLine($"    {visibility} class {name}{typeParameters}");
            _builder.AppendLine("    {");

            var functions = node.Children
                .Where(child => child.Kind == SyntaxKind.FunctionDeclaration)
                .ToArray();

            for (var index = 0; index < functions.Length; index++)
            {
                if (index > 0)
                {
                    _builder.AppendLine();
                }

                EmitFunction(functions[index], isStatic: false);
            }

            _builder.AppendLine("    }");
        }

        private void EmitInterfaceDeclaration(SyntaxNode node)
        {
            var visibility = GetVisibility(node);
            var name = GetInterfaceDeclarationName(node);
            var typeParameters = GetTypeParameterList(node);

            _builder.AppendLine($"    {visibility} interface {name}{typeParameters}");
            _builder.AppendLine("    {");

            var functions = node.Children
                .Where(child => child.Kind == SyntaxKind.FunctionDeclaration)
                .ToArray();

            for (var index = 0; index < functions.Length; index++)
            {
                if (index > 0)
                {
                    _builder.AppendLine();
                }

                EmitInterfaceFunction(functions[index]);
            }

            _builder.AppendLine("    }");
        }

        private void EmitLiteralDeclaration(SyntaxNode node)
        {
            var visibility = GetVisibility(node);
            var name = GetLiteralDeclarationName(node);
            var initializer = GetInitializerExpression(node);
            var type = GetLiteralType(node, initializer);
            var storage = CanEmitConstLiteral(type, initializer) ? "const" : "static readonly";

            _builder.AppendLine($"        {visibility} {storage} {type} {name} = {EmitExpression(initializer)};");
        }

        private void EmitFunction(SyntaxNode node, bool isStatic)
        {
            var visibility = GetVisibility(node);
            var staticModifier = isStatic ? " static" : string.Empty;
            var asyncModifier = IsAsyncFunction(node) ? " async" : string.Empty;
            var name = GetDeclarationName(node);
            var typeParameters = GetTypeParameterList(node);
            var parameters = GetParameters(node);
            var returnType = GetReturnType(node);
            var body = node.Children.FirstOrDefault(child => child.Kind == SyntaxKind.FunctionBody);
            var expression = body?.Children.LastOrDefault(child => !child.IsToken);

            var previousValueTypes = _valueTypes;
            _valueTypes = new Dictionary<string, string>(previousValueTypes, StringComparer.Ordinal);
            foreach (var parameter in parameters)
            {
                _valueTypes[parameter.Name] = parameter.SourceType;
            }

            try
            {
                _builder.AppendLine($"        {visibility}{staticModifier}{asyncModifier} {returnType} {name}{typeParameters}({FormatParameters(parameters)})");
                _builder.AppendLine("        {");
                if (expression?.Kind == SyntaxKind.BlockExpression)
                {
                    EmitBlock(expression);
                }
                else
                {
                    _builder.AppendLine($"            return {EmitExpression(expression, returnType)};");
                }

                _builder.AppendLine("        }");
            }
            finally
            {
                _valueTypes = previousValueTypes;
            }
        }

        private void EmitRecordEquals(string name, IReadOnlyList<CSharpParameter> parameters)
        {
            _builder.AppendLine("        public override bool Equals(object obj)");
            _builder.AppendLine("        {");
            _builder.AppendLine($"            var other = obj as {name};");
            var comparisons = parameters.Count == 0
                ? "true"
                : string.Join(" && ", parameters.Select(parameter => $"object.Equals({parameter.Name}, other.{parameter.Name})"));
            _builder.AppendLine($"            return other != null && {comparisons};");
            _builder.AppendLine("        }");
        }

        private void EmitRecordGetHashCode(IReadOnlyList<CSharpParameter> parameters)
        {
            _builder.AppendLine("        public override int GetHashCode()");
            _builder.AppendLine("        {");
            _builder.AppendLine("            unchecked");
            _builder.AppendLine("            {");
            _builder.AppendLine("                var hash = 17;");
            foreach (var parameter in parameters)
            {
                _builder.AppendLine($"                hash = (hash * 397) ^ (object.Equals({parameter.Name}, null) ? 0 : {parameter.Name}.GetHashCode());");
            }

            _builder.AppendLine("                return hash;");
            _builder.AppendLine("            }");
            _builder.AppendLine("        }");
        }

        private void EmitInterfaceFunction(SyntaxNode node)
        {
            var name = GetDeclarationName(node);
            var typeParameters = GetTypeParameterList(node);
            var parameters = GetParameterList(node);
            var returnType = GetReturnType(node);

            _builder.AppendLine($"        {returnType} {name}{typeParameters}({parameters});");
        }

        private string GetParameterList(SyntaxNode function)
        {
            var parameterList = function.Children.FirstOrDefault(child => child.Kind == SyntaxKind.ParameterList);
            if (parameterList is null)
            {
                return string.Empty;
            }

            var parameters = parameterList.Children
                .Where(child => child.Kind == SyntaxKind.Parameter)
                .Select(EmitParameter);
            return string.Join(", ", parameters);
        }

        private IReadOnlyList<CSharpParameter> GetParameters(SyntaxNode declaration)
        {
            var parameterList = declaration.Children.FirstOrDefault(child => child.Kind == SyntaxKind.ParameterList);
            if (parameterList is null)
            {
                return [];
            }

            return parameterList.Children
                .Where(child => child.Kind == SyntaxKind.Parameter)
                .Select(GetParameter)
                .ToArray();
        }

        private static string FormatParameters(IReadOnlyList<CSharpParameter> parameters) =>
            string.Join(", ", parameters.Select(parameter => $"{parameter.Type} {parameter.Name}"));

        private static string FormatArgumentNames(IReadOnlyList<CSharpParameter> parameters) =>
            string.Join(", ", parameters.Select(parameter => parameter.Name));

        private static string FormatPayloadExpression(IReadOnlyList<CSharpParameter> parameters)
        {
            if (parameters.Count == 1)
            {
                return parameters[0].Name;
            }

            return $"new object[] {{ {FormatArgumentNames(parameters)} }}";
        }

        private IReadOnlyList<UnionCaseShape> GetUnionCases(SyntaxNode declaration)
        {
            var cases = new List<UnionCaseShape>();
            foreach (var unionCase in declaration.Children.Where(child => child.Kind == SyntaxKind.UnionCase))
            {
                var name = unionCase.Children.FirstOrDefault(child => child.IsToken && child.Kind == SyntaxKind.IdentifierToken)?.Text ?? string.Empty;
                if (name.Length == 0)
                {
                    continue;
                }

                cases.Add(new UnionCaseShape(
                    name,
                    $"{name}Case",
                    cases.Count,
                    GetParameters(unionCase)));
            }

            return cases;
        }

        private static string GetTypeParameterList(SyntaxNode declaration)
        {
            var typeParameterList = declaration.Children.FirstOrDefault(child => child.Kind == SyntaxKind.TypeParameterList);
            if (typeParameterList is null)
            {
                return string.Empty;
            }

            var parameters = typeParameterList.Children
                .Where(child => child.IsToken && child.Kind == SyntaxKind.IdentifierToken)
                .Select(child => child.Text ?? string.Empty)
                .Where(text => text.Length > 0)
                .ToArray();

            return parameters.Length == 0 ? string.Empty : $"<{string.Join(", ", parameters)}>";
        }

        private string EmitParameter(SyntaxNode parameter)
        {
            var parameterInfo = GetParameter(parameter);
            return $"{parameterInfo.Type} {parameterInfo.Name}";
        }

        private CSharpParameter GetParameter(SyntaxNode parameter)
        {
            var name = parameter.Children.FirstOrDefault(child => child.IsToken && child.Kind == SyntaxKind.IdentifierToken)?.Text;
            var annotation = parameter.Children.FirstOrDefault(child => child.Kind == SyntaxKind.TypeAnnotation);
            var typeNode = annotation?.Children.FirstOrDefault(child => !child.IsToken);
            return new CSharpParameter(MapType(typeNode), !string.IsNullOrWhiteSpace(name) ? name : "_", GetSourceTypeName(typeNode));
        }

        private void EmitBlock(SyntaxNode node)
        {
            var statements = node.Children.Where(child => !child.IsToken).ToArray();
            for (var index = 0; index < statements.Length; index++)
            {
                var statement = statements[index];
                var isLast = index == statements.Length - 1;

                if (statement.Kind == SyntaxKind.ValueDeclaration)
                {
                    EmitLocalDeclaration(statement);
                    continue;
                }

                var expression = statement.Kind == SyntaxKind.ExpressionStatement
                    ? statement.Children.FirstOrDefault(child => !child.IsToken)
                    : statement;

                if (isLast)
                {
                    _builder.AppendLine($"            return {EmitExpression(expression)};");
                }
                else
                {
                    _builder.AppendLine($"            {EmitExpression(expression)};");
                }
            }
        }

        private void EmitLocalDeclaration(SyntaxNode node)
        {
            var name = GetLocalDeclarationName(node);
            var initializer = node.Children
                .FirstOrDefault(child => child.Kind == SyntaxKind.Initializer)?
                .Children
                .FirstOrDefault(child => !child.IsToken);

            _builder.AppendLine($"            var {name} = {EmitExpression(initializer)};");
        }

        private string EmitExpression(SyntaxNode? node, string? expectedType = null)
        {
            if (node is null)
            {
                return "default(object)";
            }

            return node.Kind switch
            {
                SyntaxKind.LiteralExpression => EmitLiteral(node),
                SyntaxKind.IdentifierExpression => EmitIdentifier(node),
                SyntaxKind.MemberAccessExpression => EmitMemberAccess(node),
                SyntaxKind.CallExpression => EmitCall(node),
                SyntaxKind.NamedArgument => EmitNamedArgument(node),
                SyntaxKind.OutArgument => EmitOutArgument(node),
                SyntaxKind.InArgument => EmitInArgument(node),
                SyntaxKind.RefArgument => EmitRefArgument(node),
                SyntaxKind.LambdaExpression => EmitLambda(node),
                SyntaxKind.AssignmentExpression => EmitAssignment(node),
                SyntaxKind.RecordUpdateExpression => EmitRecordUpdate(node),
                SyntaxKind.MatchExpression => EmitMatch(node, expectedType ?? "object"),
                SyntaxKind.AwaitExpression => EmitAwait(node),
                _ => "default(object)"
            };
        }

        private string EmitIdentifier(SyntaxNode node)
        {
            var identifier = GetIdentifierText(node);
            if (_unionCaseValues.TryGetValue(identifier, out var caseValue))
            {
                return caseValue;
            }

            return identifier.Length == 0 ? "default" : identifier;
        }

        private string EmitMemberAccess(SyntaxNode node)
        {
            var receiver = node.Children.FirstOrDefault(child => !child.IsToken);
            var member = node.Children.LastOrDefault(child => child.IsToken && child.Kind == SyntaxKind.IdentifierToken);
            if (receiver is null || member?.Text is null)
            {
                return "default(object)";
            }

            return $"{EmitExpression(receiver)}.{member.Text}";
        }

        private string EmitCall(SyntaxNode node)
        {
            var callee = node.Children.FirstOrDefault(child => !child.IsToken);
            if (callee is null)
            {
                return "default(object)";
            }

            var arguments = node.Children
                .SkipWhile(child => !ReferenceEquals(child, callee))
                .Skip(1)
                .Where(child => !child.IsToken)
                .Select(child => EmitExpression(child));

            var argumentList = string.Join(", ", arguments);
            if (TryGetCallTarget(callee, out var callTarget))
            {
                return $"{callTarget}({argumentList})";
            }

            if (TryGetConstructorName(callee, out var constructorName))
            {
                return $"new {constructorName}({argumentList})";
            }

            return $"{EmitExpression(callee)}({argumentList})";
        }

        private string EmitAwait(SyntaxNode node)
        {
            var expression = node.Children.FirstOrDefault(child => !child.IsToken);
            return $"await {EmitExpression(expression)}";
        }

        private string EmitOutArgument(SyntaxNode node)
        {
            var expression = node.Children.FirstOrDefault(child => !child.IsToken);
            return $"out {EmitExpression(expression)}";
        }

        private string EmitNamedArgument(SyntaxNode node)
        {
            var name = node.Children.FirstOrDefault(child => child.IsToken && child.Kind == SyntaxKind.IdentifierToken)?.Text ?? string.Empty;
            var expression = node.Children.LastOrDefault(child => !child.IsToken);
            return name.Length == 0
                ? EmitExpression(expression)
                : $"{name}: {EmitExpression(expression)}";
        }

        private string EmitInArgument(SyntaxNode node)
        {
            var expression = node.Children.FirstOrDefault(child => !child.IsToken);
            return $"in {EmitExpression(expression)}";
        }

        private string EmitRefArgument(SyntaxNode node)
        {
            var expression = node.Children.FirstOrDefault(child => !child.IsToken);
            return $"ref {EmitExpression(expression)}";
        }

        private string EmitLambda(SyntaxNode node)
        {
            var parameter = node.Children.FirstOrDefault(child => child.IsToken && child.Kind == SyntaxKind.IdentifierToken)?.Text ?? "_";
            var body = node.Children.LastOrDefault(child => !child.IsToken);
            return $"{parameter} => {EmitExpression(body)}";
        }

        private string EmitAssignment(SyntaxNode node)
        {
            var expressions = node.Children.Where(child => !child.IsToken).ToArray();
            var operatorToken = node.Children.FirstOrDefault(child => child.IsToken);
            if (expressions.Length < 2 || operatorToken?.Text is null)
            {
                return "default(object)";
            }

            return $"{EmitExpression(expressions[0])} {operatorToken.Text} {EmitExpression(expressions[1])}";
        }

        private string EmitMatch(SyntaxNode node, string resultType)
        {
            var input = node.Children.FirstOrDefault(child => !child.IsToken && child.Kind != SyntaxKind.MatchArm);
            if (input is null)
            {
                return "default(object)";
            }

            if (!TryGetUnionShape(input, out var union))
            {
                return TryGetTypeLevelUnionShape(input, out var typeLevelUnion)
                    ? EmitTypeLevelUnionMatch(node, input, typeLevelUnion, resultType)
                    : "default(object)";
            }

            var matchValueName = $"__match{_temporaryIndex++}";
            var builder = new StringBuilder();
            builder.AppendLine($"new System.Func<{resultType}>(delegate()");
            builder.AppendLine("            {");
            builder.AppendLine($"                var {matchValueName} = {EmitExpression(input)};");

            var wroteArm = false;
            foreach (var arm in node.Children.Where(child => child.Kind == SyntaxKind.MatchArm))
            {
                if (!TryGetMatchArm(arm, union, out var unionCase, out var payloadVariable, out var expression))
                {
                    continue;
                }

                if (wroteArm)
                {
                    builder.AppendLine();
                }

                var predicate = unionCase.Parameters.Count == 0
                    ? "IsPayloadlessCase"
                    : "IsPayloadCase";
                builder.AppendLine($"                if (TypeSharpPattern.{predicate}({matchValueName}, {unionCase.Tag}))");
                builder.AppendLine("                {");
                if (payloadVariable.Length > 0 && unionCase.Parameters.Count == 1)
                {
                    builder.AppendLine($"                    var {payloadVariable} = TypeSharpPattern.RequirePayload<{unionCase.Parameters[0].Type}>({matchValueName}, {unionCase.Tag});");
                }

                builder.AppendLine($"                    return {EmitExpression(expression)};");
                builder.AppendLine("                }");
                wroteArm = true;
            }

            if (wroteArm)
            {
                builder.AppendLine();
            }

            builder.AppendLine($"                throw TypeSharpPattern.NoMatch({matchValueName});");
            builder.Append("            })()");
            return builder.ToString().Replace("\r\n", "\n", StringComparison.Ordinal);
        }

        private string EmitTypeLevelUnionMatch(SyntaxNode node, SyntaxNode input, TypeLevelUnionShape union, string resultType)
        {
            var matchValueName = $"__match{_temporaryIndex++}";
            var builder = new StringBuilder();
            builder.AppendLine($"new System.Func<{resultType}>(delegate()");
            builder.AppendLine("            {");
            builder.AppendLine($"                var {matchValueName} = {EmitExpression(input)};");

            var wroteArm = false;
            foreach (var arm in node.Children.Where(child => child.Kind == SyntaxKind.MatchArm))
            {
                if (!TryGetTypePatternMatchArm(arm, union, out var member, out var variableName, out var expression, out var isDiscard))
                {
                    continue;
                }

                if (wroteArm)
                {
                    builder.AppendLine();
                }

                if (isDiscard)
                {
                    builder.AppendLine("                {");
                    builder.AppendLine($"                    return {EmitExpression(expression)};");
                    builder.AppendLine("                }");
                }
                else
                {
                    builder.AppendLine($"                if ({matchValueName} is {member.CSharpType} {variableName})");
                    builder.AppendLine("                {");
                    builder.AppendLine($"                    return {EmitExpression(expression)};");
                    builder.AppendLine("                }");
                }

                wroteArm = true;
            }

            if (wroteArm)
            {
                builder.AppendLine();
            }

            builder.AppendLine($"                throw TypeSharpPattern.NoMatch({matchValueName});");
            builder.Append("            })()");
            return builder.ToString().Replace("\r\n", "\n", StringComparison.Ordinal);
        }

        private string EmitRecordUpdate(SyntaxNode node)
        {
            var receiver = node.Children.FirstOrDefault(child => !child.IsToken);
            var update = node.Children.LastOrDefault(child => child.Kind == SyntaxKind.RecordExpression);
            if (receiver is null || update is null || !TryGetRecordShape(receiver, out var record))
            {
                return "default(object)";
            }

            var receiverExpression = EmitExpression(receiver);
            var updatedFields = GetRecordFieldExpressions(update);
            var arguments = record.Parameters
                .Select(parameter => updatedFields.TryGetValue(parameter.Name, out var updatedValue)
                    ? updatedValue
                    : $"{receiverExpression}.{parameter.Name}");

            return $"new {record.Name}({string.Join(", ", arguments)})";
        }

        private Dictionary<string, string> GetRecordFieldExpressions(SyntaxNode recordExpression)
        {
            var fields = new Dictionary<string, string>(StringComparer.Ordinal);
            foreach (var field in recordExpression.Children.Where(child => child.Kind == SyntaxKind.RecordField))
            {
                var name = field.Children.FirstOrDefault(child => child.IsToken && child.Kind == SyntaxKind.IdentifierToken)?.Text ?? string.Empty;
                if (name.Length == 0)
                {
                    continue;
                }

                var expression = field.Children.LastOrDefault(child => !child.IsToken);
                fields[name] = expression is null ? name : EmitExpression(expression);
            }

            return fields;
        }

        private bool TryGetRecordShape(SyntaxNode receiver, out RecordShape record)
        {
            record = default;
            if (!TryGetExpressionType(receiver, out var typeName))
            {
                return false;
            }

            return _records.TryGetValue(typeName, out record);
        }

        private bool TryGetUnionShape(SyntaxNode receiver, out UnionShape union)
        {
            union = default;
            if (!TryGetExpressionType(receiver, out var typeName))
            {
                return false;
            }

            return _unions.TryGetValue(typeName, out union);
        }

        private bool TryGetTypeLevelUnionShape(SyntaxNode receiver, out TypeLevelUnionShape union)
        {
            union = default;
            if (!TryGetExpressionType(receiver, out var typeName))
            {
                return false;
            }

            return _typeLevelUnions.TryGetValue(typeName, out union);
        }

        private static bool TryGetMatchArm(
            SyntaxNode arm,
            UnionShape union,
            out UnionCaseShape unionCase,
            out string payloadVariable,
            out SyntaxNode? expression)
        {
            unionCase = default;
            payloadVariable = string.Empty;
            expression = null;

            var pattern = arm.Children.FirstOrDefault(child => child.Kind == SyntaxKind.Pattern);
            var caseName = pattern?.Children.FirstOrDefault(child => child.IsToken && child.Kind == SyntaxKind.IdentifierToken)?.Text ?? string.Empty;
            if (caseName.Length == 0)
            {
                return false;
            }

            var foundCase = union.Cases.FirstOrDefault(candidate => string.Equals(candidate.Name, caseName, StringComparison.Ordinal));
            if (foundCase.Name is null)
            {
                return false;
            }

            unionCase = foundCase;
            var argumentPattern = pattern?
                .Children
                .FirstOrDefault(child => child.Kind == SyntaxKind.PatternArgumentList)?
                .Children
                .FirstOrDefault(child => child.Kind == SyntaxKind.Pattern);
            payloadVariable = argumentPattern?.Children.FirstOrDefault(child => child.IsToken && child.Kind == SyntaxKind.IdentifierToken)?.Text ?? string.Empty;
            expression = arm.Children.LastOrDefault(child => !child.IsToken && child.Kind != SyntaxKind.Pattern);
            return expression is not null;
        }

        private bool TryGetTypePatternMatchArm(
            SyntaxNode arm,
            TypeLevelUnionShape union,
            out TypeLevelUnionMemberShape member,
            out string variableName,
            out SyntaxNode? expression,
            out bool isDiscard)
        {
            member = default;
            variableName = string.Empty;
            expression = null;
            isDiscard = false;

            var pattern = arm.Children.FirstOrDefault(child => child.Kind == SyntaxKind.Pattern);
            variableName = pattern?.Children.FirstOrDefault(child => child.IsToken && child.Kind == SyntaxKind.IdentifierToken)?.Text ?? string.Empty;
            if (variableName == "_")
            {
                expression = arm.Children.LastOrDefault(child => !child.IsToken && child.Kind != SyntaxKind.Pattern);
                isDiscard = expression is not null;
                return isDiscard;
            }

            var annotation = pattern?.Children.FirstOrDefault(child => child.Kind == SyntaxKind.TypeAnnotation);
            var typeNode = annotation?.Children.FirstOrDefault(child => !child.IsToken);
            var sourceType = GetSourceTypeName(typeNode);
            var foundMember = union.Members.FirstOrDefault(candidate => candidate.SourceType == sourceType);
            if (foundMember.SourceType is null)
            {
                return false;
            }

            member = foundMember;
            expression = arm.Children.LastOrDefault(child => !child.IsToken && child.Kind != SyntaxKind.Pattern);
            return variableName.Length > 0 && expression is not null;
        }

        private bool TryGetExpressionType(SyntaxNode node, out string typeName)
        {
            typeName = string.Empty;
            if (node.Kind != SyntaxKind.IdentifierExpression)
            {
                return false;
            }

            var name = node.Children.FirstOrDefault(child => child.IsToken && child.Kind == SyntaxKind.IdentifierToken)?.Text ?? string.Empty;
            if (name.Length == 0)
            {
                return false;
            }

            if (!_valueTypes.TryGetValue(name, out var knownType) || knownType.Length == 0)
            {
                return false;
            }

            typeName = knownType;
            return true;
        }

        private static string EmitLiteral(SyntaxNode node)
        {
            var token = node.Children.FirstOrDefault(child => child.IsToken);
            return token?.Kind switch
            {
                SyntaxKind.StringLiteralToken => token.Text ?? "\"\"",
                SyntaxKind.InterpolatedStringLiteralToken => token.Text ?? "\"\"",
                SyntaxKind.NumericLiteralToken => token.Text ?? "0",
                SyntaxKind.TrueKeyword => "true",
                SyntaxKind.FalseKeyword => "false",
                SyntaxKind.NullKeyword => "null",
                _ => "default(object)"
            };
        }

        private string GetReturnType(SyntaxNode function)
        {
            var annotation = function.Children.FirstOrDefault(child => child.Kind == SyntaxKind.TypeAnnotation);
            var typeNode = annotation?.Children.FirstOrDefault(child => !child.IsToken);
            return MapType(typeNode);
        }

        private string MapType(SyntaxNode? node)
        {
            if (node is null)
            {
                return "object";
            }

            if (node.Kind == SyntaxKind.TypeName)
            {
                if (TryGetGenericType(node, out var genericType))
                {
                    return genericType;
                }

                var name = GetQualifiedName(node);
                if (_typeLevelUnions.ContainsKey(name))
                {
                    return "object";
                }

                return name switch
                {
                    "bool" => "bool",
                    "byte" => "byte",
                    "char" => "char",
                    "decimal" => "decimal",
                    "double" => "double",
                    "float" => "float",
                    "int" => "int",
                    "long" => "long",
                    "object" => "object",
                    "sbyte" => "sbyte",
                    "short" => "short",
                    "string" => "string",
                    "uint" => "uint",
                    "ulong" => "ulong",
                    "ushort" => "ushort",
                    "void" or "unit" => "void",
                    _ => name
                };
            }

            if (node.Kind == SyntaxKind.ArrayType)
            {
                var elementType = node.Children.FirstOrDefault(child => !child.IsToken);
                return $"{MapType(elementType)}[]";
            }

            if (node.Kind is SyntaxKind.UnionType or SyntaxKind.RecordShapeType)
            {
                return "object";
            }

            return "object";
        }

        private bool TryGetGenericType(SyntaxNode node, out string type)
        {
            type = string.Empty;
            var baseType = node.Children.FirstOrDefault(child => child.Kind == SyntaxKind.TypeName);
            var argumentList = node.Children.FirstOrDefault(child => child.Kind == SyntaxKind.TypeArgumentList);
            if (baseType is null || argumentList is null)
            {
                return false;
            }

            var baseName = MapType(baseType);
            var arguments = argumentList.Children
                .Where(child => !child.IsToken)
                .Select(MapType)
                .ToArray();
            if (baseName.Length == 0 || arguments.Length == 0)
            {
                return false;
            }

            type = $"{baseName}<{string.Join(", ", arguments)}>";
            return true;
        }

        private string GetLiteralType(SyntaxNode literal, SyntaxNode? initializer)
        {
            var annotation = literal.Children.FirstOrDefault(child => child.Kind == SyntaxKind.TypeAnnotation);
            var typeNode = annotation?.Children.FirstOrDefault(child => !child.IsToken);
            if (typeNode is not null)
            {
                return MapType(typeNode);
            }

            return InferLiteralType(initializer);
        }

        private static string InferLiteralType(SyntaxNode? initializer)
        {
            if (initializer?.Kind != SyntaxKind.LiteralExpression)
            {
                return "object";
            }

            var token = initializer.Children.FirstOrDefault(child => child.IsToken);
            return token?.Kind switch
            {
                SyntaxKind.StringLiteralToken or SyntaxKind.InterpolatedStringLiteralToken => "string",
                SyntaxKind.TrueKeyword or SyntaxKind.FalseKeyword => "bool",
                SyntaxKind.NumericLiteralToken => InferNumericLiteralType(token.Text ?? string.Empty),
                _ => "object"
            };
        }

        private static string InferNumericLiteralType(string text)
        {
            if (text.EndsWith("m", StringComparison.OrdinalIgnoreCase))
            {
                return "decimal";
            }

            return text.Contains('.', StringComparison.Ordinal) ? "double" : "int";
        }

        private static string GetSourceTypeName(SyntaxNode? node)
        {
            if (node is null)
            {
                return "object";
            }

            if (node.Kind == SyntaxKind.TypeAnnotation)
            {
                return GetSourceTypeName(node.Children.FirstOrDefault(child => !child.IsToken));
            }

            if (node.Kind == SyntaxKind.NullableType)
            {
                return GetSourceTypeName(node.Children.FirstOrDefault(child => !child.IsToken));
            }

            if (node.Kind == SyntaxKind.ArrayType)
            {
                return $"{GetSourceTypeName(node.Children.FirstOrDefault(child => !child.IsToken))}[]";
            }

            if (node.Kind == SyntaxKind.TypeName)
            {
                return GetQualifiedName(node);
            }

            return "object";
        }

        private static bool CanEmitConstLiteral(string type, SyntaxNode? initializer)
        {
            if (initializer?.Kind != SyntaxKind.LiteralExpression)
            {
                return false;
            }

            var token = initializer.Children.FirstOrDefault(child => child.IsToken);
            if (token is null || token.Kind == SyntaxKind.InterpolatedStringLiteralToken)
            {
                return false;
            }

            if (token.Kind == SyntaxKind.NullKeyword)
            {
                return string.Equals(type, "string", StringComparison.Ordinal);
            }

            return type is "bool"
                or "byte"
                or "char"
                or "decimal"
                or "double"
                or "float"
                or "int"
                or "long"
                or "sbyte"
                or "short"
                or "string"
                or "uint"
                or "ulong"
                or "ushort";
        }

        private static SyntaxNode? GetInitializerExpression(SyntaxNode node)
        {
            return node.Children
                .FirstOrDefault(child => child.Kind == SyntaxKind.Initializer)?
                .Children
                .FirstOrDefault(child => !child.IsToken);
        }

        private static string GetVisibility(SyntaxNode node)
        {
            if (node.Children.Any(child => child.Kind == SyntaxKind.PrivateModifier))
            {
                return "private";
            }

            return node.Children.Any(child => child.Kind is SyntaxKind.ExportModifier or SyntaxKind.PublicModifier)
                ? "public"
                : "internal";
        }

        private static bool IsAsyncFunction(SyntaxNode node) =>
            node.Children.Any(child => child.Kind == SyntaxKind.AsyncModifier);

        private static string GetDeclarationName(SyntaxNode node)
        {
            var seenFunctionKeyword = false;
            foreach (var child in node.Children)
            {
                if (child.IsToken && child.Kind == SyntaxKind.FunKeyword)
                {
                    seenFunctionKeyword = true;
                    continue;
                }

                if (seenFunctionKeyword && child.IsToken && child.Kind == SyntaxKind.IdentifierToken)
                {
                    return child.Text ?? "Generated";
                }
            }

            return "Generated";
        }

        private static string GetTypeAliasDeclarationName(SyntaxNode node)
        {
            var seenTypeKeyword = false;
            foreach (var child in node.Children)
            {
                if (child.IsToken && child.Kind == SyntaxKind.TypeKeyword)
                {
                    seenTypeKeyword = true;
                    continue;
                }

                if (seenTypeKeyword && child.IsToken && child.Kind == SyntaxKind.IdentifierToken)
                {
                    return child.Text ?? string.Empty;
                }
            }

            return string.Empty;
        }

        private static string GetLiteralDeclarationName(SyntaxNode node)
        {
            var seenLiteralKeyword = false;
            foreach (var child in node.Children)
            {
                if (child.IsToken && child.Kind == SyntaxKind.LiteralKeyword)
                {
                    seenLiteralKeyword = true;
                    continue;
                }

                if (seenLiteralKeyword && child.IsToken && child.Kind == SyntaxKind.IdentifierToken)
                {
                    return child.Text ?? "Literal";
                }
            }

            return "Literal";
        }

        private static string GetModuleDeclarationName(SyntaxNode node)
        {
            var seenModuleKeyword = false;
            foreach (var child in node.Children)
            {
                if (child.IsToken && child.Kind == SyntaxKind.ModuleKeyword)
                {
                    seenModuleKeyword = true;
                    continue;
                }

                if (seenModuleKeyword && child.IsToken && child.Kind == SyntaxKind.IdentifierToken)
                {
                    return child.Text ?? "Module";
                }
            }

            return "Module";
        }

        private static string GetClassDeclarationName(SyntaxNode node)
        {
            var seenClassKeyword = false;
            foreach (var child in node.Children)
            {
                if (child.IsToken && child.Kind == SyntaxKind.ClassKeyword)
                {
                    seenClassKeyword = true;
                    continue;
                }

                if (seenClassKeyword && child.IsToken && child.Kind == SyntaxKind.IdentifierToken)
                {
                    return child.Text ?? "Generated";
                }
            }

            return "Generated";
        }

        private static string GetRecordDeclarationName(SyntaxNode node)
        {
            var seenRecordKeyword = false;
            foreach (var child in node.Children)
            {
                if (child.IsToken && child.Kind == SyntaxKind.RecordKeyword)
                {
                    seenRecordKeyword = true;
                    continue;
                }

                if (seenRecordKeyword && child.IsToken && child.Kind == SyntaxKind.IdentifierToken)
                {
                    return child.Text ?? "Generated";
                }
            }

            return "Generated";
        }

        private static string GetUnionDeclarationName(SyntaxNode node)
        {
            var seenUnionKeyword = false;
            foreach (var child in node.Children)
            {
                if (child.IsToken && child.Kind == SyntaxKind.UnionKeyword)
                {
                    seenUnionKeyword = true;
                    continue;
                }

                if (seenUnionKeyword && child.IsToken && child.Kind == SyntaxKind.IdentifierToken)
                {
                    return child.Text ?? "Generated";
                }
            }

            return "Generated";
        }

        private static string GetInterfaceDeclarationName(SyntaxNode node)
        {
            var seenInterfaceKeyword = false;
            foreach (var child in node.Children)
            {
                if (child.IsToken && child.Kind == SyntaxKind.InterfaceKeyword)
                {
                    seenInterfaceKeyword = true;
                    continue;
                }

                if (seenInterfaceKeyword && child.IsToken && child.Kind == SyntaxKind.IdentifierToken)
                {
                    return child.Text ?? "Generated";
                }
            }

            return "Generated";
        }

        private static string GetLocalDeclarationName(SyntaxNode node)
        {
            var seenLetKeyword = false;
            foreach (var child in node.Children)
            {
                if (child.IsToken && child.Kind == SyntaxKind.LetKeyword)
                {
                    seenLetKeyword = true;
                    continue;
                }

                if (seenLetKeyword && child.IsToken && child.Kind == SyntaxKind.IdentifierToken)
                {
                    return child.Text ?? "local";
                }
            }

            return "local";
        }

        private bool TryGetCallTarget(SyntaxNode callee, out string callTarget)
        {
            callTarget = string.Empty;
            if (callee.Kind != SyntaxKind.IdentifierExpression)
            {
                return false;
            }

            var identifier = GetIdentifierText(callee);
            if (!_unionCaseFactories.TryGetValue(identifier, out var target))
            {
                return false;
            }

            callTarget = target;
            return true;
        }

        private bool TryGetConstructorName(SyntaxNode callee, out string constructorName)
        {
            constructorName = string.Empty;
            if (callee.Kind != SyntaxKind.IdentifierExpression)
            {
                return false;
            }

            constructorName = GetIdentifierText(callee);
            return _constructorCandidateNames.Contains(constructorName);
        }

        private static string GetIdentifierText(SyntaxNode node)
        {
            var identifier = node.Children.FirstOrDefault(child => child.IsToken && child.Kind == SyntaxKind.IdentifierToken);
            return identifier?.Text ?? string.Empty;
        }

        private static string GetQualifiedName(SyntaxNode? node)
        {
            if (node is null)
            {
                return string.Empty;
            }

            var identifiers = node.Kind == SyntaxKind.TypeName
                ? node.Children.Where(child => child.IsToken && child.Kind == SyntaxKind.IdentifierToken)
                : node.Children
                    .Where(child => child.Kind == SyntaxKind.TypeName)
                    .SelectMany(child => child.Children)
                    .Where(child => child.IsToken && child.Kind == SyntaxKind.IdentifierToken);

            var parts = identifiers.Select(identifier => identifier.Text ?? string.Empty).Where(text => text.Length > 0);
            return string.Join(".", parts);
        }

        private static bool TryUnquoteStringLiteral(string? text, out string value)
        {
            value = string.Empty;
            if (string.IsNullOrEmpty(text) || text.Length < 2 || text[0] != '"' || text[^1] != '"')
            {
                return false;
            }

            value = text[1..^1];
            return value.Length > 0;
        }

        private static bool ContainsNode(SyntaxNode node, SyntaxKind kind)
        {
            if (node.Kind == kind)
            {
                return true;
            }

            return node.Children.Any(child => !child.IsToken && ContainsNode(child, kind));
        }

        private static IEnumerable<string> GetNamedImportIdentifiers(SyntaxNode node)
        {
            var insideBraces = false;
            foreach (var child in node.Children)
            {
                if (child.IsToken && child.Kind == SyntaxKind.OpenBraceToken)
                {
                    insideBraces = true;
                    continue;
                }

                if (child.IsToken && child.Kind == SyntaxKind.CloseBraceToken)
                {
                    yield break;
                }

                if (insideBraces && child.IsToken && child.Kind == SyntaxKind.IdentifierToken && child.Text is { Length: > 0 } text)
                {
                    yield return text;
                }
            }
        }

        private sealed record CSharpImports(
            IReadOnlyList<string> Usings,
            IReadOnlyList<string> StaticUsings,
            IReadOnlyList<string> ImportedNames);

        private readonly record struct CSharpParameter(string Type, string Name, string SourceType);

        private readonly record struct RecordShape(string Name, IReadOnlyList<CSharpParameter> Parameters);

        private readonly record struct TypeLevelUnionShape(string Name, IReadOnlyList<TypeLevelUnionMemberShape> Members);

        private readonly record struct TypeLevelUnionMemberShape(string SourceType, string CSharpType);

        private readonly record struct UnionShape(string Name, IReadOnlyList<UnionCaseShape> Cases);

        private readonly record struct UnionCaseShape(
            string Name,
            string ClassName,
            int Tag,
            IReadOnlyList<CSharpParameter> Parameters);
    }
}
