using System.Text;
using TypeSharp.Compiler.Parsing;

namespace TypeSharp.Compiler.Backend;

public static class CSharpSourceBackend
{
    public static string Emit(SyntaxNode root)
    {
        var emitter = new Emitter();
        return emitter.Emit(root);
    }

    private sealed class Emitter
    {
        private readonly StringBuilder _builder = new();
        private readonly HashSet<string> _constructorCandidateNames = new(StringComparer.Ordinal);
        private readonly Dictionary<string, RecordShape> _records = new(StringComparer.Ordinal);
        private Dictionary<string, string> _valueTypes = new(StringComparer.Ordinal);

        public string Emit(SyntaxNode root)
        {
            var namespaceName = root.Children.FirstOrDefault(child => child.Kind == SyntaxKind.NamespaceDeclaration) is { } namespaceDeclaration
                ? GetQualifiedName(namespaceDeclaration)
                : "TypeSharp.Generated";

            var imports = CollectImports(root);
            foreach (var importedName in imports.ImportedNames)
            {
                _constructorCandidateNames.Add(importedName);
            }

            _builder.AppendLine("// <auto-generated />");
            _builder.AppendLine();
            foreach (var import in imports.Usings)
            {
                _builder.AppendLine($"using {import};");
            }

            foreach (var import in imports.StaticUsings)
            {
                _builder.AppendLine($"using static {import};");
            }

            if (imports.Usings.Count > 0 || imports.StaticUsings.Count > 0)
            {
                _builder.AppendLine();
            }

            _builder.AppendLine($"namespace {namespaceName}");
            _builder.AppendLine("{");
            _builder.AppendLine("    public static class Module");
            _builder.AppendLine("    {");

            var literals = root.Children
                .Where(child => child.Kind == SyntaxKind.LiteralDeclaration)
                .ToArray();

            var functions = root.Children
                .Where(child => child.Kind == SyntaxKind.FunctionDeclaration)
                .ToArray();

            var modules = root.Children
                .Where(child => child.Kind == SyntaxKind.ModuleDeclaration)
                .ToArray();

            var records = root.Children
                .Where(child => child.Kind == SyntaxKind.RecordDeclaration)
                .ToArray();

            var classes = root.Children
                .Where(child => child.Kind == SyntaxKind.ClassDeclaration)
                .ToArray();

            var interfaces = root.Children
                .Where(child => child.Kind == SyntaxKind.InterfaceDeclaration)
                .ToArray();

            foreach (var record in records)
            {
                RegisterRecord(record);
            }

            foreach (var literal in literals)
            {
                EmitLiteralDeclaration(literal);
            }

            if (literals.Length > 0 && functions.Length > 0)
            {
                _builder.AppendLine();
            }

            for (var index = 0; index < functions.Length; index++)
            {
                if (index > 0)
                {
                    _builder.AppendLine();
                }

                EmitFunction(functions[index], isStatic: true);
            }

            _builder.AppendLine("    }");

            foreach (var module in modules)
            {
                _builder.AppendLine();
                EmitModuleDeclaration(module);
            }

            foreach (var recordDeclaration in records)
            {
                _builder.AppendLine();
                EmitRecordDeclaration(recordDeclaration);
            }

            foreach (var classDeclaration in classes)
            {
                _builder.AppendLine();
                EmitClassDeclaration(classDeclaration);
            }

            foreach (var interfaceDeclaration in interfaces)
            {
                _builder.AppendLine();
                EmitInterfaceDeclaration(interfaceDeclaration);
            }

            _builder.AppendLine("}");
            return _builder.ToString().Replace("\r\n", "\n", StringComparison.Ordinal);
        }

        private void RegisterRecord(SyntaxNode node)
        {
            var name = GetRecordDeclarationName(node);
            if (name.Length == 0)
            {
                return;
            }

            var parameters = GetParameters(node);
            _records[name] = new RecordShape(name, parameters);
            _constructorCandidateNames.Add(name);
        }

        private static CSharpImports CollectImports(SyntaxNode root)
        {
            var usings = new List<string>();
            var staticUsings = new List<string>();
            var importedNames = new List<string>();
            var seenUsings = new HashSet<string>(StringComparer.Ordinal);
            var seenStaticUsings = new HashSet<string>(StringComparer.Ordinal);
            var seenImportedNames = new HashSet<string>(StringComparer.Ordinal);

            foreach (var child in root.Children)
            {
                if (child.Kind is SyntaxKind.ImportNamedDeclaration or SyntaxKind.ImportTypeDeclaration)
                {
                    foreach (var importedName in GetNamedImportIdentifiers(child))
                    {
                        if (seenImportedNames.Add(importedName))
                        {
                            importedNames.Add(importedName);
                        }
                    }

                    var moduleSpecifier = child.Children.FirstOrDefault(grandchild => grandchild.IsToken && grandchild.Kind == SyntaxKind.StringLiteralToken);
                    if (TryUnquoteStringLiteral(moduleSpecifier?.Text, out var namespaceName) && seenUsings.Add(namespaceName))
                    {
                        usings.Add(namespaceName);
                    }

                    continue;
                }

                if (child.Kind == SyntaxKind.ImportStaticDeclaration)
                {
                    var typeName = child.Children.FirstOrDefault(grandchild => grandchild.Kind == SyntaxKind.TypeName);
                    var qualifiedName = GetQualifiedName(typeName);
                    if (qualifiedName.Length > 0 && seenStaticUsings.Add(qualifiedName))
                    {
                        staticUsings.Add(qualifiedName);
                    }
                }
            }

            return new CSharpImports(usings, staticUsings, importedNames);
        }

        private void EmitModuleDeclaration(SyntaxNode node)
        {
            var visibility = GetVisibility(node);
            var name = GetModuleDeclarationName(node);

            _builder.AppendLine($"    {visibility} static class {name}");
            _builder.AppendLine("    {");

            var literals = node.Children
                .Where(child => child.Kind == SyntaxKind.LiteralDeclaration)
                .ToArray();

            var functions = node.Children
                .Where(child => child.Kind == SyntaxKind.FunctionDeclaration)
                .ToArray();

            foreach (var literal in literals)
            {
                EmitLiteralDeclaration(literal);
            }

            if (literals.Length > 0 && functions.Length > 0)
            {
                _builder.AppendLine();
            }

            for (var index = 0; index < functions.Length; index++)
            {
                if (index > 0)
                {
                    _builder.AppendLine();
                }

                EmitFunction(functions[index], isStatic: true);
            }

            _builder.AppendLine("    }");
        }

        private void EmitRecordDeclaration(SyntaxNode node)
        {
            var visibility = GetVisibility(node);
            var name = GetRecordDeclarationName(node);
            var typeParameters = GetTypeParameterList(node);
            var parameters = GetParameters(node);

            _builder.AppendLine($"    {visibility} sealed class {name}{typeParameters}");
            _builder.AppendLine("    {");

            if (parameters.Count > 0)
            {
                _builder.AppendLine($"        public {name}({FormatParameters(parameters)})");
                _builder.AppendLine("        {");
                foreach (var parameter in parameters)
                {
                    _builder.AppendLine($"            this.{parameter.Name} = {parameter.Name};");
                }

                _builder.AppendLine("        }");
                _builder.AppendLine();
            }

            foreach (var parameter in parameters)
            {
                _builder.AppendLine($"        public {parameter.Type} {parameter.Name} {{ get; }}");
            }

            if (parameters.Count > 0)
            {
                _builder.AppendLine();
            }

            EmitRecordEquals(name, parameters);
            _builder.AppendLine();
            EmitRecordGetHashCode(parameters);

            _builder.AppendLine("    }");
        }

        private void EmitClassDeclaration(SyntaxNode node)
        {
            var visibility = GetVisibility(node);
            var name = GetClassDeclarationName(node);
            var typeParameters = GetTypeParameterList(node);

            _builder.AppendLine($"    {visibility} class {name}{typeParameters}");
            _builder.AppendLine("    {");

            var functions = node.Children
                .Where(child => child.Kind == SyntaxKind.FunctionDeclaration)
                .ToArray();

            for (var index = 0; index < functions.Length; index++)
            {
                if (index > 0)
                {
                    _builder.AppendLine();
                }

                EmitFunction(functions[index], isStatic: false);
            }

            _builder.AppendLine("    }");
        }

        private void EmitInterfaceDeclaration(SyntaxNode node)
        {
            var visibility = GetVisibility(node);
            var name = GetInterfaceDeclarationName(node);
            var typeParameters = GetTypeParameterList(node);

            _builder.AppendLine($"    {visibility} interface {name}{typeParameters}");
            _builder.AppendLine("    {");

            var functions = node.Children
                .Where(child => child.Kind == SyntaxKind.FunctionDeclaration)
                .ToArray();

            for (var index = 0; index < functions.Length; index++)
            {
                if (index > 0)
                {
                    _builder.AppendLine();
                }

                EmitInterfaceFunction(functions[index]);
            }

            _builder.AppendLine("    }");
        }

        private void EmitLiteralDeclaration(SyntaxNode node)
        {
            var visibility = GetVisibility(node);
            var name = GetLiteralDeclarationName(node);
            var initializer = GetInitializerExpression(node);
            var type = GetLiteralType(node, initializer);
            var storage = CanEmitConstLiteral(type, initializer) ? "const" : "static readonly";

            _builder.AppendLine($"        {visibility} {storage} {type} {name} = {EmitExpression(initializer)};");
        }

        private void EmitFunction(SyntaxNode node, bool isStatic)
        {
            var visibility = GetVisibility(node);
            var staticModifier = isStatic ? " static" : string.Empty;
            var name = GetDeclarationName(node);
            var typeParameters = GetTypeParameterList(node);
            var parameters = GetParameters(node);
            var returnType = GetReturnType(node);
            var body = node.Children.FirstOrDefault(child => child.Kind == SyntaxKind.FunctionBody);
            var expression = body?.Children.LastOrDefault(child => !child.IsToken);

            var previousValueTypes = _valueTypes;
            _valueTypes = new Dictionary<string, string>(previousValueTypes, StringComparer.Ordinal);
            foreach (var parameter in parameters)
            {
                _valueTypes[parameter.Name] = parameter.Type;
            }

            try
            {
                _builder.AppendLine($"        {visibility}{staticModifier} {returnType} {name}{typeParameters}({FormatParameters(parameters)})");
                _builder.AppendLine("        {");
                if (expression?.Kind == SyntaxKind.BlockExpression)
                {
                    EmitBlock(expression);
                }
                else
                {
                    _builder.AppendLine($"            return {EmitExpression(expression)};");
                }

                _builder.AppendLine("        }");
            }
            finally
            {
                _valueTypes = previousValueTypes;
            }
        }

        private void EmitRecordEquals(string name, IReadOnlyList<CSharpParameter> parameters)
        {
            _builder.AppendLine("        public override bool Equals(object obj)");
            _builder.AppendLine("        {");
            _builder.AppendLine($"            var other = obj as {name};");
            var comparisons = parameters.Count == 0
                ? "true"
                : string.Join(" && ", parameters.Select(parameter => $"object.Equals({parameter.Name}, other.{parameter.Name})"));
            _builder.AppendLine($"            return other != null && {comparisons};");
            _builder.AppendLine("        }");
        }

        private void EmitRecordGetHashCode(IReadOnlyList<CSharpParameter> parameters)
        {
            _builder.AppendLine("        public override int GetHashCode()");
            _builder.AppendLine("        {");
            _builder.AppendLine("            unchecked");
            _builder.AppendLine("            {");
            _builder.AppendLine("                var hash = 17;");
            foreach (var parameter in parameters)
            {
                _builder.AppendLine($"                hash = (hash * 397) ^ (object.Equals({parameter.Name}, null) ? 0 : {parameter.Name}.GetHashCode());");
            }

            _builder.AppendLine("                return hash;");
            _builder.AppendLine("            }");
            _builder.AppendLine("        }");
        }

        private void EmitInterfaceFunction(SyntaxNode node)
        {
            var name = GetDeclarationName(node);
            var typeParameters = GetTypeParameterList(node);
            var parameters = GetParameterList(node);
            var returnType = GetReturnType(node);

            _builder.AppendLine($"        {returnType} {name}{typeParameters}({parameters});");
        }

        private static string GetParameterList(SyntaxNode function)
        {
            var parameterList = function.Children.FirstOrDefault(child => child.Kind == SyntaxKind.ParameterList);
            if (parameterList is null)
            {
                return string.Empty;
            }

            var parameters = parameterList.Children
                .Where(child => child.Kind == SyntaxKind.Parameter)
                .Select(EmitParameter);
            return string.Join(", ", parameters);
        }

        private static IReadOnlyList<CSharpParameter> GetParameters(SyntaxNode declaration)
        {
            var parameterList = declaration.Children.FirstOrDefault(child => child.Kind == SyntaxKind.ParameterList);
            if (parameterList is null)
            {
                return [];
            }

            return parameterList.Children
                .Where(child => child.Kind == SyntaxKind.Parameter)
                .Select(GetParameter)
                .ToArray();
        }

        private static string FormatParameters(IReadOnlyList<CSharpParameter> parameters) =>
            string.Join(", ", parameters.Select(parameter => $"{parameter.Type} {parameter.Name}"));

        private static string GetTypeParameterList(SyntaxNode declaration)
        {
            var typeParameterList = declaration.Children.FirstOrDefault(child => child.Kind == SyntaxKind.TypeParameterList);
            if (typeParameterList is null)
            {
                return string.Empty;
            }

            var parameters = typeParameterList.Children
                .Where(child => child.IsToken && child.Kind == SyntaxKind.IdentifierToken)
                .Select(child => child.Text ?? string.Empty)
                .Where(text => text.Length > 0)
                .ToArray();

            return parameters.Length == 0 ? string.Empty : $"<{string.Join(", ", parameters)}>";
        }

        private static string EmitParameter(SyntaxNode parameter)
        {
            var parameterInfo = GetParameter(parameter);
            return $"{parameterInfo.Type} {parameterInfo.Name}";
        }

        private static CSharpParameter GetParameter(SyntaxNode parameter)
        {
            var name = parameter.Children.FirstOrDefault(child => child.IsToken && child.Kind == SyntaxKind.IdentifierToken)?.Text;
            var annotation = parameter.Children.FirstOrDefault(child => child.Kind == SyntaxKind.TypeAnnotation);
            var typeNode = annotation?.Children.FirstOrDefault(child => !child.IsToken);
            return new CSharpParameter(MapType(typeNode), !string.IsNullOrWhiteSpace(name) ? name : "_");
        }

        private void EmitBlock(SyntaxNode node)
        {
            var statements = node.Children.Where(child => !child.IsToken).ToArray();
            for (var index = 0; index < statements.Length; index++)
            {
                var statement = statements[index];
                var isLast = index == statements.Length - 1;

                if (statement.Kind == SyntaxKind.ValueDeclaration)
                {
                    EmitLocalDeclaration(statement);
                    continue;
                }

                var expression = statement.Kind == SyntaxKind.ExpressionStatement
                    ? statement.Children.FirstOrDefault(child => !child.IsToken)
                    : statement;

                if (isLast)
                {
                    _builder.AppendLine($"            return {EmitExpression(expression)};");
                }
                else
                {
                    _builder.AppendLine($"            {EmitExpression(expression)};");
                }
            }
        }

        private void EmitLocalDeclaration(SyntaxNode node)
        {
            var name = GetLocalDeclarationName(node);
            var initializer = node.Children
                .FirstOrDefault(child => child.Kind == SyntaxKind.Initializer)?
                .Children
                .FirstOrDefault(child => !child.IsToken);

            _builder.AppendLine($"            var {name} = {EmitExpression(initializer)};");
        }

        private string EmitExpression(SyntaxNode? node)
        {
            if (node is null)
            {
                return "default(object)";
            }

            return node.Kind switch
            {
                SyntaxKind.LiteralExpression => EmitLiteral(node),
                SyntaxKind.IdentifierExpression => EmitIdentifier(node),
                SyntaxKind.MemberAccessExpression => EmitMemberAccess(node),
                SyntaxKind.CallExpression => EmitCall(node),
                SyntaxKind.NamedArgument => EmitNamedArgument(node),
                SyntaxKind.OutArgument => EmitOutArgument(node),
                SyntaxKind.InArgument => EmitInArgument(node),
                SyntaxKind.RefArgument => EmitRefArgument(node),
                SyntaxKind.LambdaExpression => EmitLambda(node),
                SyntaxKind.AssignmentExpression => EmitAssignment(node),
                SyntaxKind.RecordUpdateExpression => EmitRecordUpdate(node),
                _ => "default(object)"
            };
        }

        private static string EmitIdentifier(SyntaxNode node)
        {
            var identifier = node.Children.FirstOrDefault(child => child.IsToken && child.Kind == SyntaxKind.IdentifierToken);
            return identifier?.Text ?? "default";
        }

        private string EmitMemberAccess(SyntaxNode node)
        {
            var receiver = node.Children.FirstOrDefault(child => !child.IsToken);
            var member = node.Children.LastOrDefault(child => child.IsToken && child.Kind == SyntaxKind.IdentifierToken);
            if (receiver is null || member?.Text is null)
            {
                return "default(object)";
            }

            return $"{EmitExpression(receiver)}.{member.Text}";
        }

        private string EmitCall(SyntaxNode node)
        {
            var callee = node.Children.FirstOrDefault(child => !child.IsToken);
            if (callee is null)
            {
                return "default(object)";
            }

            var arguments = node.Children
                .SkipWhile(child => !ReferenceEquals(child, callee))
                .Skip(1)
                .Where(child => !child.IsToken)
                .Select(EmitExpression);

            var argumentList = string.Join(", ", arguments);
            if (TryGetConstructorName(callee, out var constructorName))
            {
                return $"new {constructorName}({argumentList})";
            }

            return $"{EmitExpression(callee)}({argumentList})";
        }

        private string EmitOutArgument(SyntaxNode node)
        {
            var expression = node.Children.FirstOrDefault(child => !child.IsToken);
            return $"out {EmitExpression(expression)}";
        }

        private string EmitNamedArgument(SyntaxNode node)
        {
            var name = node.Children.FirstOrDefault(child => child.IsToken && child.Kind == SyntaxKind.IdentifierToken)?.Text ?? string.Empty;
            var expression = node.Children.LastOrDefault(child => !child.IsToken);
            return name.Length == 0
                ? EmitExpression(expression)
                : $"{name}: {EmitExpression(expression)}";
        }

        private string EmitInArgument(SyntaxNode node)
        {
            var expression = node.Children.FirstOrDefault(child => !child.IsToken);
            return $"in {EmitExpression(expression)}";
        }

        private string EmitRefArgument(SyntaxNode node)
        {
            var expression = node.Children.FirstOrDefault(child => !child.IsToken);
            return $"ref {EmitExpression(expression)}";
        }

        private string EmitLambda(SyntaxNode node)
        {
            var parameter = node.Children.FirstOrDefault(child => child.IsToken && child.Kind == SyntaxKind.IdentifierToken)?.Text ?? "_";
            var body = node.Children.LastOrDefault(child => !child.IsToken);
            return $"{parameter} => {EmitExpression(body)}";
        }

        private string EmitAssignment(SyntaxNode node)
        {
            var expressions = node.Children.Where(child => !child.IsToken).ToArray();
            var operatorToken = node.Children.FirstOrDefault(child => child.IsToken);
            if (expressions.Length < 2 || operatorToken?.Text is null)
            {
                return "default(object)";
            }

            return $"{EmitExpression(expressions[0])} {operatorToken.Text} {EmitExpression(expressions[1])}";
        }

        private string EmitRecordUpdate(SyntaxNode node)
        {
            var receiver = node.Children.FirstOrDefault(child => !child.IsToken);
            var update = node.Children.LastOrDefault(child => child.Kind == SyntaxKind.RecordExpression);
            if (receiver is null || update is null || !TryGetRecordShape(receiver, out var record))
            {
                return "default(object)";
            }

            var receiverExpression = EmitExpression(receiver);
            var updatedFields = GetRecordFieldExpressions(update);
            var arguments = record.Parameters
                .Select(parameter => updatedFields.TryGetValue(parameter.Name, out var updatedValue)
                    ? updatedValue
                    : $"{receiverExpression}.{parameter.Name}");

            return $"new {record.Name}({string.Join(", ", arguments)})";
        }

        private Dictionary<string, string> GetRecordFieldExpressions(SyntaxNode recordExpression)
        {
            var fields = new Dictionary<string, string>(StringComparer.Ordinal);
            foreach (var field in recordExpression.Children.Where(child => child.Kind == SyntaxKind.RecordField))
            {
                var name = field.Children.FirstOrDefault(child => child.IsToken && child.Kind == SyntaxKind.IdentifierToken)?.Text ?? string.Empty;
                if (name.Length == 0)
                {
                    continue;
                }

                var expression = field.Children.LastOrDefault(child => !child.IsToken);
                fields[name] = expression is null ? name : EmitExpression(expression);
            }

            return fields;
        }

        private bool TryGetRecordShape(SyntaxNode receiver, out RecordShape record)
        {
            record = default;
            if (!TryGetExpressionType(receiver, out var typeName))
            {
                return false;
            }

            return _records.TryGetValue(typeName, out record);
        }

        private bool TryGetExpressionType(SyntaxNode node, out string typeName)
        {
            typeName = string.Empty;
            if (node.Kind != SyntaxKind.IdentifierExpression)
            {
                return false;
            }

            var name = node.Children.FirstOrDefault(child => child.IsToken && child.Kind == SyntaxKind.IdentifierToken)?.Text ?? string.Empty;
            if (name.Length == 0)
            {
                return false;
            }

            if (!_valueTypes.TryGetValue(name, out var knownType) || knownType.Length == 0)
            {
                return false;
            }

            typeName = knownType;
            return true;
        }

        private static string EmitLiteral(SyntaxNode node)
        {
            var token = node.Children.FirstOrDefault(child => child.IsToken);
            return token?.Kind switch
            {
                SyntaxKind.StringLiteralToken => token.Text ?? "\"\"",
                SyntaxKind.InterpolatedStringLiteralToken => token.Text ?? "\"\"",
                SyntaxKind.NumericLiteralToken => token.Text ?? "0",
                SyntaxKind.TrueKeyword => "true",
                SyntaxKind.FalseKeyword => "false",
                SyntaxKind.NullKeyword => "null",
                _ => "default(object)"
            };
        }

        private static string GetReturnType(SyntaxNode function)
        {
            var annotation = function.Children.FirstOrDefault(child => child.Kind == SyntaxKind.TypeAnnotation);
            var typeNode = annotation?.Children.FirstOrDefault(child => !child.IsToken);
            return MapType(typeNode);
        }

        private static string MapType(SyntaxNode? node)
        {
            if (node is null)
            {
                return "object";
            }

            if (node.Kind == SyntaxKind.TypeName)
            {
                if (TryGetGenericType(node, out var genericType))
                {
                    return genericType;
                }

                var name = GetQualifiedName(node);
                return name switch
                {
                    "bool" => "bool",
                    "byte" => "byte",
                    "char" => "char",
                    "decimal" => "decimal",
                    "double" => "double",
                    "float" => "float",
                    "int" => "int",
                    "long" => "long",
                    "object" => "object",
                    "sbyte" => "sbyte",
                    "short" => "short",
                    "string" => "string",
                    "uint" => "uint",
                    "ulong" => "ulong",
                    "ushort" => "ushort",
                    "void" or "unit" => "void",
                    _ => name
                };
            }

            if (node.Kind == SyntaxKind.ArrayType)
            {
                var elementType = node.Children.FirstOrDefault(child => !child.IsToken);
                return $"{MapType(elementType)}[]";
            }

            return "object";
        }

        private static bool TryGetGenericType(SyntaxNode node, out string type)
        {
            type = string.Empty;
            var baseType = node.Children.FirstOrDefault(child => child.Kind == SyntaxKind.TypeName);
            var argumentList = node.Children.FirstOrDefault(child => child.Kind == SyntaxKind.TypeArgumentList);
            if (baseType is null || argumentList is null)
            {
                return false;
            }

            var baseName = MapType(baseType);
            var arguments = argumentList.Children
                .Where(child => !child.IsToken)
                .Select(MapType)
                .ToArray();
            if (baseName.Length == 0 || arguments.Length == 0)
            {
                return false;
            }

            type = $"{baseName}<{string.Join(", ", arguments)}>";
            return true;
        }

        private static string GetLiteralType(SyntaxNode literal, SyntaxNode? initializer)
        {
            var annotation = literal.Children.FirstOrDefault(child => child.Kind == SyntaxKind.TypeAnnotation);
            var typeNode = annotation?.Children.FirstOrDefault(child => !child.IsToken);
            if (typeNode is not null)
            {
                return MapType(typeNode);
            }

            return InferLiteralType(initializer);
        }

        private static string InferLiteralType(SyntaxNode? initializer)
        {
            if (initializer?.Kind != SyntaxKind.LiteralExpression)
            {
                return "object";
            }

            var token = initializer.Children.FirstOrDefault(child => child.IsToken);
            return token?.Kind switch
            {
                SyntaxKind.StringLiteralToken or SyntaxKind.InterpolatedStringLiteralToken => "string",
                SyntaxKind.TrueKeyword or SyntaxKind.FalseKeyword => "bool",
                SyntaxKind.NumericLiteralToken => InferNumericLiteralType(token.Text ?? string.Empty),
                _ => "object"
            };
        }

        private static string InferNumericLiteralType(string text)
        {
            if (text.EndsWith("m", StringComparison.OrdinalIgnoreCase))
            {
                return "decimal";
            }

            return text.Contains('.', StringComparison.Ordinal) ? "double" : "int";
        }

        private static bool CanEmitConstLiteral(string type, SyntaxNode? initializer)
        {
            if (initializer?.Kind != SyntaxKind.LiteralExpression)
            {
                return false;
            }

            var token = initializer.Children.FirstOrDefault(child => child.IsToken);
            if (token is null || token.Kind == SyntaxKind.InterpolatedStringLiteralToken)
            {
                return false;
            }

            if (token.Kind == SyntaxKind.NullKeyword)
            {
                return string.Equals(type, "string", StringComparison.Ordinal);
            }

            return type is "bool"
                or "byte"
                or "char"
                or "decimal"
                or "double"
                or "float"
                or "int"
                or "long"
                or "sbyte"
                or "short"
                or "string"
                or "uint"
                or "ulong"
                or "ushort";
        }

        private static SyntaxNode? GetInitializerExpression(SyntaxNode node)
        {
            return node.Children
                .FirstOrDefault(child => child.Kind == SyntaxKind.Initializer)?
                .Children
                .FirstOrDefault(child => !child.IsToken);
        }

        private static string GetVisibility(SyntaxNode node)
        {
            if (node.Children.Any(child => child.Kind == SyntaxKind.PrivateModifier))
            {
                return "private";
            }

            return node.Children.Any(child => child.Kind is SyntaxKind.ExportModifier or SyntaxKind.PublicModifier)
                ? "public"
                : "internal";
        }

        private static string GetDeclarationName(SyntaxNode node)
        {
            var seenFunctionKeyword = false;
            foreach (var child in node.Children)
            {
                if (child.IsToken && child.Kind == SyntaxKind.FunKeyword)
                {
                    seenFunctionKeyword = true;
                    continue;
                }

                if (seenFunctionKeyword && child.IsToken && child.Kind == SyntaxKind.IdentifierToken)
                {
                    return child.Text ?? "Generated";
                }
            }

            return "Generated";
        }

        private static string GetLiteralDeclarationName(SyntaxNode node)
        {
            var seenLiteralKeyword = false;
            foreach (var child in node.Children)
            {
                if (child.IsToken && child.Kind == SyntaxKind.LiteralKeyword)
                {
                    seenLiteralKeyword = true;
                    continue;
                }

                if (seenLiteralKeyword && child.IsToken && child.Kind == SyntaxKind.IdentifierToken)
                {
                    return child.Text ?? "Literal";
                }
            }

            return "Literal";
        }

        private static string GetModuleDeclarationName(SyntaxNode node)
        {
            var seenModuleKeyword = false;
            foreach (var child in node.Children)
            {
                if (child.IsToken && child.Kind == SyntaxKind.ModuleKeyword)
                {
                    seenModuleKeyword = true;
                    continue;
                }

                if (seenModuleKeyword && child.IsToken && child.Kind == SyntaxKind.IdentifierToken)
                {
                    return child.Text ?? "Module";
                }
            }

            return "Module";
        }

        private static string GetClassDeclarationName(SyntaxNode node)
        {
            var seenClassKeyword = false;
            foreach (var child in node.Children)
            {
                if (child.IsToken && child.Kind == SyntaxKind.ClassKeyword)
                {
                    seenClassKeyword = true;
                    continue;
                }

                if (seenClassKeyword && child.IsToken && child.Kind == SyntaxKind.IdentifierToken)
                {
                    return child.Text ?? "Generated";
                }
            }

            return "Generated";
        }

        private static string GetRecordDeclarationName(SyntaxNode node)
        {
            var seenRecordKeyword = false;
            foreach (var child in node.Children)
            {
                if (child.IsToken && child.Kind == SyntaxKind.RecordKeyword)
                {
                    seenRecordKeyword = true;
                    continue;
                }

                if (seenRecordKeyword && child.IsToken && child.Kind == SyntaxKind.IdentifierToken)
                {
                    return child.Text ?? "Generated";
                }
            }

            return "Generated";
        }

        private static string GetInterfaceDeclarationName(SyntaxNode node)
        {
            var seenInterfaceKeyword = false;
            foreach (var child in node.Children)
            {
                if (child.IsToken && child.Kind == SyntaxKind.InterfaceKeyword)
                {
                    seenInterfaceKeyword = true;
                    continue;
                }

                if (seenInterfaceKeyword && child.IsToken && child.Kind == SyntaxKind.IdentifierToken)
                {
                    return child.Text ?? "Generated";
                }
            }

            return "Generated";
        }

        private static string GetLocalDeclarationName(SyntaxNode node)
        {
            var seenLetKeyword = false;
            foreach (var child in node.Children)
            {
                if (child.IsToken && child.Kind == SyntaxKind.LetKeyword)
                {
                    seenLetKeyword = true;
                    continue;
                }

                if (seenLetKeyword && child.IsToken && child.Kind == SyntaxKind.IdentifierToken)
                {
                    return child.Text ?? "local";
                }
            }

            return "local";
        }

        private bool TryGetConstructorName(SyntaxNode callee, out string constructorName)
        {
            constructorName = string.Empty;
            if (callee.Kind != SyntaxKind.IdentifierExpression)
            {
                return false;
            }

            constructorName = EmitIdentifier(callee);
            return _constructorCandidateNames.Contains(constructorName);
        }

        private static string GetQualifiedName(SyntaxNode? node)
        {
            if (node is null)
            {
                return string.Empty;
            }

            var identifiers = node.Kind == SyntaxKind.TypeName
                ? node.Children.Where(child => child.IsToken && child.Kind == SyntaxKind.IdentifierToken)
                : node.Children
                    .Where(child => child.Kind == SyntaxKind.TypeName)
                    .SelectMany(child => child.Children)
                    .Where(child => child.IsToken && child.Kind == SyntaxKind.IdentifierToken);

            var parts = identifiers.Select(identifier => identifier.Text ?? string.Empty).Where(text => text.Length > 0);
            return string.Join(".", parts);
        }

        private static bool TryUnquoteStringLiteral(string? text, out string value)
        {
            value = string.Empty;
            if (string.IsNullOrEmpty(text) || text.Length < 2 || text[0] != '"' || text[^1] != '"')
            {
                return false;
            }

            value = text[1..^1];
            return value.Length > 0;
        }

        private static IEnumerable<string> GetNamedImportIdentifiers(SyntaxNode node)
        {
            var insideBraces = false;
            foreach (var child in node.Children)
            {
                if (child.IsToken && child.Kind == SyntaxKind.OpenBraceToken)
                {
                    insideBraces = true;
                    continue;
                }

                if (child.IsToken && child.Kind == SyntaxKind.CloseBraceToken)
                {
                    yield break;
                }

                if (insideBraces && child.IsToken && child.Kind == SyntaxKind.IdentifierToken && child.Text is { Length: > 0 } text)
                {
                    yield return text;
                }
            }
        }

        private sealed record CSharpImports(
            IReadOnlyList<string> Usings,
            IReadOnlyList<string> StaticUsings,
            IReadOnlyList<string> ImportedNames);

        private readonly record struct CSharpParameter(string Type, string Name);

        private readonly record struct RecordShape(string Name, IReadOnlyList<CSharpParameter> Parameters);
    }
}
