// <auto-generated />

namespace Samples.GenericTypes
{
    public static class Module
    {
    }

    public class Box<T>
    {
        public T Keep(T value)
        {
            return value;
        }
    }
}
