// <auto-generated />

using TypeSharp.Runtime;

namespace Samples.LiteralMatches
{
    public static class Module
    {
        internal static string describeModeInternal(object mode)
        {
            return new System.Func<string>(delegate()
            {
                var __match0 = mode;
                if (object.Equals(__match0, "on"))
                {
                    return "On";
                }

                if (object.Equals(__match0, "off"))
                {
                    return "Off";
                }

                throw TypeSharpPattern.NoMatch(__match0);
            })();
        }

        public static string describeOn()
        {
            return describeModeInternal("on");
        }

        public static string describeFlag(bool flag)
        {
            return new System.Func<string>(delegate()
            {
                var __match1 = flag;
                if (object.Equals(__match1, true))
                {
                    return "Yes";
                }

                if (object.Equals(__match1, false))
                {
                    return "No";
                }

                throw TypeSharpPattern.NoMatch(__match1);
            })();
        }
    }
}
