using System.Collections.Generic;

internal static partial class TypeSharpCompilerTestCases
{
    public static IReadOnlyList<TypeSharpCompilerTestCase> All { get; } = new TypeSharpCompilerTestCase[]
    {
        new TypeSharpCompilerTestCase("version defaults match the documented CLI contract", VersionDefaultsMatchCliContract),
        new TypeSharpCompilerTestCase("test runner shard selection is stable", TestRunnerShardSelectionIsStable),
        new TypeSharpCompilerTestCase("diagnostic descriptor registry is stable", DiagnosticDescriptorRegistryIsStable),
        new TypeSharpCompilerTestCase("diagnostic text follows CLI text shape", DiagnosticTextUsesCliShape),
        new TypeSharpCompilerTestCase("CLI new creates console project", CliNewCreatesConsoleProject),
        new TypeSharpCompilerTestCase("CLI new creates library project", CliNewCreatesLibraryProject),
        new TypeSharpCompilerTestCase("CLI new rejects non-empty output directory", CliNewRejectsNonEmptyOutputDirectory),
        new TypeSharpCompilerTestCase("CLI accepts common no-color option", CliAcceptsCommonNoColorOption),
        new TypeSharpCompilerTestCase("CLI accepts preview project option", CliAcceptsPreviewProjectOption),
        new TypeSharpCompilerTestCase("CLI rejects unknown project option", CliRejectsUnknownProjectOption),
        new TypeSharpCompilerTestCase("CLI rejects invalid diagnostic format", CliRejectsInvalidDiagnosticFormat),
        new TypeSharpCompilerTestCase("CLI rejects invalid configuration", CliRejectsInvalidConfiguration),
        new TypeSharpCompilerTestCase("CLI rejects invalid target framework", CliRejectsInvalidTargetFramework),
        new TypeSharpCompilerTestCase("CLI rejects invalid verbosity", CliRejectsInvalidVerbosity),
        new TypeSharpCompilerTestCase("CLI explain prints diagnostic descriptor metadata", CliExplainPrintsDiagnosticDescriptorMetadata),
        new TypeSharpCompilerTestCase("CLI explain emits JSON descriptor metadata", CliExplainEmitsJsonDescriptorMetadata),
        new TypeSharpCompilerTestCase("CLI explain rejects unknown diagnostic code", CliExplainRejectsUnknownDiagnosticCode),
        new TypeSharpCompilerTestCase("CLI format check succeeds on formatted project", CliFormatCheckSucceedsOnFormattedProject),
        new TypeSharpCompilerTestCase("CLI format checks and writes normalized source", CliFormatChecksAndWritesNormalizedSource),
        new TypeSharpCompilerTestCase("CLI format reports parse diagnostics without rewriting", CliFormatReportsParseDiagnosticsWithoutRewriting),
        new TypeSharpCompilerTestCase("parse result exposes error state", ParseResultExposesErrorState),
        new TypeSharpCompilerTestCase("parser fixture convention paths are stable", ParserFixtureConventionPathsAreStable),
        new TypeSharpCompilerTestCase("binder fixture convention paths are stable", BinderFixtureConventionPathsAreStable),
        new TypeSharpCompilerTestCase("type checker fixture convention paths are stable", TypeCheckerFixtureConventionPathsAreStable),
        new TypeSharpCompilerTestCase("C# backend fixture convention paths are stable", CSharpBackendFixtureConventionPathsAreStable),
        new TypeSharpCompilerTestCase("fixture scenario README coverage is stable", FixtureScenarioReadmeCoverageIsStable),
        new TypeSharpCompilerTestCase("diagnostic fixture polarity is stable", DiagnosticFixturePolarityIsStable),
        new TypeSharpCompilerTestCase("backend abstraction exposes C# source backend", BackendAbstractionExposesCSharpSourceBackend),
        new TypeSharpCompilerTestCase("backend artifact contract supports direct assembly output", BackendArtifactContractSupportsDirectAssemblyOutput),
        new TypeSharpCompilerTestCase("lowering pipeline injects runtime helper imports", LoweringPipelineInjectsRuntimeHelperImports),
        new TypeSharpCompilerTestCase("manifest loader reads explicit manifest path", ManifestLoaderReadsExplicitManifestPath),
        new TypeSharpCompilerTestCase("manifest loader reads source aliases", ManifestLoaderReadsSourceAliases),
        new TypeSharpCompilerTestCase("manifest loader reads project references", ManifestLoaderReadsProjectReferences),
        new TypeSharpCompilerTestCase("manifest locator searches parent directories", ManifestLocatorSearchesParentDirectories),
        new TypeSharpCompilerTestCase("source discovery defaults to src root", SourceDiscoveryDefaultsToSrcRoot),
        new TypeSharpCompilerTestCase("source discovery excludes build and generated folders", SourceDiscoveryExcludesBuildAndGeneratedFolders),
        new TypeSharpCompilerTestCase("source discovery reports duplicate module paths", SourceDiscoveryReportsDuplicateModulePaths),
        new TypeSharpCompilerTestCase("source module graph collects relative import dependencies", SourceModuleGraphCollectsRelativeImportDependencies),
        new TypeSharpCompilerTestCase("source module graph collects alias import dependencies", SourceModuleGraphCollectsAliasImportDependencies),
        new TypeSharpCompilerTestCase("source module graph prefers longest alias prefix", SourceModuleGraphPrefersLongestAliasPrefix),
        new TypeSharpCompilerTestCase("source module graph reports invalid source alias target", SourceModuleGraphReportsInvalidSourceAliasTarget),
        new TypeSharpCompilerTestCase("source module graph reports invalid source alias wildcard", SourceModuleGraphReportsInvalidSourceAliasWildcard),
        new TypeSharpCompilerTestCase("source module graph collects relative import alias dependencies", SourceModuleGraphCollectsRelativeImportAliasDependencies),
        new TypeSharpCompilerTestCase("source module graph collects relative value import alias dependencies", SourceModuleGraphCollectsRelativeValueImportAliasDependencies),
        new TypeSharpCompilerTestCase("source module graph collects relative type import alias dependencies", SourceModuleGraphCollectsRelativeTypeImportAliasDependencies),
        new TypeSharpCompilerTestCase("source module graph collects relative named type import alias dependencies", SourceModuleGraphCollectsRelativeNamedTypeImportAliasDependencies),
        new TypeSharpCompilerTestCase("source module graph collects relative module import alias dependencies", SourceModuleGraphCollectsRelativeModuleImportAliasDependencies),
        new TypeSharpCompilerTestCase("source module graph collects local export alias surface", SourceModuleGraphCollectsLocalExportAliasSurface),
        new TypeSharpCompilerTestCase("source module graph collects local literal export alias surface", SourceModuleGraphCollectsLocalLiteralExportAliasSurface),
        new TypeSharpCompilerTestCase("source module graph collects local value export alias surface", SourceModuleGraphCollectsLocalValueExportAliasSurface),
        new TypeSharpCompilerTestCase("source module graph collects function value export surface", SourceModuleGraphCollectsFunctionValueExportSurface),
        new TypeSharpCompilerTestCase("source module graph collects inferred function value export surface", SourceModuleGraphCollectsInferredFunctionValueExportSurface),
        new TypeSharpCompilerTestCase("source module graph collects local type export alias surface", SourceModuleGraphCollectsLocalTypeExportAliasSurface),
        new TypeSharpCompilerTestCase("source module graph collects relative re-export surface", SourceModuleGraphCollectsRelativeReExportSurface),
        new TypeSharpCompilerTestCase("source module graph collects relative re-export alias surface", SourceModuleGraphCollectsRelativeReExportAliasSurface),
        new TypeSharpCompilerTestCase("source module graph collects relative module re-export alias surface", SourceModuleGraphCollectsRelativeModuleReExportAliasSurface),
        new TypeSharpCompilerTestCase("source module graph collects relative value re-export surface", SourceModuleGraphCollectsRelativeValueReExportSurface),
        new TypeSharpCompilerTestCase("source module graph collects relative type re-export surface", SourceModuleGraphCollectsRelativeTypeReExportSurface),
        new TypeSharpCompilerTestCase("source module graph collects relative star re-export surface", SourceModuleGraphCollectsRelativeStarReExportSurface),
        new TypeSharpCompilerTestCase("source module graph reports missing named exports", SourceModuleGraphReportsMissingNamedExports),
        new TypeSharpCompilerTestCase("source module graph reports missing re-exported names", SourceModuleGraphReportsMissingReExportedNames),
        new TypeSharpCompilerTestCase("source module graph reports missing type re-exported names", SourceModuleGraphReportsMissingTypeReExportedNames),
        new TypeSharpCompilerTestCase("source module graph reports missing namespace import members", SourceModuleGraphReportsMissingNamespaceImportMembers),
        new TypeSharpCompilerTestCase("runtime project targets net48", RuntimeProjectTargetsNet48),
        new TypeSharpCompilerTestCase("core project targets net48", CoreProjectTargetsNet48),
        new TypeSharpCompilerTestCase("runtime ABI constants are aligned", RuntimeAbiConstantsAreAligned),
        new TypeSharpCompilerTestCase("net48 runtime artifacts avoid external package dependencies", Net48RuntimeArtifactsAvoidExternalPackageDependencies),
        new TypeSharpCompilerTestCase("core option and result expose basic states", CoreOptionAndResultExposeBasicStates),
        new TypeSharpCompilerTestCase("runtime union helper exposes case metadata", RuntimeUnionHelperExposesCaseMetadata),
        new TypeSharpCompilerTestCase("runtime pattern helper matches union cases", RuntimePatternHelperMatchesUnionCases),
        new TypeSharpCompilerTestCase("runtime equality helper combines values", RuntimeEqualityHelperCombinesValues),
        new TypeSharpCompilerTestCase("runtime async helper creates tasks", RuntimeAsyncHelperCreatesTasks),
        new TypeSharpCompilerTestCase("reference resolver normalizes framework assemblies", ReferenceResolverNormalizesFrameworkAssemblies),
        new TypeSharpCompilerTestCase("reference resolver normalizes local DLL paths", ReferenceResolverNormalizesLocalDllPaths),
        new TypeSharpCompilerTestCase("reference resolver reports missing local DLL diagnostics", ReferenceResolverReportsMissingLocalDllDiagnostics),
        new TypeSharpCompilerTestCase("reference resolver reports unsupported package diagnostics", ReferenceResolverReportsUnsupportedPackageDiagnostics),
        new TypeSharpCompilerTestCase("metadata reader indexes framework assembly public symbols", MetadataReaderIndexesFrameworkAssemblyPublicSymbols),
        new TypeSharpCompilerTestCase("metadata reader creates local assembly placeholders", MetadataReaderCreatesLocalAssemblyPlaceholders),
        new TypeSharpCompilerTestCase("metadata reader indexes local public symbols", MetadataReaderIndexesLocalPublicSymbols),
        new TypeSharpCompilerTestCase("metadata reader preserves reference resolution diagnostics", MetadataReaderPreservesReferenceResolutionDiagnostics),
        new TypeSharpCompilerTestCase("metadata reader reports missing local metadata inputs", MetadataReaderReportsMissingLocalMetadataInputs),
        new TypeSharpCompilerTestCase("checker reports missing reference diagnostics", CheckerReportsMissingReferenceDiagnostics),
        new TypeSharpCompilerTestCase("checker reports invalid byref interop diagnostics", CheckerReportsInvalidByRefInteropDiagnostics),
        new TypeSharpCompilerTestCase("checker reports explicit generic byref interop diagnostics", CheckerReportsExplicitGenericByRefInteropDiagnostics),
        new TypeSharpCompilerTestCase("checker reports unsatisfied C# generic constraint diagnostics", CheckerReportsUnsatisfiedCSharpGenericConstraintDiagnostics),
        new TypeSharpCompilerTestCase("checker reports unsatisfied framework C# generic constraint diagnostics", CheckerReportsUnsatisfiedFrameworkCSharpGenericConstraintDiagnostics),
        new TypeSharpCompilerTestCase("checker accepts transitive C# generic type constraints", CheckerAcceptsTransitiveCSharpGenericTypeConstraints),
        new TypeSharpCompilerTestCase("checker accepts inferred C# generic type constraints", CheckerAcceptsInferredCSharpGenericTypeConstraints),
        new TypeSharpCompilerTestCase("checker accepts inferred C# generic array constraints", CheckerAcceptsInferredCSharpGenericArrayConstraints),
        new TypeSharpCompilerTestCase("checker reports unsatisfied inferred C# generic constraint diagnostics", CheckerReportsUnsatisfiedInferredCSharpGenericConstraintDiagnostics),
        new TypeSharpCompilerTestCase("checker reports unsatisfied inferred C# generic array constraint diagnostics", CheckerReportsUnsatisfiedInferredCSharpGenericArrayConstraintDiagnostics),
        new TypeSharpCompilerTestCase("checker reports unsatisfied inferred constructed C# generic constraint diagnostics", CheckerReportsUnsatisfiedInferredConstructedCSharpGenericConstraintDiagnostics),
        new TypeSharpCompilerTestCase("checker accepts imported C# interface implementation relation", CheckerAcceptsImportedCSharpInterfaceImplementationRelation),
        new TypeSharpCompilerTestCase("checker reports no matching C# overload diagnostics", CheckerReportsNoMatchingCSharpOverloadDiagnostics),
        new TypeSharpCompilerTestCase("checker reports no matching C# overload for known argument type diagnostics", CheckerReportsNoMatchingCSharpOverloadForKnownArgumentTypeDiagnostics),
        new TypeSharpCompilerTestCase("checker reports no matching C# overload for numeric literal conversion diagnostics", CheckerReportsNoMatchingCSharpOverloadForNumericLiteralConversionDiagnostics),
        new TypeSharpCompilerTestCase("checker reports no matching C# overload for unary numeric argument diagnostics", CheckerReportsNoMatchingCSharpOverloadForUnaryNumericArgumentDiagnostics),
        new TypeSharpCompilerTestCase("checker reports no matching C# overload for collection expression argument diagnostics", CheckerReportsNoMatchingCSharpOverloadForCollectionExpressionArgumentDiagnostics),
        new TypeSharpCompilerTestCase("checker accepts imported params collection expression array overload", CheckerAcceptsImportedParamsCollectionExpressionArrayOverload),
        new TypeSharpCompilerTestCase("checker reports no matching C# overload for imported metadata argument diagnostics", CheckerReportsNoMatchingCSharpOverloadForImportedMetadataArgumentDiagnostics),
        new TypeSharpCompilerTestCase("checker reports no matching C# overload for null literal diagnostics", CheckerReportsNoMatchingCSharpOverloadForNullLiteralDiagnostics),
        new TypeSharpCompilerTestCase("checker reports no matching C# constructor diagnostics", CheckerReportsNoMatchingCSharpConstructorDiagnostics),
        new TypeSharpCompilerTestCase("checker reports no matching C# generic constructor diagnostics", CheckerReportsNoMatchingCSharpGenericConstructorDiagnostics),
        new TypeSharpCompilerTestCase("checker reports ambiguous C# constructor diagnostics", CheckerReportsAmbiguousCSharpConstructorDiagnostics),
        new TypeSharpCompilerTestCase("checker reports missing C# method diagnostics", CheckerReportsMissingCSharpMethodDiagnostics),
        new TypeSharpCompilerTestCase("checker reports missing C# type diagnostics", CheckerReportsMissingCSharpTypeDiagnostics),
        new TypeSharpCompilerTestCase("checker reports missing framework C# type diagnostics", CheckerReportsMissingFrameworkCSharpTypeDiagnostics),
        new TypeSharpCompilerTestCase("checker reports imported C# enum match exhaustiveness", CheckerReportsImportedCSharpEnumMatchExhaustiveness),
        new TypeSharpCompilerTestCase("checker reports missing framework C# method diagnostics", CheckerReportsMissingFrameworkCSharpMethodDiagnostics),
        new TypeSharpCompilerTestCase("checker reports missing C# static member diagnostics", CheckerReportsMissingCSharpStaticMemberDiagnostics),
        new TypeSharpCompilerTestCase("checker reports missing framework C# static member diagnostics", CheckerReportsMissingFrameworkCSharpStaticMemberDiagnostics),
        new TypeSharpCompilerTestCase("checker reports missing C# instance member diagnostics", CheckerReportsMissingCSharpInstanceMemberDiagnostics),
        new TypeSharpCompilerTestCase("checker reports missing C# parameter instance member diagnostics", CheckerReportsMissingCSharpParameterInstanceMemberDiagnostics),
        new TypeSharpCompilerTestCase("checker reports missing C# alias instance member diagnostics", CheckerReportsMissingCSharpAliasInstanceMemberDiagnostics),
        new TypeSharpCompilerTestCase("checker reports missing C# assigned instance member diagnostics", CheckerReportsMissingCSharpAssignedInstanceMemberDiagnostics),
        new TypeSharpCompilerTestCase("checker accepts imported C# extension method instance syntax", CheckerAcceptsImportedCSharpExtensionMethodInstanceSyntax),
        new TypeSharpCompilerTestCase("checker accepts imported C# extension receiver relationship ranking", CheckerAcceptsImportedCSharpExtensionReceiverRelationshipRanking),
        new TypeSharpCompilerTestCase("checker accepts imported C# extension receiver object fallback", CheckerAcceptsImportedCSharpExtensionReceiverObjectFallback),
        new TypeSharpCompilerTestCase("checker reports no matching C# extension overload diagnostics", CheckerReportsNoMatchingCSharpExtensionOverloadDiagnostics),
        new TypeSharpCompilerTestCase("checker reports missing C# instance indexer diagnostics", CheckerReportsMissingCSharpInstanceIndexerDiagnostics),
        new TypeSharpCompilerTestCase("checker reports mismatched C# instance indexer diagnostics", CheckerReportsMismatchedCSharpInstanceIndexerDiagnostics),
        new TypeSharpCompilerTestCase("checker reports mismatched C# instance indexer numeric literal diagnostics", CheckerReportsMismatchedCSharpInstanceIndexerNumericLiteralDiagnostics),
        new TypeSharpCompilerTestCase("checker reports mismatched C# instance indexer unary numeric diagnostics", CheckerReportsMismatchedCSharpInstanceIndexerUnaryNumericDiagnostics),
        new TypeSharpCompilerTestCase("checker reports mismatched C# instance indexer parenthesized argument diagnostics", CheckerReportsMismatchedCSharpInstanceIndexerParenthesizedArgumentDiagnostics),
        new TypeSharpCompilerTestCase("checker reports mismatched C# instance indexer null literal diagnostics", CheckerReportsMismatchedCSharpInstanceIndexerNullLiteralDiagnostics),
        new TypeSharpCompilerTestCase("checker reports ambiguous C# instance indexer diagnostics", CheckerReportsAmbiguousCSharpInstanceIndexerDiagnostics),
        new TypeSharpCompilerTestCase("checker accepts imported C# indexer metadata relationship ranking", CheckerAcceptsImportedCSharpIndexerMetadataRelationshipRanking),
        new TypeSharpCompilerTestCase("checker accepts imported C# indexer null literal ranking", CheckerAcceptsImportedCSharpIndexerNullLiteralRanking),
        new TypeSharpCompilerTestCase("checker reports missing C# instance property setter diagnostics", CheckerReportsMissingCSharpInstancePropertySetterDiagnostics),
        new TypeSharpCompilerTestCase("checker reports missing C# parameter instance property setter diagnostics", CheckerReportsMissingCSharpParameterInstancePropertySetterDiagnostics),
        new TypeSharpCompilerTestCase("checker reports missing C# annotated local instance property setter diagnostics", CheckerReportsMissingCSharpAnnotatedLocalInstancePropertySetterDiagnostics),
        new TypeSharpCompilerTestCase("checker reports readonly C# instance field assignment diagnostics", CheckerReportsReadOnlyCSharpInstanceFieldAssignmentDiagnostics),
        new TypeSharpCompilerTestCase("checker reports missing C# static property setter diagnostics", CheckerReportsMissingCSharpStaticPropertySetterDiagnostics),
        new TypeSharpCompilerTestCase("checker reports readonly C# static field assignment diagnostics", CheckerReportsReadOnlyCSharpStaticFieldAssignmentDiagnostics),
        new TypeSharpCompilerTestCase("checker reports missing C# instance event diagnostics", CheckerReportsMissingCSharpInstanceEventDiagnostics),
        new TypeSharpCompilerTestCase("checker reports ambiguous C# overload diagnostics", CheckerReportsAmbiguousCSharpOverloadDiagnostics),
        new TypeSharpCompilerTestCase("checker reports no matching C# delegate lambda overload diagnostics", CheckerReportsNoMatchingCSharpDelegateLambdaOverloadDiagnostics),
        new TypeSharpCompilerTestCase("checker reports no matching C# delegate lambda return overload diagnostics", CheckerReportsNoMatchingCSharpDelegateLambdaReturnOverloadDiagnostics),
        new TypeSharpCompilerTestCase("checker reports no matching C# delegate lambda parameter return overload diagnostics", CheckerReportsNoMatchingCSharpDelegateLambdaParameterReturnOverloadDiagnostics),
        new TypeSharpCompilerTestCase("checker reports no matching C# delegate lambda member return overload diagnostics", CheckerReportsNoMatchingCSharpDelegateLambdaMemberReturnOverloadDiagnostics),
        new TypeSharpCompilerTestCase("checker reports no matching C# delegate lambda chained member return overload diagnostics", CheckerReportsNoMatchingCSharpDelegateLambdaChainedMemberReturnOverloadDiagnostics),
        new TypeSharpCompilerTestCase("checker reports no matching C# delegate lambda method return overload diagnostics", CheckerReportsNoMatchingCSharpDelegateLambdaMethodReturnOverloadDiagnostics),
        new TypeSharpCompilerTestCase("checker reports no matching C# delegate lambda extension method return overload diagnostics", CheckerReportsNoMatchingCSharpDelegateLambdaExtensionMethodReturnOverloadDiagnostics),
        new TypeSharpCompilerTestCase("checker reports no matching C# delegate lambda static method return overload diagnostics", CheckerReportsNoMatchingCSharpDelegateLambdaStaticMethodReturnOverloadDiagnostics),
        new TypeSharpCompilerTestCase("checker reports no matching C# delegate lambda binary return overload diagnostics", CheckerReportsNoMatchingCSharpDelegateLambdaBinaryReturnOverloadDiagnostics),
        new TypeSharpCompilerTestCase("checker reports no matching C# delegate lambda binary value return overload diagnostics", CheckerReportsNoMatchingCSharpDelegateLambdaBinaryValueReturnOverloadDiagnostics),
        new TypeSharpCompilerTestCase("checker reports no matching C# delegate lambda nameof return overload diagnostics", CheckerReportsNoMatchingCSharpDelegateLambdaNameofReturnOverloadDiagnostics),
        new TypeSharpCompilerTestCase("checker reports no matching C# delegate lambda unchecked return overload diagnostics", CheckerReportsNoMatchingCSharpDelegateLambdaUncheckedReturnOverloadDiagnostics),
        new TypeSharpCompilerTestCase("checker reports no matching C# delegate lambda satisfies return overload diagnostics", CheckerReportsNoMatchingCSharpDelegateLambdaSatisfiesReturnOverloadDiagnostics),
        new TypeSharpCompilerTestCase("checker reports no matching C# delegate lambda parenthesized return overload diagnostics", CheckerReportsNoMatchingCSharpDelegateLambdaParenthesizedReturnOverloadDiagnostics),
        new TypeSharpCompilerTestCase("checker reports no matching C# delegate lambda logical not return overload diagnostics", CheckerReportsNoMatchingCSharpDelegateLambdaLogicalNotReturnOverloadDiagnostics),
        new TypeSharpCompilerTestCase("checker reports no matching C# delegate lambda unary numeric return overload diagnostics", CheckerReportsNoMatchingCSharpDelegateLambdaUnaryNumericReturnOverloadDiagnostics),
        new TypeSharpCompilerTestCase("checker reports no matching C# delegate lambda if return overload diagnostics", CheckerReportsNoMatchingCSharpDelegateLambdaIfReturnOverloadDiagnostics),
        new TypeSharpCompilerTestCase("checker reports no matching C# delegate lambda block return overload diagnostics", CheckerReportsNoMatchingCSharpDelegateLambdaBlockReturnOverloadDiagnostics),
        new TypeSharpCompilerTestCase("checker reports no matching C# delegate lambda collection return overload diagnostics", CheckerReportsNoMatchingCSharpDelegateLambdaCollectionReturnOverloadDiagnostics),
        new TypeSharpCompilerTestCase("checker reports no matching C# delegate lambda coalesce return overload diagnostics", CheckerReportsNoMatchingCSharpDelegateLambdaCoalesceReturnOverloadDiagnostics),
        new TypeSharpCompilerTestCase("checker reports no matching C# delegate lambda indexer return overload diagnostics", CheckerReportsNoMatchingCSharpDelegateLambdaIndexerReturnOverloadDiagnostics),
        new TypeSharpCompilerTestCase("C# overload resolver selects exact literal match", CSharpOverloadResolverSelectsExactLiteralMatch),
        new TypeSharpCompilerTestCase("C# overload resolver filters known argument type mismatch", CSharpOverloadResolverFiltersKnownArgumentTypeMismatch),
        new TypeSharpCompilerTestCase("C# overload resolver filters numeric literal conversion mismatch", CSharpOverloadResolverFiltersNumericLiteralConversionMismatch),
        new TypeSharpCompilerTestCase("C# overload resolver filters unary numeric argument conversion", CSharpOverloadResolverFiltersUnaryNumericArgumentConversion),
        new TypeSharpCompilerTestCase("C# overload resolver filters collection expression argument type", CSharpOverloadResolverFiltersCollectionExpressionArgumentType),
        new TypeSharpCompilerTestCase("C# overload resolver treats collection expression as params array", CSharpOverloadResolverTreatsCollectionExpressionAsParamsArray),
        new TypeSharpCompilerTestCase("C# overload resolver ranks null literal reference match", CSharpOverloadResolverRanksNullLiteralReferenceMatch),
        new TypeSharpCompilerTestCase("C# overload resolver ranks null literal nearest metadata reference", CSharpOverloadResolverRanksNullLiteralNearestMetadataReference),
        new TypeSharpCompilerTestCase("C# overload resolver ranks parenthesized null literal nearest metadata reference", CSharpOverloadResolverRanksParenthesizedNullLiteralNearestMetadataReference),
        new TypeSharpCompilerTestCase("C# overload resolver ranks nearest metadata relationship", CSharpOverloadResolverRanksNearestMetadataRelationship),
        new TypeSharpCompilerTestCase("C# overload resolver filters explicit generic arity", CSharpOverloadResolverFiltersExplicitGenericArity),
        new TypeSharpCompilerTestCase("C# overload resolver filters lambda delegate arity", CSharpOverloadResolverFiltersLambdaDelegateArity),
        new TypeSharpCompilerTestCase("C# overload resolver filters parenthesized lambda delegate argument", CSharpOverloadResolverFiltersParenthesizedLambdaDelegateArgument),
        new TypeSharpCompilerTestCase("C# overload resolver filters lambda delegate return type", CSharpOverloadResolverFiltersLambdaDelegateReturnType),
        new TypeSharpCompilerTestCase("C# overload resolver filters lambda delegate parameter return type", CSharpOverloadResolverFiltersLambdaDelegateParameterReturnType),
        new TypeSharpCompilerTestCase("C# overload resolver filters lambda delegate member return type", CSharpOverloadResolverFiltersLambdaDelegateMemberReturnType),
        new TypeSharpCompilerTestCase("C# overload resolver filters lambda delegate chained member return type", CSharpOverloadResolverFiltersLambdaDelegateChainedMemberReturnType),
        new TypeSharpCompilerTestCase("C# overload resolver filters lambda delegate method return type", CSharpOverloadResolverFiltersLambdaDelegateMethodReturnType),
        new TypeSharpCompilerTestCase("C# overload resolver filters lambda delegate extension method return type", CSharpOverloadResolverFiltersLambdaDelegateExtensionMethodReturnType),
        new TypeSharpCompilerTestCase("C# overload resolver filters lambda delegate static method return type", CSharpOverloadResolverFiltersLambdaDelegateStaticMethodReturnType),
        new TypeSharpCompilerTestCase("C# overload resolver filters lambda delegate binary return type", CSharpOverloadResolverFiltersLambdaDelegateBinaryReturnType),
        new TypeSharpCompilerTestCase("C# overload resolver filters lambda delegate binary value return type", CSharpOverloadResolverFiltersLambdaDelegateBinaryValueReturnType),
        new TypeSharpCompilerTestCase("C# overload resolver filters lambda delegate nameof return type", CSharpOverloadResolverFiltersLambdaDelegateNameofReturnType),
        new TypeSharpCompilerTestCase("C# overload resolver filters lambda delegate checked return type", CSharpOverloadResolverFiltersLambdaDelegateCheckedReturnType),
        new TypeSharpCompilerTestCase("C# overload resolver filters lambda delegate unchecked return type", CSharpOverloadResolverFiltersLambdaDelegateUncheckedReturnType),
        new TypeSharpCompilerTestCase("C# overload resolver filters lambda delegate satisfies return type", CSharpOverloadResolverFiltersLambdaDelegateSatisfiesReturnType),
        new TypeSharpCompilerTestCase("C# overload resolver filters lambda delegate parenthesized return type", CSharpOverloadResolverFiltersLambdaDelegateParenthesizedReturnType),
        new TypeSharpCompilerTestCase("C# overload resolver filters lambda delegate logical not return type", CSharpOverloadResolverFiltersLambdaDelegateLogicalNotReturnType),
        new TypeSharpCompilerTestCase("C# overload resolver filters lambda delegate unary numeric return type", CSharpOverloadResolverFiltersLambdaDelegateUnaryNumericReturnType),
        new TypeSharpCompilerTestCase("C# overload resolver filters lambda delegate if return type", CSharpOverloadResolverFiltersLambdaDelegateIfReturnType),
        new TypeSharpCompilerTestCase("C# overload resolver filters lambda delegate block return type", CSharpOverloadResolverFiltersLambdaDelegateBlockReturnType),
        new TypeSharpCompilerTestCase("C# overload resolver filters lambda delegate collection return type", CSharpOverloadResolverFiltersLambdaDelegateCollectionReturnType),
        new TypeSharpCompilerTestCase("C# overload resolver filters lambda delegate coalesce return type", CSharpOverloadResolverFiltersLambdaDelegateCoalesceReturnType),
        new TypeSharpCompilerTestCase("C# overload resolver filters lambda delegate indexer return type", CSharpOverloadResolverFiltersLambdaDelegateIndexerReturnType),
        new TypeSharpCompilerTestCase("C# overload resolver ranks lambda delegate return type", CSharpOverloadResolverRanksLambdaDelegateReturnType),
        new TypeSharpCompilerTestCase("checker reports ambiguous expanded params overload diagnostics", CheckerReportsAmbiguousExpandedParamsOverloadDiagnostics),
        new TypeSharpCompilerTestCase("checker reports ambiguous optional overload diagnostics", CheckerReportsAmbiguousOptionalOverloadDiagnostics),
        new TypeSharpCompilerTestCase("checker reports unknown C# nullability diagnostics", CheckerReportsUnknownCSharpNullabilityDiagnostics),
        new TypeSharpCompilerTestCase("CLI check emits JSON reference diagnostics", CliCheckEmitsJsonReferenceDiagnostics),
        new TypeSharpCompilerTestCase("CLI check emits JSON duplicate source module diagnostics", CliCheckEmitsJsonDuplicateSourceModuleDiagnostics),
        new TypeSharpCompilerTestCase("CLI check accepts relative source module import aliases", CliCheckAcceptsRelativeSourceModuleImportAliases),
        new TypeSharpCompilerTestCase("CLI check accepts source module alias imports", CliCheckAcceptsSourceModuleAliasImports),
        new TypeSharpCompilerTestCase("CLI check accepts project reference source imports", CliCheckAcceptsProjectReferenceSourceImports),
        new TypeSharpCompilerTestCase("CLI check accepts referenced project own project reference source imports", CliCheckAcceptsReferencedProjectOwnProjectReferenceSourceImports),
        new TypeSharpCompilerTestCase("CLI check emits JSON unresolved source module diagnostics", CliCheckEmitsJsonUnresolvedSourceModuleDiagnostics),
        new TypeSharpCompilerTestCase("CLI check emits JSON source alias diagnostics", CliCheckEmitsJsonSourceAliasDiagnostics),
        new TypeSharpCompilerTestCase("CLI check emits JSON project reference diagnostics", CliCheckEmitsJsonProjectReferenceDiagnostics),
        new TypeSharpCompilerTestCase("CLI check emits JSON project reference cycle diagnostics", CliCheckEmitsJsonProjectReferenceCycleDiagnostics),
        new TypeSharpCompilerTestCase("CLI check emits JSON incompatible project reference target diagnostics", CliCheckEmitsJsonIncompatibleProjectReferenceTargetDiagnostics),
        new TypeSharpCompilerTestCase("CLI check emits JSON missing project reference export diagnostics", CliCheckEmitsJsonMissingProjectReferenceExportDiagnostics),
        new TypeSharpCompilerTestCase("CLI check rejects hidden transitive project source imports", CliCheckRejectsHiddenTransitiveProjectSourceImports),
        new TypeSharpCompilerTestCase("CLI check rejects project reference re-exports until supported", CliCheckRejectsProjectReferenceReExportsUntilSupported),
        new TypeSharpCompilerTestCase("CLI check emits JSON missing source module export diagnostics", CliCheckEmitsJsonMissingSourceModuleExportDiagnostics),
        new TypeSharpCompilerTestCase("CLI check emits JSON missing source module re-export diagnostics", CliCheckEmitsJsonMissingSourceModuleReExportDiagnostics),
        new TypeSharpCompilerTestCase("CLI check emits JSON missing source module namespace member diagnostics", CliCheckEmitsJsonMissingSourceModuleNamespaceMemberDiagnostics),
        new TypeSharpCompilerTestCase("CLI check emits JSON unsupported package diagnostics", CliCheckEmitsJsonUnsupportedPackageDiagnostics),
        new TypeSharpCompilerTestCase("CLI build stops before emission on reference diagnostics", CliBuildStopsBeforeEmissionOnReferenceDiagnostics),
        new TypeSharpCompilerTestCase("CLI build stops before emission on duplicate source modules", CliBuildStopsBeforeEmissionOnDuplicateSourceModules),
        new TypeSharpCompilerTestCase("CLI build lowers relative source module import aliases", CliBuildLowersRelativeSourceModuleImportAliases),
        new TypeSharpCompilerTestCase("CLI build lowers source module alias imports", CliBuildLowersSourceModuleAliasImports),
        new TypeSharpCompilerTestCase("CLI build builds project references before dependent", CliBuildBuildsProjectReferencesBeforeDependent),
        new TypeSharpCompilerTestCase("CLI build stops before emission on missing source module exports", CliBuildStopsBeforeEmissionOnMissingSourceModuleExports),
        new TypeSharpCompilerTestCase("CLI build stops before emission on missing source module re-exports", CliBuildStopsBeforeEmissionOnMissingSourceModuleReExports),
        new TypeSharpCompilerTestCase("CLI build stops before emission on missing source module namespace members", CliBuildStopsBeforeEmissionOnMissingSourceModuleNamespaceMembers),
        new TypeSharpCompilerTestCase("CLI build stops before emission on package diagnostics", CliBuildStopsBeforeEmissionOnPackageDiagnostics),
        new TypeSharpCompilerTestCase("CLI build stops before emission on invalid byref interop", CliBuildStopsBeforeEmissionOnInvalidByRefInterop),
        new TypeSharpCompilerTestCase("CLI build stops before emission on unsatisfied C# generic constraint", CliBuildStopsBeforeEmissionOnUnsatisfiedCSharpGenericConstraint),
        new TypeSharpCompilerTestCase("CLI build stops before emission on unsatisfied framework C# generic constraint", CliBuildStopsBeforeEmissionOnUnsatisfiedFrameworkCSharpGenericConstraint),
        new TypeSharpCompilerTestCase("CLI build stops before emission on unsatisfied inferred C# generic constraint", CliBuildStopsBeforeEmissionOnUnsatisfiedInferredCSharpGenericConstraint),
        new TypeSharpCompilerTestCase("CLI build stops before emission on unsatisfied inferred C# generic array constraint", CliBuildStopsBeforeEmissionOnUnsatisfiedInferredCSharpGenericArrayConstraint),
        new TypeSharpCompilerTestCase("CLI build stops before emission on unsatisfied inferred constructed C# generic constraint", CliBuildStopsBeforeEmissionOnUnsatisfiedInferredConstructedCSharpGenericConstraint),
        new TypeSharpCompilerTestCase("CLI build stops before emission on no matching C# overload", CliBuildStopsBeforeEmissionOnNoMatchingCSharpOverload),
        new TypeSharpCompilerTestCase("CLI build stops before emission on no matching C# delegate lambda overload", CliBuildStopsBeforeEmissionOnNoMatchingCSharpDelegateLambdaOverload),
        new TypeSharpCompilerTestCase("CLI build stops before emission on no matching C# delegate lambda return overload", CliBuildStopsBeforeEmissionOnNoMatchingCSharpDelegateLambdaReturnOverload),
        new TypeSharpCompilerTestCase("CLI build stops before emission on no matching C# delegate lambda parameter return overload", CliBuildStopsBeforeEmissionOnNoMatchingCSharpDelegateLambdaParameterReturnOverload),
        new TypeSharpCompilerTestCase("CLI build stops before emission on no matching C# delegate lambda member return overload", CliBuildStopsBeforeEmissionOnNoMatchingCSharpDelegateLambdaMemberReturnOverload),
        new TypeSharpCompilerTestCase("CLI build stops before emission on no matching C# delegate lambda chained member return overload", CliBuildStopsBeforeEmissionOnNoMatchingCSharpDelegateLambdaChainedMemberReturnOverload),
        new TypeSharpCompilerTestCase("CLI build stops before emission on no matching C# delegate lambda method return overload", CliBuildStopsBeforeEmissionOnNoMatchingCSharpDelegateLambdaMethodReturnOverload),
        new TypeSharpCompilerTestCase("CLI build stops before emission on no matching C# delegate lambda extension method return overload", CliBuildStopsBeforeEmissionOnNoMatchingCSharpDelegateLambdaExtensionMethodReturnOverload),
        new TypeSharpCompilerTestCase("CLI build stops before emission on no matching C# delegate lambda static method return overload", CliBuildStopsBeforeEmissionOnNoMatchingCSharpDelegateLambdaStaticMethodReturnOverload),
        new TypeSharpCompilerTestCase("CLI build stops before emission on no matching C# delegate lambda binary return overload", CliBuildStopsBeforeEmissionOnNoMatchingCSharpDelegateLambdaBinaryReturnOverload),
        new TypeSharpCompilerTestCase("CLI build stops before emission on no matching C# delegate lambda binary value return overload", CliBuildStopsBeforeEmissionOnNoMatchingCSharpDelegateLambdaBinaryValueReturnOverload),
        new TypeSharpCompilerTestCase("CLI build stops before emission on no matching C# delegate lambda nameof return overload", CliBuildStopsBeforeEmissionOnNoMatchingCSharpDelegateLambdaNameofReturnOverload),
        new TypeSharpCompilerTestCase("CLI build stops before emission on no matching C# delegate lambda unchecked return overload", CliBuildStopsBeforeEmissionOnNoMatchingCSharpDelegateLambdaUncheckedReturnOverload),
        new TypeSharpCompilerTestCase("CLI build stops before emission on no matching C# delegate lambda satisfies return overload", CliBuildStopsBeforeEmissionOnNoMatchingCSharpDelegateLambdaSatisfiesReturnOverload),
        new TypeSharpCompilerTestCase("CLI build stops before emission on no matching C# delegate lambda parenthesized return overload", CliBuildStopsBeforeEmissionOnNoMatchingCSharpDelegateLambdaParenthesizedReturnOverload),
        new TypeSharpCompilerTestCase("CLI build stops before emission on no matching C# delegate lambda logical not return overload", CliBuildStopsBeforeEmissionOnNoMatchingCSharpDelegateLambdaLogicalNotReturnOverload),
        new TypeSharpCompilerTestCase("CLI build stops before emission on no matching C# delegate lambda unary numeric return overload", CliBuildStopsBeforeEmissionOnNoMatchingCSharpDelegateLambdaUnaryNumericReturnOverload),
        new TypeSharpCompilerTestCase("CLI build stops before emission on no matching C# delegate lambda if return overload", CliBuildStopsBeforeEmissionOnNoMatchingCSharpDelegateLambdaIfReturnOverload),
        new TypeSharpCompilerTestCase("CLI build stops before emission on no matching C# delegate lambda block return overload", CliBuildStopsBeforeEmissionOnNoMatchingCSharpDelegateLambdaBlockReturnOverload),
        new TypeSharpCompilerTestCase("CLI build stops before emission on no matching C# delegate lambda collection return overload", CliBuildStopsBeforeEmissionOnNoMatchingCSharpDelegateLambdaCollectionReturnOverload),
        new TypeSharpCompilerTestCase("CLI build stops before emission on no matching C# delegate lambda coalesce return overload", CliBuildStopsBeforeEmissionOnNoMatchingCSharpDelegateLambdaCoalesceReturnOverload),
        new TypeSharpCompilerTestCase("CLI build stops before emission on no matching C# delegate lambda indexer return overload", CliBuildStopsBeforeEmissionOnNoMatchingCSharpDelegateLambdaIndexerReturnOverload),
        new TypeSharpCompilerTestCase("CLI build stops before emission on known argument type C# overload mismatch", CliBuildStopsBeforeEmissionOnKnownArgumentTypeCSharpOverloadMismatch),
        new TypeSharpCompilerTestCase("CLI build stops before emission on numeric literal C# overload mismatch", CliBuildStopsBeforeEmissionOnNumericLiteralCSharpOverloadMismatch),
        new TypeSharpCompilerTestCase("CLI build stops before emission on unary numeric C# overload mismatch", CliBuildStopsBeforeEmissionOnUnaryNumericCSharpOverloadMismatch),
        new TypeSharpCompilerTestCase("CLI build stops before emission on collection expression C# overload mismatch", CliBuildStopsBeforeEmissionOnCollectionExpressionCSharpOverloadMismatch),
        new TypeSharpCompilerTestCase("CLI build stops before emission on imported metadata argument C# overload mismatch", CliBuildStopsBeforeEmissionOnImportedMetadataArgumentCSharpOverloadMismatch),
        new TypeSharpCompilerTestCase("CLI build stops before emission on null literal C# overload mismatch", CliBuildStopsBeforeEmissionOnNullLiteralCSharpOverloadMismatch),
        new TypeSharpCompilerTestCase("CLI build stops before emission on no matching C# constructor", CliBuildStopsBeforeEmissionOnNoMatchingCSharpConstructor),
        new TypeSharpCompilerTestCase("CLI build stops before emission on no matching C# generic constructor", CliBuildStopsBeforeEmissionOnNoMatchingCSharpGenericConstructor),
        new TypeSharpCompilerTestCase("CLI build stops before emission on ambiguous C# constructor", CliBuildStopsBeforeEmissionOnAmbiguousCSharpConstructor),
        new TypeSharpCompilerTestCase("CLI build stops before emission on missing C# method", CliBuildStopsBeforeEmissionOnMissingCSharpMethod),
        new TypeSharpCompilerTestCase("CLI build stops before emission on missing C# type", CliBuildStopsBeforeEmissionOnMissingCSharpType),
        new TypeSharpCompilerTestCase("CLI build stops before emission on missing framework C# type", CliBuildStopsBeforeEmissionOnMissingFrameworkCSharpType),
        new TypeSharpCompilerTestCase("CLI build stops before emission on missing framework C# method", CliBuildStopsBeforeEmissionOnMissingFrameworkCSharpMethod),
        new TypeSharpCompilerTestCase("CLI build stops before emission on missing C# static member", CliBuildStopsBeforeEmissionOnMissingCSharpStaticMember),
        new TypeSharpCompilerTestCase("CLI build stops before emission on missing framework C# static member", CliBuildStopsBeforeEmissionOnMissingFrameworkCSharpStaticMember),
        new TypeSharpCompilerTestCase("CLI build stops before emission on missing C# instance member", CliBuildStopsBeforeEmissionOnMissingCSharpInstanceMember),
        new TypeSharpCompilerTestCase("CLI build stops before emission on missing C# parameter instance member", CliBuildStopsBeforeEmissionOnMissingCSharpParameterInstanceMember),
        new TypeSharpCompilerTestCase("CLI build stops before emission on missing C# alias instance member", CliBuildStopsBeforeEmissionOnMissingCSharpAliasInstanceMember),
        new TypeSharpCompilerTestCase("CLI build stops before emission on missing C# assigned instance member", CliBuildStopsBeforeEmissionOnMissingCSharpAssignedInstanceMember),
        new TypeSharpCompilerTestCase("CLI build stops before emission on no matching C# extension overload", CliBuildStopsBeforeEmissionOnNoMatchingCSharpExtensionOverload),
        new TypeSharpCompilerTestCase("CLI build stops before emission on missing C# instance indexer", CliBuildStopsBeforeEmissionOnMissingCSharpInstanceIndexer),
        new TypeSharpCompilerTestCase("CLI build stops before emission on mismatched C# instance indexer", CliBuildStopsBeforeEmissionOnMismatchedCSharpInstanceIndexer),
        new TypeSharpCompilerTestCase("CLI build stops before emission on mismatched C# instance indexer numeric literal", CliBuildStopsBeforeEmissionOnMismatchedCSharpInstanceIndexerNumericLiteral),
        new TypeSharpCompilerTestCase("CLI build stops before emission on mismatched C# instance indexer unary numeric", CliBuildStopsBeforeEmissionOnMismatchedCSharpInstanceIndexerUnaryNumeric),
        new TypeSharpCompilerTestCase("CLI build stops before emission on mismatched C# instance indexer parenthesized argument", CliBuildStopsBeforeEmissionOnMismatchedCSharpInstanceIndexerParenthesizedArgument),
        new TypeSharpCompilerTestCase("CLI build stops before emission on mismatched C# instance indexer null literal", CliBuildStopsBeforeEmissionOnMismatchedCSharpInstanceIndexerNullLiteral),
        new TypeSharpCompilerTestCase("CLI build stops before emission on ambiguous C# instance indexer", CliBuildStopsBeforeEmissionOnAmbiguousCSharpInstanceIndexer),
        new TypeSharpCompilerTestCase("CLI build stops before emission on missing C# instance property setter", CliBuildStopsBeforeEmissionOnMissingCSharpInstancePropertySetter),
        new TypeSharpCompilerTestCase("CLI build stops before emission on readonly C# instance field assignment", CliBuildStopsBeforeEmissionOnReadOnlyCSharpInstanceFieldAssignment),
        new TypeSharpCompilerTestCase("CLI build stops before emission on missing C# static property setter", CliBuildStopsBeforeEmissionOnMissingCSharpStaticPropertySetter),
        new TypeSharpCompilerTestCase("CLI build stops before emission on readonly C# static field assignment", CliBuildStopsBeforeEmissionOnReadOnlyCSharpStaticFieldAssignment),
        new TypeSharpCompilerTestCase("CLI build stops before emission on missing C# instance event", CliBuildStopsBeforeEmissionOnMissingCSharpInstanceEvent),
        new TypeSharpCompilerTestCase("CLI build stops before emission on ambiguous C# overload", CliBuildStopsBeforeEmissionOnAmbiguousCSharpOverload),
        new TypeSharpCompilerTestCase("CLI build stops before emission on type checker diagnostics", CliBuildStopsBeforeEmissionOnTypeCheckerDiagnostics),
        new TypeSharpCompilerTestCase("CLI build stops before emission on unsatisfied imported C# interface implementation", CliBuildStopsBeforeEmissionOnUnsatisfiedImportedCSharpInterfaceImplementation),
        new TypeSharpCompilerTestCase("CLI build stops before emission on nullability diagnostics", CliBuildStopsBeforeEmissionOnNullabilityDiagnostics),
        new TypeSharpCompilerTestCase("CLI build stops before emission on public boundary diagnostics", CliBuildStopsBeforeEmissionOnPublicBoundaryDiagnostics),
        new TypeSharpCompilerTestCase("CLI build stops before emission on non-exhaustive match", CliBuildStopsBeforeEmissionOnNonExhaustiveMatch),
        new TypeSharpCompilerTestCase("CLI build stops before emission on unsupported export forwarding", CliBuildStopsBeforeEmissionOnUnsupportedExportForwarding),
        new TypeSharpCompilerTestCase("CLI build stops before emission on duplicate local export", CliBuildStopsBeforeEmissionOnDuplicateLocalExport),
        new TypeSharpCompilerTestCase("CLI build uses local export lists for public surface", CliBuildUsesLocalExportListsForPublicSurface),
        new TypeSharpCompilerTestCase("CLI build lowers local function export aliases", CliBuildLowersLocalFunctionExportAliases),
        new TypeSharpCompilerTestCase("CLI build lowers local literal export aliases", CliBuildLowersLocalLiteralExportAliases),
        new TypeSharpCompilerTestCase("CLI build lowers local value export aliases", CliBuildLowersLocalValueExportAliases),
        new TypeSharpCompilerTestCase("CLI build lowers function value exports", CliBuildLowersFunctionValueExports),
        new TypeSharpCompilerTestCase("CLI build lowers inferred function value exports", CliBuildLowersInferredFunctionValueExports),
        new TypeSharpCompilerTestCase("CLI build lowers local type export aliases", CliBuildLowersLocalTypeExportAliases),
        new TypeSharpCompilerTestCase("manifest loader reports invalid manifest shape", ManifestLoaderReportsInvalidManifestShape),
        new TypeSharpCompilerTestCase("manifest loader rejects invalid option domains", ManifestLoaderRejectsInvalidOptionDomains),
        new TypeSharpCompilerTestCase("CLI check emits JSON invalid manifest value diagnostics", CliCheckEmitsJsonInvalidManifestValueDiagnostics),
        new TypeSharpCompilerTestCase("CLI run builds and runs generated net48 executable", CliRunBuildsAndRunsGeneratedNet48Executable),
        new TypeSharpCompilerTestCase("CLI run passes arguments to generated main", CliRunPassesArgumentsToGeneratedMain),
        new TypeSharpCompilerTestCase("CLI run uses module path container for multi-source executable", CliRunUsesModulePathContainerForMultiSourceExecutable),
        new TypeSharpCompilerTestCase("CLI run reports unsupported main signature", CliRunReportsUnsupportedMainSignature),
        new TypeSharpCompilerTestCase("CLI run rejects library projects", CliRunRejectsLibraryProjects),
        new TypeSharpCompilerTestCase("CLI build honors Release configuration", CliBuildHonorsReleaseConfiguration),
        new TypeSharpCompilerTestCase("CLI run honors Release configuration", CliRunHonorsReleaseConfiguration),
        new TypeSharpCompilerTestCase("CLI build honors target framework override", CliBuildHonorsTargetFrameworkOverride),
        new TypeSharpCompilerTestCase("CLI run honors target framework override", CliRunHonorsTargetFrameworkOverride),
        new TypeSharpCompilerTestCase("CLI build honors quiet verbosity", CliBuildHonorsQuietVerbosity),
        new TypeSharpCompilerTestCase("CLI build honors minimal verbosity", CliBuildHonorsMinimalVerbosity),
        new TypeSharpCompilerTestCase("lexer handles tokens used by hello fixture", LexerHandlesHelloFixtureTokens),
        new TypeSharpCompilerTestCase("parser parses hello fixture without diagnostics", ParserParsesHelloFixtureWithoutDiagnostics),
        new TypeSharpCompilerTestCase("parser parses module declaration without diagnostics", ParserParsesModuleDeclarationWithoutDiagnostics),
        new TypeSharpCompilerTestCase("parser parses unbound generic nameof without diagnostics", ParserParsesUnboundGenericNameofWithoutDiagnostics),
        new TypeSharpCompilerTestCase("parser rejects unbound generic outside nameof", ParserRejectsUnboundGenericOutsideNameof),
        new TypeSharpCompilerTestCase("parser fixture snapshots match", ParserFixtureSnapshotsMatch),
        new TypeSharpCompilerTestCase("binder fixture diagnostics match", BinderFixtureDiagnosticsMatch),
        new TypeSharpCompilerTestCase("type checker fixture diagnostics match", TypeCheckerFixtureDiagnosticsMatch),
        new TypeSharpCompilerTestCase("C# backend fixture snapshots match", CSharpBackendFixtureSnapshotsMatch),
        new TypeSharpCompilerTestCase("generated C# compiles in net48 project", GeneratedCSharpCompilesInNet48Project),
        new TypeSharpCompilerTestCase("binder binds local declarations without diagnostics", BinderBindsLocalDeclarationsWithoutDiagnostics),
        new TypeSharpCompilerTestCase("binder reports unresolved unbound generic nameof target", BinderReportsUnresolvedUnboundGenericNameofTarget),
        new TypeSharpCompilerTestCase("semantic model resolves symbols at source positions", SemanticModelResolvesSymbolsAtSourcePositions),
        new TypeSharpCompilerTestCase("checker reports unresolved name diagnostics", CheckerReportsUnresolvedNameDiagnostics),
        new TypeSharpCompilerTestCase("checker reports duplicate symbol diagnostics", CheckerReportsDuplicateSymbolDiagnostics),
        new TypeSharpCompilerTestCase("checker reports import alias conflict diagnostics", CheckerReportsImportAliasConflictDiagnostics),
        new TypeSharpCompilerTestCase("checker reports unsupported export forwarding diagnostics", CheckerReportsUnsupportedExportForwardingDiagnostics),
        new TypeSharpCompilerTestCase("checker reports duplicate local export diagnostics", CheckerReportsDuplicateLocalExportDiagnostics),
        new TypeSharpCompilerTestCase("checker reports unresolved local export list diagnostics", CheckerReportsUnresolvedLocalExportListDiagnostics),
        new TypeSharpCompilerTestCase("type checker accepts basic annotations", TypeCheckerAcceptsBasicAnnotations),
        new TypeSharpCompilerTestCase("inference engine infers local expression graph", InferenceEngineInfersLocalExpressionGraph),
        new TypeSharpCompilerTestCase("checker reports type mismatch diagnostics", CheckerReportsTypeMismatchDiagnostics),
        new TypeSharpCompilerTestCase("checker reports parser diagnostics", CheckerReportsParserDiagnostics),
        new TypeSharpCompilerTestCase("CLI check succeeds on parse-clean project", CliCheckSucceedsOnParseCleanProject),
        new TypeSharpCompilerTestCase("CLI check emits JSON parser diagnostics", CliCheckEmitsJsonParserDiagnostics),
        new TypeSharpCompilerTestCase("CLI check emits JSON type checker diagnostics", CliCheckEmitsJsonTypeCheckerDiagnostics),
        new TypeSharpCompilerTestCase("CLI check emits JSON nullability diagnostics", CliCheckEmitsJsonNullabilityDiagnostics),
        new TypeSharpCompilerTestCase("CLI check emits JSON structural diagnostics", CliCheckEmitsJsonStructuralDiagnostics),
        new TypeSharpCompilerTestCase("CLI check emits JSON public boundary diagnostics", CliCheckEmitsJsonPublicBoundaryDiagnostics),
        new TypeSharpCompilerTestCase("CLI check emits JSON duplicate symbol diagnostics", CliCheckEmitsJsonDuplicateSymbolDiagnostics),
        new TypeSharpCompilerTestCase("CLI check emits JSON import alias conflict diagnostics", CliCheckEmitsJsonImportAliasConflictDiagnostics),
        new TypeSharpCompilerTestCase("CLI check emits JSON unsupported export forwarding diagnostics", CliCheckEmitsJsonUnsupportedExportForwardingDiagnostics),
        new TypeSharpCompilerTestCase("CLI check emits JSON duplicate local export diagnostics", CliCheckEmitsJsonDuplicateLocalExportDiagnostics),
        new TypeSharpCompilerTestCase("CLI check emits JSON unsupported generic constraint diagnostics", CliCheckEmitsJsonUnsupportedGenericConstraintDiagnostics),
        new TypeSharpCompilerTestCase("CLI check emits JSON dynamic capability diagnostics", CliCheckEmitsJsonDynamicCapabilityDiagnostics),
        new TypeSharpCompilerTestCase("CLI check emits JSON dynamic call capability diagnostics", CliCheckEmitsJsonDynamicCallCapabilityDiagnostics),
        new TypeSharpCompilerTestCase("CLI check emits JSON capability call marker diagnostics", CliCheckEmitsJsonCapabilityCallMarkerDiagnostics),
        new TypeSharpCompilerTestCase("CLI check emits JSON unknown access diagnostics", CliCheckEmitsJsonUnknownAccessDiagnostics),
        new TypeSharpCompilerTestCase("CLI check keeps warnings nonblocking by default", CliCheckKeepsWarningsNonblockingByDefault),
        new TypeSharpCompilerTestCase("CLI check treats warnings as errors", CliCheckTreatsWarningsAsErrors),
        new TypeSharpCompilerTestCase("CLI build stops before emission on warnings as errors", CliBuildStopsBeforeEmissionOnWarningsAsErrors),
        new TypeSharpCompilerTestCase("CLI lsp runs language server protocol", CliLspRunsLanguageServerProtocol),
        new TypeSharpCompilerTestCase("CLI lsp rejects unknown options", CliLspRejectsUnknownOptions),
        new TypeSharpCompilerTestCase("LSP diagnostic mapper uses zero-based ranges", LspDiagnosticMapperUsesZeroBasedRanges),
        new TypeSharpCompilerTestCase("language server publishes diagnostics on didOpen", LanguageServerPublishesDiagnosticsOnDidOpen),
        new TypeSharpCompilerTestCase("language server clears diagnostics on didClose", LanguageServerClearsDiagnosticsOnDidClose),
        new TypeSharpCompilerTestCase("language server returns hover for bound symbols", LanguageServerReturnsHoverForBoundSymbols),
        new TypeSharpCompilerTestCase("language server returns definition for bound symbols", LanguageServerReturnsDefinitionForBoundSymbols),
        new TypeSharpCompilerTestCase("language server returns completion items", LanguageServerReturnsCompletionItems),
        new TypeSharpCompilerTestCase("VS Code extension activates LSP client", VsCodeExtensionActivatesLspClient),
        new TypeSharpCompilerTestCase("VS Code extension activation smoke runs in mocked extension host", VsCodeExtensionActivationSmokeRunsInMockedExtensionHost),
        new TypeSharpCompilerTestCase("VS Code extension live smoke runs against bundled language server", VsCodeExtensionLiveSmokeRunsAgainstBundledLanguageServer),
        new TypeSharpCompilerTestCase("VS Code extension package shape is stable", VsCodeExtensionPackageShapeIsStable),
        new TypeSharpCompilerTestCase("VS Code syntax grammar covers stable TypeSharp tokens", VsCodeSyntaxGrammarCoversStableTypeSharpTokens),
        new TypeSharpCompilerTestCase("runnable example catalog smoke matrix is stable", RunnableExampleCatalogSmokeMatrixIsStable),
        new TypeSharpCompilerTestCase("runnable example project commands are smoke-tested", RunnableExampleProjectCommandsAreSmokeTested),
        new TypeSharpCompilerTestCase("docs site contract is stable", DocsSiteContractIsStable),
        new TypeSharpCompilerTestCase("GitHub Pages workflow contract is stable", GitHubPagesWorkflowContractIsStable),
        new TypeSharpCompilerTestCase("release and regression workflow contracts are stable", ReleaseAndRegressionWorkflowContractsAreStable),
        new TypeSharpCompilerTestCase("repository monorepo layout is stable", RepositoryMonorepoLayoutIsStable),
        new TypeSharpCompilerTestCase("CLI build emits generated C# source", CliBuildEmitsGeneratedCSharpSource),
        new TypeSharpCompilerTestCase("CLI build compiles parenthesized expression lowering", CliBuildCompilesParenthesizedExpressionLowering),
        new TypeSharpCompilerTestCase("CLI build uses root namespace for namespace-less source", CliBuildUsesRootNamespaceForNamespaceLessSource),
        new TypeSharpCompilerTestCase("CLI build uses module path containers for multiple sources", CliBuildUsesModulePathContainersForMultipleSources),
        new TypeSharpCompilerTestCase("CLI build lowers relative source named imports", CliBuildLowersRelativeSourceNamedImports),
        new TypeSharpCompilerTestCase("CLI build lowers relative source named import aliases", CliBuildLowersRelativeSourceNamedImportAliases),
        new TypeSharpCompilerTestCase("CLI build lowers relative source value import aliases", CliBuildLowersRelativeSourceValueImportAliases),
        new TypeSharpCompilerTestCase("CLI build lowers relative source type import aliases", CliBuildLowersRelativeSourceTypeImportAliases),
        new TypeSharpCompilerTestCase("CLI build lowers relative source named type import aliases", CliBuildLowersRelativeSourceNamedTypeImportAliases),
        new TypeSharpCompilerTestCase("CLI build lowers relative source namespace imports", CliBuildLowersRelativeSourceNamespaceImports),
        new TypeSharpCompilerTestCase("CLI build lowers relative source re-exports", CliBuildLowersRelativeSourceReExports),
        new TypeSharpCompilerTestCase("CLI build lowers relative source re-export aliases", CliBuildLowersRelativeSourceReExportAliases),
        new TypeSharpCompilerTestCase("CLI build lowers relative source module re-export aliases", CliBuildLowersRelativeSourceModuleReExportAliases),
        new TypeSharpCompilerTestCase("CLI build lowers relative source value re-exports", CliBuildLowersRelativeSourceValueReExports),
        new TypeSharpCompilerTestCase("CLI build lowers relative source type re-exports", CliBuildLowersRelativeSourceTypeReExports),
        new TypeSharpCompilerTestCase("CLI build lowers relative source star re-exports", CliBuildLowersRelativeSourceStarReExports),
        new TypeSharpCompilerTestCase("CLI build lowers source alias re-exports", CliBuildLowersSourceAliasReExports),
        new TypeSharpCompilerTestCase("CLI build lowers source alias value re-export import aliases", CliBuildLowersSourceAliasValueReExportImportAliases),
        new TypeSharpCompilerTestCase("CLI build lowers source alias type re-export imports", CliBuildLowersSourceAliasTypeReExportImports),
        new TypeSharpCompilerTestCase("CLI build lowers source alias module re-export imports", CliBuildLowersSourceAliasModuleReExportImports),
        new TypeSharpCompilerTestCase("CLI build omits ambient function declarations", CliBuildOmitsAmbientFunctionDeclarations),
        new TypeSharpCompilerTestCase("CLI build ignores ambient main entry point", CliBuildIgnoresAmbientMainEntryPoint),
        new TypeSharpCompilerTestCase("CLI build lowers open declarations to using directives", CliBuildLowersOpenDeclarationsToUsingDirectives),
        new TypeSharpCompilerTestCase("CLI build lowers import alias to using alias directive", CliBuildLowersImportAliasToUsingAliasDirective),
        new TypeSharpCompilerTestCase("CLI build lowers namespace import to using alias directive", CliBuildLowersNamespaceImportToUsingAliasDirective),
        new TypeSharpCompilerTestCase("CLI build emits generated C# project scaffold", CliBuildEmitsGeneratedCSharpProjectScaffold),
        new TypeSharpCompilerTestCase("CLI build propagates manifest references to generated C# project", CliBuildPropagatesManifestReferencesToGeneratedCSharpProject),
        new TypeSharpCompilerTestCase("CLI build compiles framework static member call", CliBuildCompilesFrameworkStaticMemberCall),
        new TypeSharpCompilerTestCase("CLI build compiles local DLL static member call", CliBuildCompilesLocalDllStaticMemberCall),
        new TypeSharpCompilerTestCase("CLI build compiles imported constructor and instance member call", CliBuildCompilesImportedConstructorAndInstanceMemberCall),
        new TypeSharpCompilerTestCase("CLI build compiles imported constructor named optional params calls", CliBuildCompilesImportedConstructorNamedOptionalParamsCalls),
        new TypeSharpCompilerTestCase("CLI build compiles imported parameter instance member call", CliBuildCompilesImportedParameterInstanceMemberCall),
        new TypeSharpCompilerTestCase("CLI build compiles imported alias instance member call", CliBuildCompilesImportedAliasInstanceMemberCall),
        new TypeSharpCompilerTestCase("CLI build compiles imported assigned instance member call", CliBuildCompilesImportedAssignedInstanceMemberCall),
        new TypeSharpCompilerTestCase("CLI build compiles imported property access", CliBuildCompilesImportedPropertyAccess),
        new TypeSharpCompilerTestCase("CLI build compiles imported property assignment", CliBuildCompilesImportedPropertyAssignment),
        new TypeSharpCompilerTestCase("CLI build compiles imported field access", CliBuildCompilesImportedFieldAccess),
        new TypeSharpCompilerTestCase("CLI build compiles imported field assignment", CliBuildCompilesImportedFieldAssignment),
        new TypeSharpCompilerTestCase("CLI build compiles imported static property assignment", CliBuildCompilesImportedStaticPropertyAssignment),
        new TypeSharpCompilerTestCase("CLI build compiles imported static field assignment", CliBuildCompilesImportedStaticFieldAssignment),
        new TypeSharpCompilerTestCase("CLI build compiles imported indexer access", CliBuildCompilesImportedIndexerAccess),
        new TypeSharpCompilerTestCase("CLI build compiles imported indexer parenthesized argument", CliBuildCompilesImportedIndexerParenthesizedArgument),
        new TypeSharpCompilerTestCase("CLI build compiles imported indexer numeric literal conversion", CliBuildCompilesImportedIndexerNumericLiteralConversion),
        new TypeSharpCompilerTestCase("CLI build compiles imported overloaded indexer exact match", CliBuildCompilesImportedOverloadedIndexerExactMatch),
        new TypeSharpCompilerTestCase("CLI build compiles imported indexer metadata relationship match", CliBuildCompilesImportedIndexerMetadataRelationshipMatch),
        new TypeSharpCompilerTestCase("CLI build compiles imported indexer null literal match", CliBuildCompilesImportedIndexerNullLiteralMatch),
        new TypeSharpCompilerTestCase("CLI build compiles imported params call", CliBuildCompilesImportedParamsCall),
        new TypeSharpCompilerTestCase("CLI build compiles imported out call", CliBuildCompilesImportedOutCall),
        new TypeSharpCompilerTestCase("CLI build compiles imported in call", CliBuildCompilesImportedInCall),
        new TypeSharpCompilerTestCase("CLI build compiles imported ref call", CliBuildCompilesImportedRefCall),
        new TypeSharpCompilerTestCase("CLI build compiles exact overload match", CliBuildCompilesExactOverloadMatch),
        new TypeSharpCompilerTestCase("CLI build compiles object overload fallback for known argument type", CliBuildCompilesObjectOverloadFallbackForKnownArgumentType),
        new TypeSharpCompilerTestCase("CLI build compiles null literal reference overload match", CliBuildCompilesNullLiteralReferenceOverloadMatch),
        new TypeSharpCompilerTestCase("CLI build compiles null literal metadata relationship overload match", CliBuildCompilesNullLiteralMetadataRelationshipOverloadMatch),
        new TypeSharpCompilerTestCase("CLI build compiles parenthesized null literal metadata relationship overload match", CliBuildCompilesParenthesizedNullLiteralMetadataRelationshipOverloadMatch),
        new TypeSharpCompilerTestCase("CLI build compiles imported metadata overload match", CliBuildCompilesImportedMetadataOverloadMatch),
        new TypeSharpCompilerTestCase("CLI build compiles imported metadata relationship overload match", CliBuildCompilesImportedMetadataRelationshipOverloadMatch),
        new TypeSharpCompilerTestCase("CLI build compiles imported collection expression overload match", CliBuildCompilesImportedCollectionExpressionOverloadMatch),
        new TypeSharpCompilerTestCase("CLI build compiles numeric literal constant conversion", CliBuildCompilesNumericLiteralConstantConversion),
        new TypeSharpCompilerTestCase("CLI build compiles unary numeric constant conversion", CliBuildCompilesUnaryNumericConstantConversion),
        new TypeSharpCompilerTestCase("CLI build compiles imported params collection expression array match", CliBuildCompilesImportedParamsCollectionExpressionArrayMatch),
        new TypeSharpCompilerTestCase("CLI build compiles exact expanded params overload match", CliBuildCompilesExactExpandedParamsOverloadMatch),
        new TypeSharpCompilerTestCase("CLI build compiles imported optional call", CliBuildCompilesImportedOptionalCall),
        new TypeSharpCompilerTestCase("CLI build compiles imported named argument call", CliBuildCompilesImportedNamedArgumentCall),
        new TypeSharpCompilerTestCase("CLI build compiles imported delegate lambda call", CliBuildCompilesImportedDelegateLambdaCall),
        new TypeSharpCompilerTestCase("CLI build compiles imported delegate lambda overload arity match", CliBuildCompilesImportedDelegateLambdaOverloadArityMatch),
        new TypeSharpCompilerTestCase("CLI build compiles imported delegate lambda overload return match", CliBuildCompilesImportedDelegateLambdaOverloadReturnMatch),
        new TypeSharpCompilerTestCase("CLI build compiles imported delegate lambda overload parenthesized argument match", CliBuildCompilesImportedDelegateLambdaOverloadParenthesizedArgumentMatch),
        new TypeSharpCompilerTestCase("CLI build compiles imported delegate lambda overload parameter return match", CliBuildCompilesImportedDelegateLambdaOverloadParameterReturnMatch),
        new TypeSharpCompilerTestCase("CLI build compiles imported delegate lambda overload return ranking", CliBuildCompilesImportedDelegateLambdaOverloadReturnRanking),
        new TypeSharpCompilerTestCase("CLI build compiles imported delegate lambda overload member return match", CliBuildCompilesImportedDelegateLambdaOverloadMemberReturnMatch),
        new TypeSharpCompilerTestCase("CLI build compiles imported delegate lambda overload chained member return match", CliBuildCompilesImportedDelegateLambdaOverloadChainedMemberReturnMatch),
        new TypeSharpCompilerTestCase("CLI build compiles imported delegate lambda overload method return match", CliBuildCompilesImportedDelegateLambdaOverloadMethodReturnMatch),
        new TypeSharpCompilerTestCase("CLI build compiles imported delegate lambda overload extension method return match", CliBuildCompilesImportedDelegateLambdaOverloadExtensionMethodReturnMatch),
        new TypeSharpCompilerTestCase("CLI build compiles imported delegate lambda overload static method return match", CliBuildCompilesImportedDelegateLambdaOverloadStaticMethodReturnMatch),
        new TypeSharpCompilerTestCase("CLI build compiles imported delegate lambda overload binary return match", CliBuildCompilesImportedDelegateLambdaOverloadBinaryReturnMatch),
        new TypeSharpCompilerTestCase("CLI build compiles imported delegate lambda overload binary value return match", CliBuildCompilesImportedDelegateLambdaOverloadBinaryValueReturnMatch),
        new TypeSharpCompilerTestCase("CLI build compiles imported delegate lambda overload nameof return match", CliBuildCompilesImportedDelegateLambdaOverloadNameofReturnMatch),
        new TypeSharpCompilerTestCase("CLI build compiles imported delegate lambda overload checked return match", CliBuildCompilesImportedDelegateLambdaOverloadCheckedReturnMatch),
        new TypeSharpCompilerTestCase("CLI build compiles imported delegate lambda overload satisfies return match", CliBuildCompilesImportedDelegateLambdaOverloadSatisfiesReturnMatch),
        new TypeSharpCompilerTestCase("CLI build compiles imported delegate lambda overload parenthesized return match", CliBuildCompilesImportedDelegateLambdaOverloadParenthesizedReturnMatch),
        new TypeSharpCompilerTestCase("CLI build compiles imported delegate lambda overload logical not return match", CliBuildCompilesImportedDelegateLambdaOverloadLogicalNotReturnMatch),
        new TypeSharpCompilerTestCase("CLI build compiles imported delegate lambda overload unary numeric return match", CliBuildCompilesImportedDelegateLambdaOverloadUnaryNumericReturnMatch),
        new TypeSharpCompilerTestCase("CLI build compiles imported delegate lambda overload if return match", CliBuildCompilesImportedDelegateLambdaOverloadIfReturnMatch),
        new TypeSharpCompilerTestCase("CLI build compiles imported delegate lambda overload block return match", CliBuildCompilesImportedDelegateLambdaOverloadBlockReturnMatch),
        new TypeSharpCompilerTestCase("CLI build compiles imported delegate lambda overload collection return match", CliBuildCompilesImportedDelegateLambdaOverloadCollectionReturnMatch),
        new TypeSharpCompilerTestCase("CLI build compiles imported delegate lambda overload coalesce return match", CliBuildCompilesImportedDelegateLambdaOverloadCoalesceReturnMatch),
        new TypeSharpCompilerTestCase("CLI build compiles imported delegate lambda overload indexer return match", CliBuildCompilesImportedDelegateLambdaOverloadIndexerReturnMatch),
        new TypeSharpCompilerTestCase("CLI build compiles imported event add and remove call", CliBuildCompilesImportedEventAddRemoveCall),
        new TypeSharpCompilerTestCase("CLI build compiles imported extension method instance call", CliBuildCompilesImportedExtensionMethodInstanceCall),
        new TypeSharpCompilerTestCase("CLI build compiles imported extension receiver relationship match", CliBuildCompilesImportedExtensionReceiverRelationshipMatch),
        new TypeSharpCompilerTestCase("CLI build compiles imported extension receiver object fallback", CliBuildCompilesImportedExtensionReceiverObjectFallback),
        new TypeSharpCompilerTestCase("CLI build compiles imported generic method call", CliBuildCompilesImportedGenericMethodCall),
        new TypeSharpCompilerTestCase("CLI build compiles imported explicit generic method call", CliBuildCompilesImportedExplicitGenericMethodCall),
        new TypeSharpCompilerTestCase("CLI build compiles imported generic constraint call", CliBuildCompilesImportedGenericConstraintCall),
        new TypeSharpCompilerTestCase("CLI build compiles imported framework generic constraint call", CliBuildCompilesImportedFrameworkGenericConstraintCall),
        new TypeSharpCompilerTestCase("CLI build compiles imported transitive generic constraint call", CliBuildCompilesImportedTransitiveGenericConstraintCall),
        new TypeSharpCompilerTestCase("CLI build compiles imported inferred generic constraint call", CliBuildCompilesImportedInferredGenericConstraintCall),
        new TypeSharpCompilerTestCase("CLI build compiles imported inferred generic array constraint call", CliBuildCompilesImportedInferredGenericArrayConstraintCall),
        new TypeSharpCompilerTestCase("CLI build compiles imported inferred constructed generic constraint call", CliBuildCompilesImportedInferredConstructedGenericConstraintCall),
        new TypeSharpCompilerTestCase("CLI build compiles imported interface reference", CliBuildCompilesImportedInterfaceReference),
        new TypeSharpCompilerTestCase("CLI build compiles imported interface implementation return", CliBuildCompilesImportedInterfaceImplementationReturn),
        new TypeSharpCompilerTestCase("CLI build compiles imported attribute and generic type references", CliBuildCompilesImportedAttributeAndGenericTypeReferences),
        new TypeSharpCompilerTestCase("CLI build compiles imported generic type constructor call", CliBuildCompilesImportedGenericTypeConstructorCall),
        new TypeSharpCompilerTestCase("CLI build compiles basic semantics", CliBuildCompilesBasicSemantics),
        new TypeSharpCompilerTestCase("CLI build compiles module namespace", CliBuildCompilesModuleNamespace),
        new TypeSharpCompilerTestCase("CLI build compiles core option result APIs", CliBuildCompilesCoreOptionResultApis),
        new TypeSharpCompilerTestCase("CLI build compiles generic function API", CliBuildCompilesGenericFunctionApi),
        new TypeSharpCompilerTestCase("CLI build compiles class declaration API", CliBuildCompilesClassDeclarationApi),
        new TypeSharpCompilerTestCase("CLI build compiles interface declaration API", CliBuildCompilesInterfaceDeclarationApi),
        new TypeSharpCompilerTestCase("CLI build compiles enum declaration API", CliBuildCompilesEnumDeclarationApi),
        new TypeSharpCompilerTestCase("CLI build compiles integral bitwise expression API", CliBuildCompilesIntegralBitwiseExpressionApi),
        new TypeSharpCompilerTestCase("CLI build compiles boolean bitwise expression API", CliBuildCompilesBooleanBitwiseExpressionApi),
        new TypeSharpCompilerTestCase("CLI build compiles bitwise compound assignment API", CliBuildCompilesBitwiseCompoundAssignmentApi),
        new TypeSharpCompilerTestCase("CLI build compiles enum match exhaustiveness", CliBuildCompilesEnumMatchExhaustiveness),
        new TypeSharpCompilerTestCase("CLI build compiles imported C# enum match exhaustiveness", CliBuildCompilesImportedCSharpEnumMatchExhaustiveness),
        new TypeSharpCompilerTestCase("CLI build compiles partial declaration API", CliBuildCompilesPartialDeclarationApi),
        new TypeSharpCompilerTestCase("CLI build compiles generic type declaration API", CliBuildCompilesGenericTypeDeclarationApi),
        new TypeSharpCompilerTestCase("CLI build compiles generic constraint API", CliBuildCompilesGenericConstraintApi),
        new TypeSharpCompilerTestCase("CLI build compiles immutable record API", CliBuildCompilesImmutableRecordApi),
        new TypeSharpCompilerTestCase("CLI build compiles record update lowering", CliBuildCompilesRecordUpdateLowering),
        new TypeSharpCompilerTestCase("CLI build compiles record expression construction", CliBuildCompilesRecordExpressionConstruction),
        new TypeSharpCompilerTestCase("CLI build compiles keyof type operator", CliBuildCompilesKeyofTypeOperator),
        new TypeSharpCompilerTestCase("CLI build compiles indexed access type operator", CliBuildCompilesIndexedAccessTypeOperator),
        new TypeSharpCompilerTestCase("CLI build compiles nominal union API", CliBuildCompilesNominalUnionApi),
        new TypeSharpCompilerTestCase("CLI build compiles nominal union match lowering", CliBuildCompilesNominalUnionMatchLowering),
        new TypeSharpCompilerTestCase("CLI build compiles type-level union narrowing", CliBuildCompilesTypeLevelUnionNarrowing),
        new TypeSharpCompilerTestCase("CLI build compiles async Task interop", CliBuildCompilesAsyncTaskInterop),
        new TypeSharpCompilerTestCase("CLI build compiles collection expression lowering", CliBuildCompilesCollectionExpressionLowering),
        new TypeSharpCompilerTestCase("CLI build compiles pipeline lowering", CliBuildCompilesPipelineLowering),
        new TypeSharpCompilerTestCase("CLI build compiles TypeSharp params parameter lowering", CliBuildCompilesTypeSharpParamsParameterLowering),
        new TypeSharpCompilerTestCase("CLI build compiles TypeSharp optional/default parameter lowering", CliBuildCompilesTypeSharpOptionalDefaultParameterLowering),
        new TypeSharpCompilerTestCase("CLI build compiles TypeSharp named argument lowering", CliBuildCompilesTypeSharpNamedArgumentLowering),
        new TypeSharpCompilerTestCase("CLI build compiles composition lowering", CliBuildCompilesCompositionLowering),
        new TypeSharpCompilerTestCase("CLI build compiles satisfies expression", CliBuildCompilesSatisfiesExpression),
        new TypeSharpCompilerTestCase("CLI build compiles yield iterator lowering", CliBuildCompilesYieldIteratorLowering),
        new TypeSharpCompilerTestCase("CLI build compiles lock statement lowering", CliBuildCompilesLockStatementLowering),
        new TypeSharpCompilerTestCase("CLI build compiles extension method lowering", CliBuildCompilesExtensionMethodLowering),
        new TypeSharpCompilerTestCase("CLI build compiles nameof intrinsic", CliBuildCompilesNameofIntrinsic),
        new TypeSharpCompilerTestCase("CLI build compiles checked unchecked expressions", CliBuildCompilesCheckedUncheckedExpressions),
        new TypeSharpCompilerTestCase("CLI build compiles literal constants", CliBuildCompilesLiteralConstants),
        new TypeSharpCompilerTestCase("CLI build emits generated net48 assembly", CliBuildEmitsGeneratedNet48Assembly),
        new TypeSharpCompilerTestCase("generated net48 assembly public ABI snapshot is stable", GeneratedNet48AssemblyPublicAbiSnapshotIsStable),
        new TypeSharpCompilerTestCase("C# net48 project consumes generated TypeSharp assembly", CSharpNet48ProjectConsumesGeneratedTypeSharpAssembly),
        new TypeSharpCompilerTestCase("net48 application model hosts reference generated assembly and runtime", Net48ApplicationModelHostsReferenceGeneratedAssemblyAndRuntime),
        new TypeSharpCompilerTestCase("compiler check keeps parallel diagnostics in source order", CompilerCheckKeepsParallelDiagnosticsInSourceOrder),
        new TypeSharpCompilerTestCase("compiler check performance smoke stays bounded", CompilerCheckPerformanceSmokeStaysBounded),
        new TypeSharpCompilerTestCase("CLI build stops before emission on diagnostics", CliBuildStopsBeforeEmissionOnDiagnostics),
    };
}
