// <auto-generated />

namespace Samples.Keyof
{
    public static class Module
    {
        internal static string nameKey()
        {
            return "Name";
        }

        internal static bool isName(string key)
        {
            return key == "Name";
        }
    }

    internal sealed class Customer
    {
        public Customer(string Name, int Age)
        {
            this.Name = Name;
            this.Age = Age;
        }

        public string Name { get; }
        public int Age { get; }

        public override bool Equals(object obj)
        {
            var other = obj as Customer;
            return other != null && object.Equals(Name, other.Name) && object.Equals(Age, other.Age);
        }

        public override int GetHashCode()
        {
            unchecked
            {
                var hash = 17;
                hash = (hash * 397) ^ (object.Equals(Name, null) ? 0 : Name.GetHashCode());
                hash = (hash * 397) ^ (object.Equals(Age, null) ? 0 : Age.GetHashCode());
                return hash;
            }
        }
    }
}
