// <auto-generated />

namespace Samples.OptionalDefaultParameterLowering
{
    public static class Module
    {
        public static string decorate(string value, string prefix = "[", string suffix = "]")
        {
            return prefix + value + suffix;
        }

        public static int increment(int value, int amount = 1)
        {
            return value + amount;
        }

        public static bool choose(bool enabled = true)
        {
            return enabled;
        }

        public static string maybe(string value = null)
        {
            return value;
        }

        public static string main()
        {
            var decorated = decorate("value");
            var full = decorate("value", "<", ">");
            var incremented = increment(1);
            var chosen = choose();
            return decorated + full + incremented.ToString() + chosen.ToString();
        }
    }
}
