// <auto-generated />

using TypeSharp.Runtime;

namespace Samples.EnumMatches
{
    public static class Module
    {
        public static string describe(Color color)
        {
            return new System.Func<string>(delegate()
            {
                var __match0 = color;
                if (object.Equals(__match0, Color.Red))
                {
                    return "red";
                }

                if (object.Equals(__match0, Color.Green))
                {
                    if (color == Color.Green)
                    {
                        return "green";
                    }
                }

                {
                    return "other";
                }

                throw TypeSharpPattern.NoMatch(__match0);
            })();
        }
    }

    internal enum Color
    {
        Red,
        Green,
        Blue
    }
}
