// <auto-generated />

using TypeSharp.Runtime;

namespace Samples.Unions
{
    public static class Module
    {
        public static string describe(PaymentStatus status)
        {
            return new System.Func<string>(delegate()
            {
                var __match0 = status;
                if (TypeSharpPattern.IsPayloadlessCase(__match0, 0))
                {
                    return "Waiting";
                }

                if (TypeSharpPattern.IsPayloadCase(__match0, 1))
                {
                    var at = TypeSharpPattern.RequirePayload<string>(__match0, 1);
                    return $"Paid:{at}";
                }

                if (TypeSharpPattern.IsPayloadCase(__match0, 2))
                {
                    var reason = TypeSharpPattern.RequirePayload<string>(__match0, 2);
                    return $"Failed:{reason}";
                }

                throw TypeSharpPattern.NoMatch(__match0);
            })();
        }

        public static string describeWithFallback(PaymentStatus status)
        {
            return new System.Func<string>(delegate()
            {
                var __match1 = status;
                if (TypeSharpPattern.IsPayloadlessCase(__match1, 0))
                {
                    return "Waiting";
                }

                {
                    return "Settled";
                }

                throw TypeSharpPattern.NoMatch(__match1);
            })();
        }
    }

    public abstract class PaymentStatus
    {
        private PaymentStatus()
        {
        }

        public static PaymentStatus Pending
        {
            get
            {
                return PendingCase.Instance;
            }
        }

        public static PaymentStatus Paid(string at)
        {
            return new PaidCase(at);
        }

        public static PaymentStatus Failed(string reason)
        {
            return new FailedCase(reason);
        }

        public sealed class PendingCase : PaymentStatus, ITypeSharpUnionCase
        {
            public static readonly PendingCase Instance = new PendingCase();

            private PendingCase()
            {
            }

            public int Tag
            {
                get
                {
                    return 0;
                }
            }

            public string CaseName
            {
                get
                {
                    return "Pending";
                }
            }

            public bool HasPayload
            {
                get
                {
                    return false;
                }
            }

            public object Payload
            {
                get
                {
                    throw new System.InvalidOperationException("Union case has no payload.");
                }
            }

            public override bool Equals(object obj)
            {
                return obj is PendingCase;
            }

            public override int GetHashCode()
            {
                return TypeSharpUnion.CombineHash(Tag, null);
            }
        }

        public sealed class PaidCase : PaymentStatus, ITypeSharpUnionCase
        {
            public PaidCase(string at)
            {
                this.at = at;
            }

            public string at { get; }

            public int Tag
            {
                get
                {
                    return 1;
                }
            }

            public string CaseName
            {
                get
                {
                    return "Paid";
                }
            }

            public bool HasPayload
            {
                get
                {
                    return true;
                }
            }

            public object Payload
            {
                get
                {
                    return at;
                }
            }

            public override bool Equals(object obj)
            {
                var other = obj as PaidCase;
                return other != null && object.Equals(at, other.at);
            }

            public override int GetHashCode()
            {
                return TypeSharpUnion.CombineHash(Tag, at);
            }
        }

        public sealed class FailedCase : PaymentStatus, ITypeSharpUnionCase
        {
            public FailedCase(string reason)
            {
                this.reason = reason;
            }

            public string reason { get; }

            public int Tag
            {
                get
                {
                    return 2;
                }
            }

            public string CaseName
            {
                get
                {
                    return "Failed";
                }
            }

            public bool HasPayload
            {
                get
                {
                    return true;
                }
            }

            public object Payload
            {
                get
                {
                    return reason;
                }
            }

            public override bool Equals(object obj)
            {
                var other = obj as FailedCase;
                return other != null && object.Equals(reason, other.reason);
            }

            public override int GetHashCode()
            {
                return TypeSharpUnion.CombineHash(Tag, reason);
            }
        }
    }
}
