// <auto-generated />

namespace Samples.InstanceValues
{
    public static class Module
    {
    }

    public class BuildInfo
    {
        public readonly string Name = "TypeSharp";

        public static string Echo(string value)
        {
            return value;
        }
    }
}
