// <auto-generated />

namespace Samples.Events
{
    public static class Module
    {
    }

    public class Notifier
    {
        public event ChangedHandler Changed;

        public string Echo(string value)
        {
            return value;
        }
    }

    public delegate void ChangedHandler(string value);
}
