// <auto-generated />

using System;
using TypeSharp.Runtime;

namespace Samples.Unions
{
    public static class Module
    {
        public static PaymentStatus pending()
        {
            return PaymentStatus.Pending;
        }

        public static PaymentStatus paid(string at)
        {
            return PaymentStatus.Paid(at);
        }
    }

    [ObsoleteAttribute("Use PaymentStatus2.")]
    public abstract class PaymentStatus
    {
        private PaymentStatus()
        {
        }

        public static PaymentStatus Pending
        {
            get
            {
                return PendingCase.Instance;
            }
        }

        public static PaymentStatus Paid(string at)
        {
            return new PaidCase(at);
        }

        public sealed class PendingCase : PaymentStatus, ITypeSharpUnionCase
        {
            public static readonly PendingCase Instance = new PendingCase();

            private PendingCase()
            {
            }

            public int Tag
            {
                get
                {
                    return 0;
                }
            }

            public string CaseName
            {
                get
                {
                    return "Pending";
                }
            }

            public bool HasPayload
            {
                get
                {
                    return false;
                }
            }

            public object Payload
            {
                get
                {
                    throw new System.InvalidOperationException("Union case has no payload.");
                }
            }

            public override bool Equals(object obj)
            {
                return obj is PendingCase;
            }

            public override int GetHashCode()
            {
                return TypeSharpUnion.CombineHash(Tag, null);
            }
        }

        public sealed class PaidCase : PaymentStatus, ITypeSharpUnionCase
        {
            public PaidCase(string at)
            {
                this.at = at;
            }

            public string at { get; }

            public int Tag
            {
                get
                {
                    return 1;
                }
            }

            public string CaseName
            {
                get
                {
                    return "Paid";
                }
            }

            public bool HasPayload
            {
                get
                {
                    return true;
                }
            }

            public object Payload
            {
                get
                {
                    return at;
                }
            }

            public override bool Equals(object obj)
            {
                var other = obj as PaidCase;
                return other != null && object.Equals(at, other.at);
            }

            public override int GetHashCode()
            {
                return TypeSharpUnion.CombineHash(Tag, at);
            }
        }
    }
}
