// <auto-generated />

namespace Samples.BackendLiterals
{
    public static class Module
    {
        public const string ApiVersion = "1.0";
        public const int MaxRetryCount = 3;
        internal const bool FeatureEnabled = true;
        public const decimal TaxRate = 1.5m;

        public static string version()
        {
            return ApiVersion;
        }

        public static int retries()
        {
            return MaxRetryCount;
        }

        public static bool enabled()
        {
            return FeatureEnabled;
        }

        public static decimal rate()
        {
            return TaxRate;
        }
    }
}
