// <auto-generated />

using System.Text;

namespace Samples.BackendBlocks
{
    public static class Module
    {
        public static string render()
        {
            var builder = new StringBuilder();
            builder.Append("Hello, ");
            builder.Append("TypeSharp");
            return builder.ToString();
        }
    }
}
