// <auto-generated />

namespace Samples.Constructors
{
    public static class Module
    {
    }

    public class Formatter
    {
        public Formatter(string prefix, params string[] values)
        {
        }

        public int Count = 0;

        public string Echo(string value)
        {
            return value;
        }
    }
}
