// <auto-generated />

namespace Samples.CheckedExpressions
{
    public static class Module
    {
        public static int checkedAdd(int value)
        {
            return checked(value + 1);
        }

        public static int uncheckedAdd(int value)
        {
            return unchecked(value + 1);
        }
    }
}
