// <auto-generated />

namespace Samples.Nameof
{
    public static class Module
    {
        public static string propertyName()
        {
            return nameof(Customer.Name);
        }

        public static string parameterName(string value)
        {
            return nameof(value);
        }
    }

    public sealed class Customer
    {
        public Customer(string Name)
        {
            this.Name = Name;
        }

        public string Name { get; }

        public override bool Equals(object obj)
        {
            var other = obj as Customer;
            return other != null && object.Equals(Name, other.Name);
        }

        public override int GetHashCode()
        {
            unchecked
            {
                var hash = 17;
                hash = (hash * 397) ^ (object.Equals(Name, null) ? 0 : Name.GetHashCode());
                return hash;
            }
        }
    }
}
