// <auto-generated />

namespace Samples.Indexers
{
    public static class Module
    {
        public static string firstName()
        {
            var names = new string[] { "Ada", "Grace" };
            return names[0];
        }
    }
}
