// <auto-generated />

using Legacy.Tools;

namespace Samples.BackendEvents
{
    public static class Module
    {
        public static string subscribe()
        {
            var source = new LegacyEvents();
            source.Transform += text => text;
            source.Transform -= text => text;
            source.Transform += text => text;
            return source.Raise("value");
        }
    }
}
