// <auto-generated />

namespace Samples.LogicalUnsignedShiftAssignment
{
    public static class Module
    {
        internal static int adjust(int value, byte count)
        {
            var result = value;
            result = unchecked((int)(unchecked((uint)(result)) >> count));
            return result;
        }

        internal static long adjustLong(long value, short count)
        {
            var result = value;
            result = unchecked((long)(unchecked((ulong)(result)) >> count));
            return result;
        }

        internal static byte adjustSmall(byte value, int count)
        {
            var result = value;
            result = unchecked((byte)(unchecked((uint)(result)) >> count));
            return result;
        }

        internal static uint adjustUnsigned(uint value, int count)
        {
            var result = value;
            result = result >> count;
            return result;
        }
    }
}
