// <auto-generated />

using System.Threading.Tasks;

namespace Samples.AsyncInterop
{
    public static class Module
    {
        public static async Task<string> greeting()
        {
            var value = await Task.FromResult("Hello, async");
            return value;
        }
    }
}
