// <auto-generated />

namespace Samples.Enums
{
    public static class Module
    {
        public static Color favorite()
        {
            return Color.Green;
        }
    }

    public enum Color
    {
        Red,
        Green,
        Blue
    }
}
