// <auto-generated />

using System;

namespace Samples.Enums
{
    public static class Module
    {
        public static Color favorite()
        {
            return Color.Green;
        }
    }

    [FlagsAttribute]
    public enum Color : byte
    {
        Red = 1,
        Crimson = Red,
        [ObsoleteAttribute("Use Blue instead.")]
        Green,
        Blue = 4
    }
}
