// <auto-generated />

namespace Samples.RecordExpressions
{
    public static class Module
    {
        public static Customer create()
        {
            return new Customer("Ada", 36);
        }

        public static Customer localCreate()
        {
            var customer = new Customer("Grace", 42);
            return customer;
        }
    }

    public sealed class Customer
    {
        public Customer(string Name, int Age)
        {
            this.Name = Name;
            this.Age = Age;
        }

        public string Name { get; }
        public int Age { get; }

        public override bool Equals(object obj)
        {
            var other = obj as Customer;
            return other != null && object.Equals(Name, other.Name) && object.Equals(Age, other.Age);
        }

        public override int GetHashCode()
        {
            unchecked
            {
                var hash = 17;
                hash = (hash * 397) ^ (object.Equals(Name, null) ? 0 : Name.GetHashCode());
                hash = (hash * 397) ^ (object.Equals(Age, null) ? 0 : Age.GetHashCode());
                return hash;
            }
        }
    }
}
