// <auto-generated />

namespace Samples.Classes
{
    public static class Module
    {
    }

    public class Greeter
    {
        public string Echo(string value)
        {
            return value;
        }
    }
}
