// <auto-generated />

using System.Collections.Generic;

namespace Samples.DirectGenericFunctionCallLowering
{
    public static class Module
    {
        internal static T identity<T>(T value)
        {
            return value;
        }

        internal static T choose<T>(T left, T right)
        {
            return left;
        }

        internal static T[] keepArray<T>(T[] items)
        {
            return items;
        }

        internal static List<T> keepList<T>(List<T> items)
        {
            return items;
        }

        internal static string asText(string value)
        {
            return value;
        }

        public static string main()
        {
            var text = identity("a");
            var typed = identity<string>(text);
            var chosen = choose(text, typed);
            var numbers = new int[] { 1, 2 };
            var copiedNumbers = keepArray(numbers);
            var explicitNumbers = keepArray<int>(copiedNumbers);
            var names = new List<string> { "a", "b" };
            var copiedNames = keepList(names);
            var explicitNames = keepList<string>(copiedNames);
            return asText(chosen);
        }
    }
}
