// <auto-generated />

namespace Samples.DirectGenericFunctionCallLowering
{
    public static class Module
    {
        internal static T identity<T>(T value)
        {
            return value;
        }

        internal static T choose<T>(T left, T right)
        {
            return left;
        }

        internal static string asText(string value)
        {
            return value;
        }

        public static string main()
        {
            var text = identity("a");
            var typed = identity<string>(text);
            var chosen = choose(text, typed);
            return asText(chosen);
        }
    }
}
