// <auto-generated />

namespace Samples.ShiftAssignment
{
    public static class Module
    {
        public static int adjust(int value, ushort count)
        {
            var result = value;
            result <<= count;
            result >>= 1;
            return result;
        }

        public static uint adjustUnsigned(uint value, int count)
        {
            var result = value;
            result >>= count;
            result <<= 2;
            return result;
        }

        public static byte adjustSmall(byte value, int count)
        {
            var result = value;
            result <<= count;
            result >>= 1;
            return result;
        }
    }
}
