// <auto-generated />

namespace Samples.IntegralBitwise
{
    public static class Module
    {
        public static int literalFlags()
        {
            return 1 | 2;
        }

        public static int literalInvert()
        {
            return ~0;
        }

        public static int mask(int value)
        {
            return value & 3;
        }

        public static int toggle(int value)
        {
            return value ^ 1;
        }
    }
}
