// <auto-generated />

namespace Samples.Pipeline
{
    public static class Module
    {
        public static int increment(int value)
        {
            return value + 1;
        }

        public static int add(int value, int amount)
        {
            return value + amount;
        }

        public static string format(int value)
        {
            return value.ToString();
        }

        public static string compute()
        {
            return format(add(increment(1), 2));
        }
    }
}
