// <auto-generated />

using System;

namespace Samples.MemberAttributes
{
    public static class Module
    {
    }

    public class Greeter
    {
        [ObsoleteAttribute("Use NewChanged.")]
        public event ChangedHandler Changed;

        [ObsoleteAttribute("Use NewName.")]
        public readonly string Name = "Ada";

        [ObsoleteAttribute("Use DisplayName2.")]
        public string DisplayName { get; } = "Ada Lovelace";

        [ObsoleteAttribute("Use Nickname2.")]
        public string Nickname { get; set; } = "ada";

        [ObsoleteAttribute("Use Say.")]
        public string Echo(string value)
        {
            return value;
        }
    }

    public interface IGreeter
    {
        [ObsoleteAttribute("Use NewUpdated.")]
        event ChangedHandler Updated;

        [ObsoleteAttribute("Use Title2.")]
        string Title { get; }

        [ObsoleteAttribute("Use Alias2.")]
        string Alias { get; set; }

        [ObsoleteAttribute("Use Talk.")]
        string Echo(string value);
    }

    public delegate void ChangedHandler(string value);
}
