// <auto-generated />

namespace Samples.ParamsParameterLowering
{
    public static class Module
    {
        internal static string join(string separator, params string[] values)
        {
            return separator;
        }

        internal static int sum(params int[] values)
        {
            return 0;
        }

        public static string main()
        {
            var names = new string[] { "a", "b" };
            var numbers = new int[] { 1, 2 };
            var expanded = join(",", "a", "b");
            var exact = join(",", names);
            var total = sum(1, 2, 3);
            var piped = sum(1, 2, 3);
            var exactPipe = sum(numbers);
            return expanded + exact + total.ToString() + piped.ToString() + exactPipe.ToString();
        }
    }
}
