// <auto-generated />

namespace Samples.DirectNamedArgumentLowering
{
    public static class Module
    {
        public static string decorate(string value, string prefix = "[", string suffix = "]")
        {
            return prefix + value + suffix;
        }

        public static int add(int left, int right)
        {
            return left + right;
        }

        public static string main()
        {
            var direct = decorate("value", "<", ">");
            var reordered = decorate("value", "[", ">");
            var mixed = decorate("value", "[", ">");
            var sum = add(1, 2);
            var piped = decorate("value", "[", ">");
            return direct + reordered + mixed + sum.ToString() + piped;
        }
    }
}
