// <auto-generated />

namespace Samples.Composition
{
    public static class Module
    {
        public static readonly System.Func<int, string> formatAfterIncrement = __compose0 => format(increment(__compose0));

        public static readonly System.Func<int, string> formatBeforeIncrement = __compose1 => format(increment(__compose1));

        public static readonly System.Func<int, string> formatAfterIdentity = __compose2 => format(identity(__compose2));

        public static readonly System.Func<int, int> identityAfterIncrement = __compose3 => identity(increment(__compose3));

        public static readonly System.Func<int[], int> countAfterArrayIdentity = __compose4 => arrayCount(arrayIdentity(__compose4));

        public static int increment(int value)
        {
            return value + 1;
        }

        public static string format(int value)
        {
            return value.ToString();
        }

        internal static T identity<T>(T value)
        {
            return value;
        }

        internal static T[] arrayIdentity<T>(T[] items)
        {
            return items;
        }

        internal static int arrayCount<T>(T[] items)
        {
            return 1;
        }
    }
}
