// <auto-generated />

namespace Samples.Composition
{
    public static class Module
    {
        public static readonly System.Func<int, string> formatAfterIncrement = __compose0 => format(increment(__compose0));

        public static readonly System.Func<int, string> formatBeforeIncrement = __compose1 => format(increment(__compose1));

        public static int increment(int value)
        {
            return value + 1;
        }

        public static string format(int value)
        {
            return value.ToString();
        }
    }
}
