// <auto-generated />

namespace Samples.RecordSpread
{
    public static class Module
    {
        public static Customer older(Customer customer)
        {
            return new Customer(customer.Name, 43);
        }

        public static Customer fromExtended(ExtendedCustomer customer)
        {
            return new Customer(customer.Name, customer.Age);
        }
    }

    public sealed class Customer
    {
        public Customer(string Name, int Age)
        {
            this.Name = Name;
            this.Age = Age;
        }

        public string Name { get; }
        public int Age { get; }

        public override bool Equals(object obj)
        {
            var other = obj as Customer;
            return other != null && object.Equals(Name, other.Name) && object.Equals(Age, other.Age);
        }

        public override int GetHashCode()
        {
            unchecked
            {
                var hash = 17;
                hash = (hash * 397) ^ (object.Equals(Name, null) ? 0 : Name.GetHashCode());
                hash = (hash * 397) ^ (object.Equals(Age, null) ? 0 : Age.GetHashCode());
                return hash;
            }
        }
    }

    public sealed class ExtendedCustomer
    {
        public ExtendedCustomer(string Name, int Age, string Tier)
        {
            this.Name = Name;
            this.Age = Age;
            this.Tier = Tier;
        }

        public string Name { get; }
        public int Age { get; }
        public string Tier { get; }

        public override bool Equals(object obj)
        {
            var other = obj as ExtendedCustomer;
            return other != null && object.Equals(Name, other.Name) && object.Equals(Age, other.Age) && object.Equals(Tier, other.Tier);
        }

        public override int GetHashCode()
        {
            unchecked
            {
                var hash = 17;
                hash = (hash * 397) ^ (object.Equals(Name, null) ? 0 : Name.GetHashCode());
                hash = (hash * 397) ^ (object.Equals(Age, null) ? 0 : Age.GetHashCode());
                hash = (hash * 397) ^ (object.Equals(Tier, null) ? 0 : Tier.GetHashCode());
                return hash;
            }
        }
    }
}
