// <auto-generated />

namespace Samples.BitwiseCompoundAssignment
{
    public static class Module
    {
        public static int updateBits()
        {
            var value = 1;
            value |= 2;
            value &= 3;
            value ^= 4;
            return value;
        }

        public static Permission updateFlags()
        {
            var permission = Permission.Read;
            permission |= Permission.Write;
            permission &= Permission.ReadWrite;
            permission ^= Permission.Write;
            return permission;
        }

        public static bool updateBool()
        {
            var flag = true;
            flag &= false;
            flag |= true;
            flag ^= false;
            return flag;
        }
    }

    public enum Permission
    {
        None,
        Read,
        Write,
        ReadWrite = Read | Write
    }
}
