// <auto-generated />

using Legacy.Tools;

namespace Samples.BackendLambdas
{
    public static class Module
    {
        public static string apply()
        {
            return LegacyDelegates.Apply("value", text => text);
        }
    }
}
