// <auto-generated />

namespace Samples.StaticMethods
{
    public static class Module
    {
    }

    public class Calculator
    {
        public static int Identity(int value)
        {
            return value;
        }

        public string Echo(string value)
        {
            return value;
        }
    }
}
