// <auto-generated />

namespace Samples.StaticEvents
{
    public static class Module
    {
    }

    public class Notifier
    {
        public static event ChangedHandler GlobalChanged;

        public event ChangedHandler Changed;

        public string Echo(string value)
        {
            return value;
        }
    }

    public delegate void ChangedHandler(string value);
}
