// <auto-generated />

using TypeSharp.Runtime;

namespace Samples.Partials
{
    public static class Module
    {
    }

    public static partial class Hooks
    {
        public static string label()
        {
            return "hook";
        }
    }

    public sealed partial class Customer
    {
        public Customer(string Name)
        {
            this.Name = Name;
        }

        public string Name { get; }

        public override bool Equals(object obj)
        {
            var other = obj as Customer;
            return other != null && object.Equals(Name, other.Name);
        }

        public override int GetHashCode()
        {
            unchecked
            {
                var hash = 17;
                hash = (hash * 397) ^ (object.Equals(Name, null) ? 0 : Name.GetHashCode());
                return hash;
            }
        }
    }

    public abstract partial class Status
    {
        private Status()
        {
        }

        public static Status Pending
        {
            get
            {
                return PendingCase.Instance;
            }
        }

        public sealed class PendingCase : Status, ITypeSharpUnionCase
        {
            public static readonly PendingCase Instance = new PendingCase();

            private PendingCase()
            {
            }

            public int Tag
            {
                get
                {
                    return 0;
                }
            }

            public string CaseName
            {
                get
                {
                    return "Pending";
                }
            }

            public bool HasPayload
            {
                get
                {
                    return false;
                }
            }

            public object Payload
            {
                get
                {
                    throw new System.InvalidOperationException("Union case has no payload.");
                }
            }

            public override bool Equals(object obj)
            {
                return obj is PendingCase;
            }

            public override int GetHashCode()
            {
                return TypeSharpUnion.CombineHash(Tag, null);
            }
        }
    }

    public partial class Greeter
    {
        public string Echo(string value)
        {
            return value;
        }
    }

    public partial interface IGreeter
    {
        string Echo(string value);
    }
}
