// <auto-generated />

using System.Text.RegularExpressions;

namespace Samples.BackendCalls
{
    public static class Module
    {
        public static bool isSlug()
        {
            return Regex.IsMatch("hello", "^[a-z]+$");
        }
    }
}
