// <auto-generated />

using System.Collections.Generic;

namespace Samples.CollectionSpread
{
    public static class Module
    {
        public static int[] combined(int[] xs, int[] ys)
        {
            return System.Linq.Enumerable.ToArray<int>(System.Linq.Enumerable.Concat<int>(System.Linq.Enumerable.Concat<int>(System.Linq.Enumerable.Concat<int>(new int[] { 0 }, xs), ys), new int[] { 4 }));
        }

        public static List<int> listCombined(int[] xs, List<int> ys)
        {
            return new List<int>(System.Linq.Enumerable.Concat<int>(System.Linq.Enumerable.Concat<int>(System.Linq.Enumerable.Concat<int>(new int[] { 0 }, xs), ys), new int[] { 4 }));
        }
    }
}
