// <auto-generated />

namespace Samples.InterfaceProperties
{
    public static class Module
    {
    }

    public interface IBuildInfo
    {
        string Name { get; }

        int Version { get; }
    }
}
