// <auto-generated />

using System;
using System.Threading.Tasks;
using System.Text;
using System.Globalization;
using Text = System.Text;
using Builder = System.Text.StringBuilder;
using static System.Math;

namespace Samples.BackendImports
{
    public static class Module
    {
        public static string greeting()
        {
            return "Hello, imports";
        }
    }
}
