// <auto-generated />

namespace Samples.IntegralShift
{
    public static class Module
    {
        public static int literalLeft()
        {
            return 1 << 3;
        }

        public static int literalRight()
        {
            return 16 >> 2;
        }

        public static int shiftByte(byte value, ushort count)
        {
            return value << count;
        }

        public static uint shiftUnsigned(uint value, int count)
        {
            return value >> count;
        }

        public static long shiftLong(long value, short count)
        {
            return value << count;
        }

        public static int combined(int value)
        {
            return (value << 2) >> 1;
        }
    }
}
